### ISSUE TITLE
isFileChanged() for ofImage, ofVideoPlayer, ofSoundPlayer and ofFile

### ISSUE THREAD

**Issue by imanhabib** [openframeworks/openFrameworks#1120]
When loading a file with ofImage, ofSoundPlayer , ofVideoPlayer-file or any ofFile it would be nice to be able to know if the file changed since it was loaded.

Its very simple to implement with Poco::File->getLastModified() and it would be very nice if this would be built into the above classes.

**Comment by bakercp** [comment]
I'm not sure that `ofImage`, `ofVideoPlayer`, `ofSoundPlayer` should have the responsibility of keep track of the status of the underlying data.  In fact, it assumes that the underlying data is a local file.  For instance, some `ofVideoPlayer` can play streaming content.  ofImage can load remote images, etc.

Since there hasn't been much movement on this since 2011, I'm going to close this issue for now.  If there is an outcry, please reopen it :).
