### ISSUE TITLE
look into adding video streaming support to AVFoundationPlayer

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#1741]
the initial forum topic is here,
http://forum.openframeworks.cc/index.php/topic,11497

**Comment by pizthewiz** [comment]
Not sure if this fits in 0.9.0 still, regardless the iOS and OS X players will merge soon via #3590, so adding the _macOS_ label here too.

**Comment by ofTheo** [comment]
can confirm this is still an issue and with the single AV player now for iOS and OSX.

**Comment by pizthewiz** [comment]
I think @dantheman and @vade looked into this a bit during the dev jam weekend in early January. Snooping around I see a branch [vade/openFrameworks/AVFoundation_HLS_Fix](https://github.com/vade/openFrameworks/tree/AVFoundation_HLS_Fix) but I'm not sure if it bore fruit and of course we just swapped video players in #3590 so…

**Comment by vade** [comment]
Oh - ha. Yea. Life and all that. This 'works' in as much as I can get a stream to 'play' in quotes, but something upstream in the texture uploading is fucking up royally because some checking / assertion about width/height and CVPIxelBuffer square pixel nonesense. 

Basically, some streams aren't square pixel aspect ratio. The test stream isn't. Also the method you request width and height doesnt work until the video is rolling, so its kind of a setup catch 22.

I spoke with @danthemellowman about this a while back and then got annoyed with it and put it down.

BASICALLYICANTFINISHANYTHINGOK.

:P

Feel free to look at what I have and see if you can figure out whats what. if you fire off the apple HSL test stream you'll hear audio IIRC, but won't get video due to the above oddities in the texture upload pipeline.

**Comment by pizthewiz** [comment]
Awesome, that is super helpful and provides some good intel to work from. It looks like the commit to scope out is [58843ff6](https://github.com/vade/openFrameworks/commit/58843ff68e44e5c04fe51890b175a3e40e280de3). Not sure if the _new_ new (hours old) AV Foundation video player has the same hangups, but we definitely have some specifics to investigate - thanks!

**Comment by vade** [comment]
No worries. Glad I can be of some help. :+1:

**Comment by jvcleave** [comment]
Hey all,

In trying to see what the issue is I started this project
https://github.com/jvcleave/AvFoundationPlayer

It basically is able to
- read an HLS stream
- play audio
- get correct dimensions and current time of video playing
- apparently reading pixels in the sense that it reports that they have changed

I figure once this works the next step would be to integrate it into the ofAvFoundation player. I'm not really familiar enough with CoreVideo/CoreMedia to know what I need to do to get it into ofPixels/ofTexture

**Comment by jvcleave** [comment]
The above project now works with:
- looping
- corrected color
- pixel/texture access
- seeking (only forward testing)
- isFrameNew

It's currently fairly light at https://github.com/jvcleave/AvFoundationPlayer/commit/1a26b07082335949e17574faa7b8ea2d2638f248

I have to move on to finish a project not based on master but can look at it in a few weeks

**Comment by jeraman** [comment]
Would you have any news from this by any chance? 

Just as a reference, I'm struggling to get a m3u8 HLS inside oF:
https://forum.openframeworks.cc/t/hls-m3u8-http-live-streaming-video/11927

**Comment by i-n-g-o** [comment]
here a PR tackling this issue:
https://github.com/openframeworks/openFrameworks/pull/5530

should not have any side-effects...

**Comment by bakercp** [comment]
Closed with #5530 if not, please reopen.
