### ISSUE TITLE
Fedora compile error (misses cairo-features.h)

### ISSUE THREAD

**Issue by brianfay** [openframeworks/openFrameworks#1884]
The install_dependencies.sh script failed on me yesterday (I was trying to build openFrameworks in Fedora for the first time).

This doesn't seem to be a problem with the script itself; just a problem with the makefile include flags, which don't currently lead to the cairo development files.

To get this working, I simply added:

INCLUDES_FLAGS += -I /usr/include/cairo

after line 108 in the openFrameworksCompiled/project/linux64 makefile.

Others have suggested changing the cairo includes in libs/openFrameworks/graphics/ofCairoRenderer.h from "cairo-features.h" to "cairo/cairo-features.h"
I haven't tested that, but perhaps it could be a more elegant solution.

**Comment by highperformancecoder** [comment]
I got this error message when trying to compile the examples, and the reason turned out to be an uninstalled dependency, specifically assimp in my case.

The code in config.shared.mk should be made more robust so that it runs pkg-config --cflags on all pkg-config dependencies, not just fall over on the first one not found.
