### ISSUE TITLE
ofVec2f::angle() could intuitively mean two things

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#2060]
when i imagine the word "angle" as it relates to two ofVec2f objects, two different concepts come to mind:
1. the angle between two vectors: the angle from (1, 0) to (0, 1) is 90 degrees.
2. the angle from one point to another: the angle from (1, 1) to (2, 1) is 0 degrees (directly to the right).

the first one is the one implemented by angle(). sometimes i write code like this to execute the second one:

``` c++
ofVec2f a, b;
ofVec2f zero(1, 0); // "zero degrees" points to the right
float angle = zero.angle(b - a);
```

but it would be nice to think of a good name. maybe angleBetween() vs angleTo()?

**Comment by kylemcdonald** [comment]
as another point of reference, p5.js uses the word "heading" to describe the first meaning (angular distance from an axis) http://p5js.org/reference/#p5.Vector/heading

**Comment by corybarr** [comment]
What if ofPoint was no longer a typedef of ofVec3f and instead inherited from it? ofPoint::angleTo would then be overridden.

Reasoning: I don't think of a point as a vector, and I'm pretty picky about using ofPoint or ofVec[23]f for conceptual clarity. For example, a point doesn't have a magnitude, so when using an ofPoint I have no interest in the distance from the upper left corner unless it's a special case. It seems unintuitive for any method of ofPoint to use the point (0, 0, 0) in a calculation by default. It's essentially an arbitrary spot. 

When I use an ofVec[23]f, I think of the object as an ordered pair of points.

I added the code that would be ofPoint::angleTo in #3632.

**Comment by timmb** [comment]
I think having a bearing/heading/direction method makes sense as a measure of the counterclockwise angle between a vector and an axis (possibly with the x axis as a default argument). But I would argue it's still a quality of a vector, not a point. Points don't have direction. You only get a direction with a pair of points, and that's because you've made a vector by considering the difference between them.

How about having bearing() as a measure of angle against an axis, and bearingTo(ofVec2f) as what you describe:
 a.bearingTo(b) === (b-a).bearing().

I don't think it's a good idea to subclass ofVec2f and then use a different meaning of 'angle' in the subclass. The angle between two vectors is the difference between the directions they point, and any subclass of ofVec2f is still an instance of ofVec2f so should be consistent in language.

I would vote for adding to ofVec2f:
float bearing(ofVec2f axis=ofVec2f(1,0,0)) 

and if we go with making ofPoint a subclass of ofVec2f then adding to ofPoint:
float bearingTo(ofPoint otherPoint, ofVec2f axis=ofVec2f(1,0,0))

or otherwise just adding bearingTo to the ofVec2f class.

Tim

**Comment by corybarr** [comment]
Yeah, Tim, you've got a point. Subclassing ofVec3f is a bit of a cop out. If starting from scratch, I'd offer the idea that a point and a vector are two quite different things and should be different classes. Vectors have no fixed location, so the idea of distance between vectors seems undefined there. Similarly, the angle between two vectors and two points means a very different thing.

Functions can be added to ofVec[23]f, but I don't think they'll ever be intuitive. You just have to remember which function treats the data as a vector and which as a point, or just recognize that you're really only dealing with vectors, never with points. Subclassing and overriding functions where the meaning is very different is a compromise to not break a lot of code.

**Comment by tgfrerer** [comment]
How about we follow a more minimalist approach:

* Let's deprecate `ofPoint` in favour of `ofVec3f` (i was under the impression that this was the plan anyway?)
* Let's try not to extend the API by adding features that may introduce semantic ambiguity

I would advocate this for two reasons: 

+ if ever we want to switch over to a maintained, optimised, and widely-used maths library like the excellent `glm`, (as e.g. Cinder appears to be doing), a simple API footprint would help us a lot.

+ mathematically, there is no concept of an angle between two points, an angle can only be drawn between two vectors. A vec2f and a vec3f can be read as two different things: 

1. A *position vector* (="point") which means a vector starting at the origin and ending at a specific coordinate. These are used to represent positions in space.
2. A *direction vector*, which means the director has no set origin, but shows a direction in space, relative to the coordinate basis. These are used to represent e.g. forces.

The mathematical ambiguity between `position vector` and `direction vector`  disappears when using `vec4f`: 

Generally, a *position* vector has a `.w` value of `1.0`, whilst a *direction* vector has a `.w` value of `0.0`. This is why, for example, your normals need to have `.w` equal `0`, and your model coordinates need `.w` being `1` for lighting calculations.

---
That doesn't mean such helper methods aren't great! What would suggest is to write the function into your `ofApp.h` file. It's probably an one-liner. By sitting in a header file it will get automatically inlined, and will be even faster by a couple of CPU cycles as it would be as a core oF function.

**Comment by corybarr** [comment]
Deprecating ofPoint sounds like a good solution. That makes all the function names, return values, and semantics much clearer. Given that, it seems like bearingTo is very intuitive for what I originally used angleTo to calculate.

**Comment by ofZach** [comment]
back in the day, when all of this was in an addon, we used to have different point and vec objects, but it got a bit confusing which to use, and they got out of sync, which is why we moved to just having vecs but typedeffed to a point, but we also felt like ofVec3f is a sort of "beginning user" unfriendly syntax.  ofPoint is a **very heavily used data type** and there will be a ton of addons and code that will break if we deprecate / remove ofPoint.   I'm not adverse to using glm, but I do think keeping the ofPoint object around for a while makes sense, because it's such a heavy part of people's projects and code.

**Comment by tgfrerer** [comment]
By *deprecate* i mean we could add the `deprecated` pragma flag in 0.9 and remove in 0.10 or even later, meant as a signal / flag for addon implementers to watch out for a change with an upcoming release.

I wonder if reducing the choice/ambiguity could also be of benefit for beginners. To have only one data type to deal with could be nice: when I started using openFrameworks, i remember finding it really odd and distracting that some methods used `ofPoint`, some `ofVec3f`, and some returned `ofPoints` to things that required `ofVec3fs`. 

"How is that even possible? - do things get converted? - do i lose out on performance? - and why does the cat like walking over my keyboara;ljs ?", I wondered. 

It took me a while to understand what a `typedef` does in this case (and i still haven't fully understood the full gamut of what `typedef` is capable of). 

And although it was a nice detour into learning to know c++ better, it took me away from my initial goal of drawing some geometry.

**Comment by arturoc** [comment]
i'd say let's move to glm asap. then deprecate all the current vector math types. my idea is that we can have both for a while and add some kind of cast operators so old projects still work as they are but get tons of warnings :) it might be a little hard to get right but i think is doable and it's for sure worth moving to glm which has a syntax much similar to opengl's + should be much more optimized

**Comment by tgfrerer** [comment]
related #3477

**Comment by bakercp** [comment]
Closing this as it has largely been addressed by the integration of glm. Besides ofParameter*, ofPoint is not used in the core anymore.
