### ISSUE TITLE
ofxGui examples folder

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#2152]
Hey guys,
just noticed that the examples folder for ofxGui is within the "core" examples. I think that these should be in the addons examples folder, or rename ofxGui to ofGui to be consistent with the other examples.

What do you think?

**Comment by arturoc** [comment]
This is not the case anymore, at some point we decided to drop the difference between examples using addons or not and now the classification in categories has to do with the topic the example explains only so for example an example that explains a 3d concept will be in the 3d folder no matter if it uses an addon or not.

@jedahan I'll answer to your other question in the other PR you opened but i'm going to close this since it's been solved already
