### ISSUE TITLE
deprecate QuickTime classes, make AV Foundation default

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#2283]
These don't compile with newer OSX sdks without Carbon right?

**Comment by pizthewiz** [comment]
I am going to close this out now that video playback has transitioned to AV Foundation for the 0.9.0 release, while recognizing we still need a grabber implementation #3382 which will come in a later release.

**Comment by DyInCN** [comment]
We have a old project used the QuickTime.framework. In order to playback the video with special sound effects，we used the QTAudioContextInsertRegistryInfo API,and set the processDataCallback of the 
QTAudioContextInsertRegistryInfo object.The processDataCallback is said like this:

<typedef CALLBACK_API( OSStatus , AudioContextInsertProcessDataCallback )(void *inUserData, AudioUnitRenderActionFlags *ioRenderFlags, const AudioTimeStamp *inTimeStamp, UInt32 inNumberFrames, AudioBufferList *inInputData, AudioBufferList *outOutputData);>

When the program excutes this callback, we can get the inInputData and outOutputData. And then, 
there is a third C++ API,which need the parameters are from the inInputData and outOutputData.
This API can run audio effects for the playing data.

Now we need to abandon the QuickTime.framework, and replace it by AVFoundation.framework.
The third C++ API was made into a static library, and we can not modify the source code about it.
So there is a question is that how can I get the inInputData and outOutputData by AVFoundation?
If someone can help us, it is so much thanks。
