### ISSUE TITLE
devApps/projectGenerator isn't setting ADDON_CFLAGS

### ISSUE THREAD

**Issue by danomatika** [openframeworks/openFrameworks#2404]
I'm using the current develop to update the ofxPd examples. I created an addons_config.mk and specified the ADDON_CFLAGS needed by libpd. I generated 2 projects, 1 for OSX and 1 for iOS, and neither have the custom CFLAGS form the addons_config.mk set. This means they can't build and beginners will go running to the hills.

**Comment by avilleret** [comment]
I confirm this bug.
I'm trying to build against opencv 2.4.12 (I need OpenCL support which is not in the official ofxOpencv addon).
Then I tried to change `PROJECT_LDFLAGS` and `PROJECT_CFLAGS` in `config.make`, but this doesn't work.
I also tried to make an addon without code, but just a `addon_config.mk` that sets `ADDON_CFLAGS` and `ADDON_LDFLAGS` and that works.

so this issue seems to be resolved despite there is another one regarding  `PROJECT_LDFLAGS` and `PROJECT_CFLAGS` in `config.make`.

**Comment by bilderbuchi** [comment]
pinging @arturoc who is probably most knowledgeable about this part of the code.

**Comment by arturoc** [comment]
@avilleret do you mean that adding PROJECT_CFLAGS doesn't work with the project generator? in that case is correct. we just use that file for the makefle system. if the addon_config flags are working then this issue can be closed.

we can discuss if we want to turn config.make into something that all the project generation systems parse for flags to add to the project but that would be a separate issue

**Comment by avilleret** [comment]
thanks @arturoc I thought that `config.make` was used by Xcode generator too (the make suffixe should have warned me about that).
So this issue could be close I think.
