### ISSUE TITLE
ofxiOSKeyboard need fix y poision?

### ISSUE THREAD

**Issue by azuremous** [openframeworks/openFrameworks#2449]
ofxiOSKeyboard.mm

inside init() and updateOrientation() there is _y = _h need to fix to _y = _yOriginal ?

**Comment by micuat** [comment]
@julapy @ofTheo 
I guess this is still not fixed in the master branch and 0.9:
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxiOS/src/utils/ofxiOSKeyboard.mm#L230
https://github.com/openframeworks/openFrameworks/blob/stable/addons/ofxiOS/src/utils/ofxiOSKeyboard.mm#L227
They should be `_y = _yoriginal;` (I have only tested default orientation)

**Comment by ofTheo** [comment]
thanks @micuat will add for next release
