### ISSUE TITLE
Unify OS X and iOS AV Foundation Player

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3242]
With the merging of #3200 we now have an AVFoundation player/grabber for OS X.
We also have a separate one for iOS. 

I think the goal of AVFoundation was to have a shared API for video on both iOS and OS X, so it would be worth looking at consolidation. 

It could result in more consistent behavior and less bugs to fix. 

ping @julapy @admsyn @prisonerjohn @openframeworks/video @openframeworks/ios

**Comment by julapy** [comment]
hey, just wanted to give this a little push since OF activity is ramping up for 0.9.0
have @prisonerjohn @openframeworks/video folks had a chance to look at this yet?

for now it might be an idea to replace the current iOS video player with ofxAVFoundationVideoPlayer (https://github.com/julapy/ofxAVFoundationVideoPlayer). ive been concentrating my dev efforts on the new ofxAVFoundationVideoPlayer and leaving the OF iOS player stagnant... so to take advantage of the new features and bug fixes, its probably worth doing the swap now for 0.9.0. keep in mind that ofxAVFoundationVideoPlayer stems from the OF iOS player so its essentially the same, but now also works on OSX.

@ofTheo @admsyn - you guys ok with this?

**Comment by ofTheo** [comment]
@julapy I am super happy to do this. 
We're actually talking about doing a bunch of video stuff now anyway with #3543 so I think its the perfect time. 

Please do a PR for it! It will be great to have a single video player for both. 
Not sure if #3543 should be done first @pizthewiz @bakercp ? thoughts?

**Comment by prisonerjohn** [comment]
Sorry I haven't had a chance to dig through yet, I only took a quick glance. I agree that a unified video player for iOS and OS X is def the way to go! I could test it in my recent and current projects if it gets pulled in the main repo.

**Comment by admsyn** [comment]
:+1:

**Comment by julapy** [comment]
spent a couple days merging the OSX and iOS video player code (PR is here - #3590)

its working well across the two platforms in pretty much the same way.

one difference worth noting is that the current OSX video player in master uses the AVPlayerItemVideoOutput class which is only available in iOS6+ and currently ofxiOS supports iOS5 and up. so in this version, AVAssetReader is used for reading video sample data instead AVPlayerItemVideoOutput. this is ok i think, as they both do the same thing and when we bump up the minimum iOS version to iOS6+, then we can swap out AVAssetReader for AVPlayerItemVideoOutput.

the new version has a couple new features on top of the current implementation,
````
- video player can render to a ofTexture or display natively in a UIView or NSView.
- not only video sample data can be retrieved, but also audio sample data which can be used further down the chain for FFT analysis or mixing with other audio channels. as far as im aware, this is only possible with AVAssetReader and not AVPlayerItemVideoOutput.
````

@prisonerjohn @ofTheo @admsyn, let me know what you guys think.

**Comment by pizthewiz** [comment]
Should be good to close this yeah?

**Comment by kylemcdonald** [comment]
yes!
