### ISSUE TITLE
Emscripten tutorial

### ISSUE THREAD

**Issue by minusplusminus** [openframeworks/openFrameworks#3426]
Hi,

I'm trying to figure out how to realize an Emscripten build. There's not much documentation about this option.

The only thing I could find is: 
https://github.com/openframeworks/openFrameworks/pull/2992

**Comment by s373** [comment]
would really really like to count on this soon for a project, almost there, so i share what i've accomplished and some errors, hoping a fellow programmer can assist!

the process of setup is straightforward:

1. install portable sdk ( http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#all-os-installation-instructions-portable-sdk )
2. calling on the project folder <pre> emmake make </pre> starts the compiling process, and all looks like it'll work when errors are gone.

there are a couple of errors i remember fixing like extraneous parentheses, and this one,
<pre>
../../../libs/openFrameworks/utils/ofURLFileLoader.cpp:247:11: error: allocating an
      object of abstract class type 'ofxEmscriptenURLFileLoader'
:impl(new ofxEmscriptenURLFileLoader){}
          ^
../../../libs/openFrameworks/types/ofBaseTypes.h:669:25: note: unimplemented pure
      virtual method 'handleRequest' in 'ofxEmscriptenURLFileLoader'
        virtual ofHttpResponse handleRequest(ofHttpRequest request) = 0;
                               ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
make[2]: *** [../../../libs/openFrameworksCompiled/lib/emscripten/obj/Release/libs/openFrameworks/utils/ofURLFileLoader.o] Error 1
make[1]: *** [Release] Error 2
make: *** [Release] Error 2
  </pre>

which i fixed by implementing an empty <pre> ofHttpResponse handleRequest(ofHttpRequest request); </pre> on ofxEmscriptenURLFileLoader.h

then another error:
<pre>../../../libs/openFrameworks/video/ofDirectShowPlayer.cpp:17:10: fatal error: 
      'DShow.h' file not found
#include <DShow.h>
         ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting </pre>

somehow emscripten compilation is including ofDirectShowPlayer.h, looks like OF_VIDEO_PLAYER_DIRECTSHOW is defined when compiler is at ofVideoPlayer.h, now i am a bit lost as to where to undefine OF_VIDEO_PLAYER_DIRECTSHOW and define the correct OF_VIDEO_PLAYER_EMSCRIPTEN

then errors just cascade if i remove OF_VIDEO_PLAYER_DIRECTSHOW completely from source, resulting in 
<pre>
../../../libs/openFrameworks/video/ofVideoGrabber.cpp:43:51: error: allocating an
      object of abstract class type 'ofxEmscriptenVideoGrabber'
                setGrabber( shared_ptr<OF_VID_GRABBER_TYPE>(new OF_VID_GRAB...
                                                                ^
../../../libs/openFrameworks/video/ofVideoGrabber.h:42:30: note: expanded from
      macro 'OF_VID_GRABBER_TYPE'
        #define OF_VID_GRABBER_TYPE ofxEmscriptenVideoGrabber
                                    ^
../../../libs/openFrameworks/types/ofBaseTypes.h:388:15: note: unimplemented pure
      virtual method 'setup' in 'ofxEmscriptenVideoGrabber'
        virtual bool setup(int w, int h) = 0;
                     ^
../../../libs/openFrameworks/video/ofVideoGrabber.cpp:60:51: error: allocating an
      object of abstract class type 'ofxEmscriptenVideoGrabber'
                setGrabber( shared_ptr<OF_VID_GRABBER_TYPE>(new OF_VID_GRAB...
                                                                ^
../../../libs/openFrameworks/video/ofVideoGrabber.h:42:30: note: expanded from
      macro 'OF_VID_GRABBER_TYPE'
        #define OF_VID_GRABBER_TYPE ofxEmscriptenVideoGrabber
                                    ^
../../../libs/openFrameworks/video/ofVideoGrabber.cpp:133:60: error: allocating an
      object of abstract class type 'ofxEmscriptenVideoGrabber'
  ...mutThis->setGrabber( shared_ptr<OF_VID_GRABBER_TYPE>(new OF_VID_GRABBER_TYP...
                                                              ^
../../../libs/openFrameworks/video/ofVideoGrabber.h:42:30: note: expanded from
      macro 'OF_VID_GRABBER_TYPE'
        #define OF_VID_GRABBER_TYPE ofxEmscriptenVideoGrabber
                                    ^
3 errors generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
make[2]: *** [../../../libs/openFrameworksCompiled/lib/emscripten/obj/Release/libs/openFrameworks/video/ofVideoGrabber.o] Error 1
make[1]: *** [Release] Error 2
make: *** [Release] Error 2

</pre>

any suggestions/ideas? using of-git..

**Comment by s373** [comment]
prevent directshow error above, add this to emscripten makefile
<pre>
PLATFORM_CORE_EXCLUSIONS += $(OF_LIBS_PATH)/openFrameworks/video/ofDirectShowPlayer.cpp
</pre>

then must define a method in ofEmscriptenVideoPlayer.h not yet implemented
<pre>bool load(string name){
		loadMovie(name);
	}
</pre>

and compilation almost succeeds! i was trying with ofxBullet, and i get errors, probably related to non openGl immediate mode allowance inside ofxEmscripten:
<pre>
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:186:2: error: use of
      undeclared identifier 'glBegin'
        glBegin(GL_LINES);
        ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:187:3: error: use of
      undeclared identifier 'glVertex3f'
                glVertex3f(pa.x, pa.y, pa.z);
                ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:188:3: error: use of
      undeclared identifier 'glVertex3f'
                glVertex3f(pb.x, pb.y, pb.z);
                ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:189:2: error: use of
      undeclared identifier 'glEnd'
        glEnd();
        ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:199:2: error: use of
      undeclared identifier 'glBegin'
        glBegin(GL_LINES);
        ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:200:3: error: use of
      undeclared identifier 'glVertex3f'
                glVertex3f(pa.x, pa.y, pa.z);
                ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:201:3: error: use of
      undeclared identifier 'glVertex3f'
                glVertex3f(pb.x, pb.y, pb.z);
                ^
../../../addons/ofxBullet/src/joints/ofxBulletJoint.cpp:202:2: error: use of
      undeclared identifier 'glEnd'
        glEnd();
        ^

</pre>


then i tried with a simpler test example HelloWorld & 3dPrimitives and console is hanging on llvm-nm..

no html yet generated... console hangs forever on this ...

<pre>
7 warnings generated.
Linking bin/HelloWorld.html for emscripten
/Users/as/Downloads/emsdk_portable/emscripten/1.29.0/em++ -o bin/HelloWorld.html -O3 -s OUTLINING_LIMIT=100000 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s TOTAL_MEMORY=134217728 --memory-init-file 1  obj/emscripten/Release/src/main.o obj/emscripten/Release/src/testApp.o
 ../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxAppEmscriptenWindow.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundPlayer.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundStream.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenURLFileLoader.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoGrabber.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoPlayer.o 
../../../libs/openFrameworksCompiled/lib/emscripten/libopenFrameworks.bc   -Wl,--as-needed -Wl,--gc-sections --preload-file bin/data@data --js-library 
../../../addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js --js-library 
../../../addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js 
../../../libs/FreeImage/lib/emscripten/libfreeimage.a ../../../libs/tess2/lib/emscripten/libtess2.a    
../../../libs/poco/lib/emscripten/libPocoUtil.so ../../../libs/poco/lib/emscripten/libPocoXML.so 
../../../libs/poco/lib/emscripten/libPocoFoundation.so ../../../libs/tess2/lib/emscripten/libtess2.so 
../../../libs/freetype/lib/emscripten/libfreetype.bc  


</pre>


<pre>
1 warning generated.
Linking bin/3dPrimitives.html for emscripten
/Users/as/Downloads/emsdk_portable/emscripten/1.29.0/em++ -o bin/3dPrimitives.html -O3 -s OUTLINING_LIMIT=100000 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s TOTAL_MEMORY=134217728 --memory-init-file 1  obj/emscripten/Release/src/main.o obj/emscripten/Release/src/ofApp.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxAppEmscriptenWindow.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundPlayer.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenSoundStream.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenURLFileLoader.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoGrabber.o 
../../../addons/obj/emscripten/Release/ofxEmscripten/src/ofxEmscriptenVideoPlayer.o 
../../../libs/openFrameworksCompiled/lib/emscripten/libopenFrameworks.bc   -Wl,--as-needed -Wl,--gc-sections --preload-file bin/data@data --js-library 
../../../addons/ofxEmscripten/libs/html5video/lib/emscripten/library_html5video.js --js-library 
../../../addons/ofxEmscripten/libs/html5audio/lib/emscripten/library_html5audio.js 
../../../libs/FreeImage/lib/emscripten/libfreeimage.a ../../../libs/tess2/lib/emscripten/libtess2.a    
../../../libs/poco/lib/emscripten/libPocoUtil.so ../../../libs/poco/lib/emscripten/libPocoXML.so 
../../../libs/poco/lib/emscripten/libPocoFoundation.so ../../../libs/tess2/lib/emscripten/libtess2.so 
../../../libs/freetype/lib/emscripten/libfreetype.bc  

</pre>

any ideas? now compilation apparently succeeds, but hangs forever on .html generation... left it for 10+minutes hanging on libfreetype and nothing happens, no html generated on /bin
using emscripten 1.29.0, of git on osx

thanks

**Comment by s373** [comment]
![screen shot 2015-02-11 at 13 10 11](https://cloud.githubusercontent.com/assets/728199/6147438/6f682170-b1ef-11e4-835c-d963f5e52ad4.png)

**Comment by arturoc** [comment]
there's been some major refactoring when introducing multiwindow support that has broken emscripten. i'll fix it when i have a moment but there's probably much more than what you've found since at least the window class needs some changes to work with the newest version

the emscripten compiler can be super slow too, compiling in debug with `make Debug` makes it slightly faster

**Comment by s373** [comment]
<pre>emmake make Debug or emmake make</pre> on my system which now compiles ofxemscripten ok, produce exactly the same outcome i mentioned earlier: compile ok, but llvm-nm never finishes and no binary html generated. (10+ hours of waiting for it to finish)

could you paste the terminal output of a working project you have there? better yet, is there any of-branch somewhere where emscripten is compiling and generating .html? just would like to test it out to see if it fits the project i am making, and if i could heavily customise the html. 

btw, your of-emscripten files look great tease! http://arturocastro.net/files/of-emscripten/

**Comment by arturoc** [comment]
no there's no branch, you could try to go back to some specfic commit but not sure either where it was working. the original branch were i did the port is not compatible anymore with the current emscripten.

but yes you can change the html as much as you want, even communicate from js/html to c++ and viceversa

**Comment by bakercp** [comment]
There is now a full setup tutorial here http://openframeworks.cc/setup/emscripten/

If it still doesn't meet your needs, please reopen this issue or submit a pull request with updates to ofSite. Thanks!
