### ISSUE TITLE
ofSystemLoadDialog hangs app on OS X

### ISSUE THREAD

**Issue by pusnik** [openframeworks/openFrameworks#3456]
Draw and update methods get called but nothing on screen is updated. Issue is reproduced on 10.10 as on 10.9. ofSystemSaveDialog works normal. Using OF 0.8.4 stable version. 

Also to note is that ofSystemSaveDialog works without any problem on both OS X versions.

Edit: It works without problem on (all using the same bin) :
               - macbook pro retina 15" late 2013 with Nvidia graphics (OS X 10.10)
               - Mac mini late 2012, with Intel graphics (OS X 10.8.5)
        Does not work on:
              - Macbook pro retina 13" late 2013 with Intel Iris, (OS X 10.10)
              - Macbook pro retina 15" 2012, with nvidia (OS X 10.9)

**Comment by dimitre** [comment]
I think this issue is still important, so one can input to the software without freezing.
but with a different function, maybe using std::function to return the value
or something similar to ofLoadURLAsync function

something like this can solve the fact the window freezes on top, but doesn't solve the value return
```obj-c
		__block std::string textOut = "";

		[alert beginSheetModalForWindow:primaryWindow completionHandler:^(NSModalResponse result) {
			if (result == NSAlertFirstButtonReturn) {
				textOut = [[label stringValue] UTF8String];
			} else if (result == NSAlertSecondButtonReturn) {
				textOut = "";
			}
		}];
```
