### ISSUE TITLE
Document 0.9.0 Platform Support Coverage

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3506]
Please edit this list directly if you have more information :)

OS X
- ~~10.6~~ _Removed_
  - _No support for libc++ / c++11, etc_
- 10.7 - 10.10 (_FAT Bundle_)
  - Note: QTKitVideo pipeline will be deprecated, but essential for 10.7 support.
  - i386 (with libc++)
  - x86_64 (with libc++)

iOS (using 10.9+ OSX)
- ~~iOS 4~~ _Removed_
  - _see #2568 for more discussion_
- iOS 5.1 - 9.1 (_FAT Bundle_ with libc++ for all archs)
  - armv7
  - ~~armv7s~~ _Removed_
    - _potential performance gains not worth the binary size increase, see #3423 for more discussion_
  - arm64
  - i386 
  - x86_64

Android
- OS?
  - ~~armv5~~ _Removed_
    - _No new hardware for this._ 
  - armeabi-v7a
  - i386

Windows
- Win7 - Win8
  - Visual Studio 2012
    -  i386
  - MinGW / Codeblocks 12.11
    -  i386

Linux
  - i386
  - x86_64
  - armv6l
  - armv7l

Emscripten
  - VM

**Comment by pizthewiz** [comment]
It might also be useful to document our tooling support as well.

On the iOS side, `arm64` was not supported until Xcode 5 and Xcode 5 requires OS X 10.8 to run, so should 10.8 become our minimum for OS X, that would be a natural fit.

(Feel free to remove this comment)

**Comment by danoli3** [comment]
For iOS Apple are really stepping up that you have to be at the latest in order to submit to the AppStore.
So if a developer wants to use oF with iOS, they are going to have to be at the latest Xcode and SDK in order to do that.

However there are probably a lot of developers who just want to make OS X apps... and if they are on 10.8, shouldn't stop them unless they want to make iOS apps specifically, then it's apple stopping them not us.

**Comment by notjosh** [comment]
fwiw, Apple make it fairly easy/cheap (read: free) to be on the latest OS/dev tools, and they run on hardware from as far back as 2007.

As [64-bit is required for submission now](http://9to5mac.com/2014/12/17/apple-reminds-developers-about-64-bit-ios-app-store-requirement-app-updates-now-must-also-comply-by-june/), it'd seem wise to bump the minimum to what'll cause the fewest unexpected issues throughout dev/submission imo.

**Comment by bilderbuchi** [comment]
where should this documentation end up for the release? is the list current?

**Comment by bilderbuchi** [comment]
@bakercp @kylemcdonald @pizthewiz what are we gonna do with the content in this issue?

**Comment by kylemcdonald** [comment]
@bilderbuchi in my opinion #4178 is headed in the right direction.

another solution could be to include this information on the "downloads" page. but it's nice to have it distributed with the actual download itself, because it could change on github master even before the downloads page is updated.

**Comment by bilderbuchi** [comment]
closed by #4528
