### ISSUE TITLE
Support OpenGL 3.2+ on GLUT

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3576]
While reverting to GLUT recently due to the GLFW Linux bug which gives me a blank screen on startup (is there an issue for this? It was noted in the forums but I couldn't find it here), I discovered there's no support for the ofGLProgrammableRenderer() in GLUT and therefore OpenGL 3.2 support.

After searching a bit, I discovered I could switch this on using the following lines:
```
glutInitContextVersion(3,2);
glutInitContextProfile(GLUT_CORE_PROFILE);
```

However this didn't compile until I replaced  
``` 
#include <GL/glut.h>
```  
with 
```
#include <freeglut.h>
```
 in ofAppGlutWindow.cpp

Any reason this can't be included in much the same way as GLFW?
Anyone know why we are using 
```
<GL/glut.h>
``` 
instead of 
```
<freeglut.h>
``` 
under Linux (and what's the difference anyway?)

Summoning @arturoc and @tgfrerer who I think might have something to say on the topic :)

**Comment by arturoc** [comment]
all platforms except for linux use glut instead of freeglut. while freeglut is perfectly compatible with the standard glut it adds some extensions that are not present in other platforms. we can add ifdefs to the glut class for linux but not sure is worth mantaining 2 classes with mostly the same functionality. if you want to add it though and send a PR go for it.

also i reported the linux bug in the GLFW and ubuntu issue trackes and it's fixed now (yesterday) but it hasn't arrived yet to ubuntu 14.10

**Comment by pierrep** [comment]
Hmmm, yeah I see. One of the things I like about OF is that it works mostly the same across platforms, so maybe adding extra linux functionality kinda breaks that, even if it is for the better.

Maybe a better option would be for me to have this extra functionality as an addon (ofxFreeGlutAppWindow or something)

Thanks for following up the GLFW stuff, that's been a real PITA!
