### ISSUE TITLE
bug in ofSoundObject

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#3586]
this in line 130:

```cpp
std::shared_ptr<ofBaseSoundOutput> ofSoundMixer::getChannelSource(int channelNumber) {
	if (channelNumber < channels.size()) {
        return std::shared_ptr<ofBaseSoundOutput>(channels[channelNumber]);
	}else{
		return std::shared_ptr<ofBaseSoundOutput>();
	}
}
```

is wrong, it's creating a shared_ptr from an already existing pointer which will destroy the original once it goes out of scope, the correct thing to do seems to store shared_ptr in the vector.

ping @bakercp since it seems he added this code

**Comment by bakercp** [comment]
I think I got credit for this one because I converted all of the `ofPtr` -> `std::shared_ptr`.  I do not condone the mixing of shared and raw pointers :) -- see my original comments / suggestions on the PR here https://github.com/openframeworks/openFrameworks/pull/3369.

Anyway, if I'm still allowed to register my opinion -- back in the PR discussion I think I proposed keeping a vector of std::shared_ptr or using std::weak_ptr in this case.  It's a little tricky because it's a pointer to a base class ... anyway, not sure what the best solution is, but this is definitely a big bug.

**Comment by arturoc** [comment]
i agree the best would be to have a vector of weak pointers. the main problem is that it would force people to use shared pointers which can be intimidating for beginners. 

who did this then? @roymacdonald @admsyn @mazbox

**Comment by admsyn** [comment]
That was me, making a mistake when shuffling some of the code around. [Roy's original intent was for that to be a dereference of a raw pointer](https://github.com/admsyn/openFrameworks/commit/801c237ddb0d0be0d274fbd5bda107bed7467543#diff-6663da56fce847e65be8c23d36ee1a17L14). 

I think what happened was that I intended to migrate from all raw pointers to all ofPtr and missed that `channels` was (and still is) a `vector<ofSoundObject *>` instead of shared pointers.

I think making this making this back into a dereference to a ofBaseSoundOutput& is the way to go?

**Comment by arturoc** [comment]
the main problem with that is the user has to keep references to the original objects around until all the objects that hold a reference to them are destroyed, control the order of destruction... which can be really messy.

an option would be to implement some kind of internal smart pointer in the objects themselves the way ofParameter does it for example. since this is an API to be used by addon developers... it might be tricky to enforce that through some kind of API.

not sure what's the best option really but i'd say the API is not very mature, perhaps we should remove this class and leave it for the next version as we already did with ofSoundFile and ofBasicSoundPlayer. Having ofSoundBuffer and the callbacks using it is already a very good change in the sound API that will make sound development easier

**Comment by admsyn** [comment]
Actually, looking a bit closer at this I think I see where some confusion came from. The function's written to return a reference, but internally stores its channel sources as pointers. In the case that a channel doesn't have an associated source, [it didn't have a reference to return](https://github.com/admsyn/openFrameworks/blob/3c06b38ab18b80e9ef29edc0a935503ec665f8c2/libs/openFrameworks/sound/ofSoundMixer.cpp#L12-L18).

Moving this to shared pointers fixes the semantic issue (since you can return NULL) but puts shared pointers in the public API.

**Comment by roymacdonald** [comment]
HI, just a quick answer.
The idea would be to be able to return a NULL as it will mean that nothing
is connected to that channel. I have no idea on how the ofParameter deals
with pointers, yet implementing something similar might be the way to go.
I understand the problem with exposing pointers throught the API, but in
this case the references might be a bit messy.
I'll go around this later as I have to rush out right now.
All the best!

*Roy Macdonald*
+569 8248 8478

**Comment by kylemcdonald** [comment]
i noticed something else related to this code... i was in some weird intermediate land of 64-bit, libstdc++, libc++, c++11, c++98, 10.7 deployment... everything was mixed up... and i had to make these changes to get my code to compile:

https://github.com/kylemcdonald/openFrameworks/commit/67f621dded606cfcabac840e2391115aad935f7e

i think the `std::` prefix to the `shared_ptr` in the code above might not be necessary at the moment, and maybe leftover from when we were importing `shared_ptr` into `std` from somewhere else? i don't totally understand what's going on, but i'm sure this will get sorted out as we start changing the OS X project settings.

**Comment by bilderbuchi** [comment]
I guess a tough question is if those changes will break in other configurations than yours, kyle, as they are stirring the pot quite much.

**Comment by kylemcdonald** [comment]
i think the `shared_ptr` might break in other legitimate situations.

the other things are probably just incomplete `#if`s where we haven't delineated the exact boundary between the two cases clearly enough. i think we will discover the exact nature of that boundary as we prepare an OS X release that is both 32-bit and 64-bit compatible.
