### ISSUE TITLE
ofMesh::draw() slow vs ofGetGLRenderer()->draw(ofMesh) in fixed pipeline

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#3667]
```
ofMesh mesh;

mesh.draw();
//vs
ofGetGLRenderer()->draw(mesh, false, true, false);
```
When using the fixed pipeline renderer, those two behave very differently when drawing lots of meshes. The ofMesh::draw() method is waaay slower, around ~10x slower when drawing 1000 ofMeshes. After some digging, came to the conclusion that this happens  because each ofMesh::draw() does a glPushAttrib() and a glPopAttrib() before drawing the mesh.

This was noticed on Mac OS X 10.9.

Arturo thinks this might not be necessary. See here: http://forum.openframeworks.cc/t/ofmesh-draw-slow-vs-ofgetglrenderer-draw-ofmesh/18593.

**Comment by arturoc** [comment]
yeah the programmable renderer just defaults to whatever the fill state is. we could change the fixed pipeline renderer to use that too. i think before we were more careful with trying to maintain the state if someone did direct gl calls in combination with OF calls but i it's a huge performance hit to push / pop or get / set attributes this way and we've recently done other changes in that direction (defaulting to whatever OF's state is instead of querying the GL state) as we did with the viewport rencetly.

i guess the discussion should be, do we want to do this only in the programmable renderer and keep the fixed one querying the GL state or should change the fixed one too?

**Comment by tgfrerer** [comment]
I would consider `ofMesh.draw()` a convenience method, which means i would advocate for it to aim to be designed to be easy to use - but internally careful to maintain state, and not aggressively optimised.

We're not currently tracking the polygonmode internally in the renderers and setting the polygonmode based on the current fill style in the programmable renderer is a necessary evil, following the principle of least surprise. We have to do this there because `push/popAttrib` have been deprecated in modern OpenGL for performance reasons.

If you want to draw 1000s of meshes and get good performance, it's probably a good idea to use `ofVboMesh`, where you have much more options to optimise, and which will be even faster than anything achievable with ofMesh, because it optimises how the data is kept on the GPU.

When you render an ofMesh, for every draw() all the vertex data has to be sent to the GPU individually. When you draw an ofVbo or an ofVboMesh, it's only sending data to the GPU if the mesh has been changed. The next time the ofVboMesh is drawn unchanged, its just telling the GPU where to find the data.

In my mind, an ofMesh is a data container with some convenience drawing functions. In practice, i only use it to load geometry, or to draw debug data. Once i have loaded the geometry using an ofMesh, I initialise an ofVbo or an ofVboMesh with it, and draw using these optimised objects =)

**Comment by arturoc** [comment]
even with that, in this specific case where he's drawing 1000s of meshes, creating 1000s of vbos might not be the best idea and creating 1 vbo and updating it several times per frame can be way slower than using ofMesh if it's not done properly, the fastest would be to create 1 vbo with all the data + a texture atlas but that's probably overkill for some cases.

i think that OF fill mode == gl polygon mode is a good assumption and shouldn't be problematic. if someone calls glPolygonMode manually and then draw a mesh which returns that value to whatever the fill state was is preferable to doing a ton of push/pop attributes by default. in the programmable renderer we could be doing get/set instead of push/pop but we chose not to and instead default to the current fill state which hasn't been any problem.

**Comment by tgfrerer** [comment]
yeah, it's probably better to optimise the data (i.e. the amounts of meshes and draw calls) before everything else. 

i like the refactor! and strange that we never noticed the `GL_FILL` swap bug in `drawInstanced`

**Comment by armadillu** [comment]
In my case each mesh is changing every frame, so for a quick 1-day prototype it seemed the best option. I believe ofVBOmesh would only add more overhead when the meshes are updated all the time. 

Basically I needed 1000 different high res textures/photos with a custom crop on screen (i.e. not square), and I need to be able to zoom into them too. So unless I build a gigantic texture atlas to be able to Texture them all in one texture->bind() "go", (and it would still be too low res bc of the max texture size limit), i need individual meshes so that i can bind each texture before I draw the mesh.

I guess I could try multi-texturing and a shader, but its beyond the scope of my prototype.

**Comment by arturoc** [comment]
actually creating 1 ofVboMesh and updating it by calling set() so the previous buffer is invalidated, is pretty much what's going on internally in OF. but yes i think removing the push/pop and defaulting to the fill state is a good balance of performance/least surprise in this case.

> i like the refactor! and strange that we never noticed the GL_FILL swap bug in drawInstanced

yeah right, i was having problems with instanced drawing under the programmable renderer a while ago but not sure it had anything with this
