### ISSUE TITLE
May be able to remove 3rd party repo for RPI/arm6

### ISSUE THREAD

**Issue by jvcleave** [openframeworks/openFrameworks#3669]
I *think* that we may be able to remove the vontaene.de repo as from the below it appears that Raspbian has adopted libgstreamer1.0-dev into the main repo 

It seems vontaene has a newer version tho - @arturoc you are more familiar with gstreamer - any watchouts?

```
pi@jvcrpi ~ $ apt-cache policy libgstreamer1.0-dev
libgstreamer1.0-dev:
  Installed: 1.2.4-1.1
  Candidate: 1.2.4-1.1
  Version table:
 *** 1.2.4-1.1 0
        500 http://vontaene.de/raspbian-updates/ ./main armhf Packages
        100 /var/lib/dpkg/status
     1.2.0-1rpi3 0
        500 http://archive.raspberrypi.org/debian/ wheezy/main armhf Packages
```

**Comment by arturoc** [comment]
voataene.de had the omx module for gstreamer. without that raspbian didn't had accelerated video decoding under gstreamer making it super slow

**Comment by jvcleave** [comment]
it looks like both have it (but vontaene is newer)

```
pi@jvcrpi ~ $ apt-cache policy gstreamer1.0-omx
gstreamer1.0-omx:
  Installed: 1.2.0-1
  Candidate: 1.2.0-1
  Version table:
 *** 1.2.0-1 0
        500 http://vontaene.de/raspbian-updates/ ./main armhf Packages
        100 /var/lib/dpkg/status
     1.0.0.1-0+rpi12rpi1 0
        500 http://archive.raspberrypi.org/debian/ wheezy/main armhf Packages
```

**Comment by bilderbuchi** [comment]
cf. #3688

**Comment by bakercp** [comment]
From vontaene (aka Defiant) her/himself:

> Please no longer use my repository since nowadays raspbian already contains all gstreamer/omx packages.

http://www.raspberrypi.org/forums/viewtopic.php?f=28&t=87139&p=696727&hilit=vontaene#p696727

**Comment by bakercp** [comment]
So theoretically, we should just be able to use the plain debian `install_dependencies.sh`.  That's what we are doing in the [Raspberry Pi 2 Setup Guide](http://forum.openframeworks.cc/t/raspberry-pi-2-setup-guide/18690) at least and it seems to be working (I tested it with video grabber, etc).

**Comment by arturoc** [comment]
mmh, not sure but i'd say then it won't install the omx plugin and do the decoding in the cpu which is much slower.

at least we should add `apt-get install gstreamer1.0-omx`

**Comment by bakercp** [comment]
@arturoc Ahh yes, that makes sense - how should we test this?

**Comment by arturoc** [comment]
`gst-inspect-1.0 | grep omx` should output something if the package is installed but i guess it's not since it's a specific package `gstreamer1.0-omx` that is not installed by the default linux script

**Comment by nselikoff** [comment]
FYI:

I just ran through the openFrameworks setup on a Raspberry Pi Model B with a fresh install of Raspbian, and oF 0.8.4 from the download page (not a git checkout) and got stuck at running the install_dependencies script due to two issues.

1. The missing PGP key for vontaene.de. Indeed, gstreamer is already installed on the latest Raspbian. I commented out the first section of `install_dependencies.sh` that inserts the gstreamer repository.
2. A change in the GTK package name, which I see was fixed in 8292bdd8cbae888b9194665520faa2fb60d206b5 but isn't in 0.8.4.

After those changes, install_dependencies ran without error, and I complied oF without error, and haven't run into any issues yet.

**Comment by Daandelange** [comment]
Hello,
I'm also figuring out how to get OF 9.0 (or rather the latest 0.8.4 master) to work on my Rpi1 B+.  
Here's a little sum-up I gathered from several posts.

- Comment out line 4 in `/openFrameWorks/scripts/linux/debian_armv6l/install_dependencies.sh` (thus using gstreamer 1.0). Then run `./install_dependencies.sh`.
[Line 4]  `echo "deb http://vontaene.de/raspbian-updates/ . main" > /etc/apt/sources.list.d/gstreamer.list`  


- Update to g++4.8:
 `sudo apt-get install g++-4.8`
`cd /usr/bin`
`sudo rm g++`
`sudo ln -s g++-4.8 g++`  
- And update your compiler flags to use c++11:  
`nano openFrameWorks/libs/openFrameworksCompiled/project/makefileCommon/config.linux.common.mk`  
__Find__ `PLATFORM_CFLAGS = -Wall -std=c++0x` __replace with__ `PLATFORM_CFLAGS = -Wall -std=c++11`

Now your OF main project should compile.
I guess that all these changes are temporary until OF 9.0 gets released.

_Note: from here on, there are no make files at all for any OF project so impossible to build the PG or any example makefile._  

I'm currently unable to compile any example project, I get linker errors with Poco (ThreadImpl, BugCheck, etc.) Any ideas ?

**Comment by bakercp** [comment]
The linker errors are there because the static poco libs need to be recompiled.  I have done this but won't have access to my machine for a week. You can reckmplie the yourself using the apothecary script in master.

**Comment by Daandelange** [comment]
Thanks, that worked perfectly, OF runs fine now on my Rpi! :+1: 
That took a look time to compile! ^_^
`cd openFrameworks/scripts/apothecary`  
`sudo ./apothecary update poco`

_Shall I push something or are you on it ?_

**Comment by bakercp** [comment]
If you've got working static libs go ahead and PR!

**Comment by Daandelange** [comment]
I commited the changes but did not make a branch for it and now i'm kinda stuck doing a separate PR...

The compiled libs are in my master branch in https://github.com/Daandelange/openFrameworks/commit/09bac515ae1971fda69cb6f74772abb6c4cadca0 which has already an active PR (https://github.com/openframeworks/openFrameworks/pull/3807)...
Somehow, the commit was even added to that PR...

How to handle this situation on Git ?

**Comment by bilderbuchi** [comment]
> Somehow, the commit was even added to that PR...

this happened because you didn't create a separate branch for your other PR, so that PR contains all the commits you have added to your master branch (and all you will add in the future) which are not in our master branch yet (see the line "Daandelange wants to merge 5 commits into openframeworks:master from Daandelange:master" in the PR description.)

To avoid this, you should follow the [guidelines](https://github.com/openframeworks/openFrameworks/blob/master/CONTRIBUTING.md#organising-your-code) that were presented to you when you create a PR or issue, then this issue can't happen. :-)

To work around this, the simplest way would be to get @bakercp and @ofZach to check if all the commits in #3807 are fine to merge, and merge that PR asap.

If that's not the case, the git way to fix this would be to [git cherry pick](http://git-scm.com/docs/git-cherry-pick) your commit 09bac51 over into a new branch, and delete it from your master (uing [git reset --hard](http://stackoverflow.com/a/9530204/599884). 
Then you have to push --force your updated master (cause you changed history) to your origin, and can push the newly created branch with the compiled libs, and PR that in a separate PR. :-)

**Comment by Daandelange** [comment]
Ok, thanks you and sorry for the mess. I'm up to date with the guidelines now :)

I'll wait for Christopher's or Zach's answer and hope it can merge. :angel: 
_(I can also make additional changes to validate it)_

**Comment by bilderbuchi** [comment]
ok, your compiled libs have been merged. does that mean this issue can be closed? @Daandelange @bakercp

**Comment by arturoc** [comment]
the original issue refers to something else. we need to check if raspbian already brings the latest gstreamer omx module

**Comment by Daandelange** [comment]
I downloaded a fresh Raspbian installation 2 weeks ago and I don't remember installing omxplayer.
This information may help:
`Debian GNU/Linux 7.8 (wheezy)`
`uname -a: Linux 3.18.14+ #792 armv6l`
```
dpkg -l | grep gstreamer1.0-omx
||/ Name                                  Version                                Architecture Description
+++-=====================================-======================================-============-===============================================================================
ii  gstreamer1.0-omx                      1.2.0-1                                armhf        OpenMAX IL GStreamer wrapper
```

Line 4 in `/openFrameWorks/scripts/linux/debian_armv6l/install_dependencies.sh` still needs to be removed in order to run it.
And gcc++ 4.8 (C++11) needs to be installed but is indeed off topic here. [see https://github.com/openframeworks/openFrameworks/issues/3669#issuecomment-106778065 ]

**Comment by arturoc** [comment]
ok that sounds correct, can you remove that line and send a PR. about gcc which one is the default installed in raspbian? if we change it to install gcc 4.8 by default and next version ships with 4.9 5... it'll keep installing 4.8

**Comment by bilderbuchi** [comment]
isn't there a possibility to specify `gcc >= 4.8` somehow?

**Comment by bilderbuchi** [comment]
if it mirrors wheezy, gcc default should be [4.7.2](https://packages.debian.org/wheezy/devel/gcc).

**Comment by Daandelange** [comment]
Yes, gcc [needs to be updated](https://github.com/openframeworks/openFrameworks/issues/3669#issuecomment-106778065) from a clean install.
`sudo rm g++` & `sudo ln -s g++-4.8 g++` replaces the old `gcc` shorthand symlink from the old version to the new version so compiling OF succeeds. (so logically this is a workaround, not a fix)

Maybe we could change `g++` to `gcc-4.8` in [debian_armv6l/install_dependencies.sh](https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/debian_armv6l/install_dependencies.sh), line 20 ?
`apt-get install libmpg123-dev alsa-base ...etc... g++ libgl1-mesa-dev ...etc...`

@bakercp https://github.com/Daandelange/openFrameworks/commit/6d973c64c8ccd61fb768e6b46115b1389e8d6a22
This commit removes the old repo. I'm hesitating if lines 2 and 3 also be removed ?
I just ran the script which succeeded on my rpi but everything was already up-to-date.
