### ISSUE TITLE
retina apps need second call to set window size

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#3733]
if i have an app using `HighResolutionCapable` as `True` and say:

```c++
ofSetupOpenGL(1280, 1280, OF_WINDOW);
ofLog() << ofGetWidth() << "x" << ofGetHeight();
ofLog() << ofGetScreenWidth() << "x" << ofGetScreenHeight();
```

i get:

```
[notice ] 1280 850
[notice ] 2880 1800
```

it looks like it's clipping to the available size before the window is even created? if i want a big window i have to say:

```c++
ofSetupOpenGL(1280, 1280, OF_WINDOW);
ofSetWindowShape(1280, 1280);
```

**Comment by ofTheo** [comment]
yeah - I am seeing this issue too on a MBP without having the high res plist value set. 

its because the scale is set to 2 at this point:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L261

So the supplied width and height which are in screen coords are then divided by 2 in the following call. 

removing:
```
        //have to update the windowShape to account for retina coords
        if( windowMode == OF_WINDOW ){
            setWindowShape(windowW, windowH);
        }
```
fixes the issue.
