### ISSUE TITLE
content of fbo rendered to png but not to pdf

### ISSUE THREAD

**Issue by liasomething** [openframeworks/openFrameworks#3804]
hi all,

i am not sure if this is an issue, but i could not find anything that seems to solve this...

i am trying to export the contents of an fbo that is bigger/higher than the screen to a pdf.

1) i am setting the window to 
ofSetupOpenGL(800, 3000, OF_WINDOW);

2)  i am setting the viewport for the pdf
ofBeginSaveScreenAsPDF(saveFileName+".pdf", false, false,  ofRectangle(0, 0, ofGetWidth(), 3000) );

3) i am randomly drawing circles to the fbo (and to the screen), at a random height of 3000

4) for testing if the fbo actually contains my graphic correctly i am exporting a png:
ofPixels pixels;
fbo.readToPixels(pixels);
ofSaveImage(pixels, saveFileName+".png", OF_IMAGE_QUALITY_BEST);
===> this is correct, the circles are drawn all over the png (randomly until 3000 height)

the fbo is not correct: even if i remove all the clipping paths in illustrator, i can see that the circles are only drawn in the area of the screen, leaving an empty area below.

5) i am also getting this error, but i am not sure if this is related, as is does not seem to influence the drawing of the circles in the upper part of the pdf ? :
"ofCairoRenderer: draw(): cairo mesh rendering doesn't support colors, textures, or normals. drawing wireframe"

+ i also uploaded the sample code temporarily here:
http://www.liaworks.com/wip/fbo_biggerThanScreen_exportPDF.zip

![png_pdf](https://cloud.githubusercontent.com/assets/183150/7489778/cadb5dc4-f3da-11e4-9ddb-4c303201de94.jpg)

**Comment by joaodafonseca** [comment]
I got the exact same problem? did you manage to solve this problem?

**Comment by arturoc** [comment]
hey sorry i didn't saw this before but you shouldn't need an fbo to render a bigger than the screen pdf. an FBO is a very openGL specific concept and it doesn't make much sense to mix it with pdf unless you really need to get the contents of the openGL renderer or something similar.

the problem here i think is that the viewport parameter when setting up the cairo renderer is kind of confusing because it's not so much the viewport as the surface size.

setting that parameter only sets the size of the final PDF but not the viewport so even if the size of the PDF is correct we need to set the viewport to that same size by calling `ofViewport(viewportRect)` before of after setting cairo. Since cairo will take the size of the surface from the current viewport we can do:

```cpp
 ofRectangle viewport(0, 0, ofGetWidth(), 3000);
ofBeginSaveScreenAsPDF(saveFileName+".pdf");
```

i've changed the name of that parameter to surface size, it would be probably even better to have a size or width, height parameters only but i'm going to leave it as it is for 0.9

**Comment by joaodafonseca** [comment]
Hey @arturoc, thanks for the answer it worked fine, i did actually asked something similar in the forum few hours ago, so you can ignore it. Let me just ask a quick question related to pdf export here! 
How can I export a pdf without the background?

**Comment by liasomething** [comment]
@arturo thanks for the solution!
