### ISSUE TITLE
ofSetFrameRate is inconsistent

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#3822]
hey guys,

ive been seeing some strange frame rate issues in the latest master over the last couple months...

basically say i set `ofSetFrameRate(60)`
this generally is working fine until i load a big file that takes a few seconds to load.
immediately after the file finishes loading, the frame rate jumps to a much higher number, 150 fps sometimes, but this value is always different.

i suspect its something to do with the fps trying to compensate for the number of frames lost while loading the big file... so it then tries to speed up to where it is supposed to be based on some kind of estimated frame count? 

i haven't dug into it yet but its just some theories atm.

anyone else seeing this.

im on macbook pro osx 10.10.3

**Comment by arturoc** [comment]
yeah i noticed this recently. i did some changes in the timers for the fps a while ago to fix some precision issues. it's much more precise now but it has this problem.  it's caused because we are using a blocking timer that waits until the next period by incrementing a counter so instead of saying sleep 15 ms it says wake up at 16 ms no matter how much time has passed during the current update cycle.

when an update takes too long it still increments the next time to whatever it needs and you get this effect where the timer tries to catch up.

the way to fix it should be by detecting if the current update cycle is already in the future respect to the next wake up time and increment the next wake up time until is not

**Comment by bilderbuchi** [comment]
is this really a "critical" issue? nothing's crashing, and it's not related to the remaining 0.9.0 core issues. I lean towards pushing back to not hold 0.9.0 back any more.

**Comment by ofTheo** [comment]
I think this would be worth fixing. 
FPS issues can have pretty crazy knock on effects. 
I'll take a look at it when working on the remaining 0.9 issues.

**Comment by arturoc** [comment]
i'm fixing it now will send the fix in a moment
