### ISSUE TITLE
remaining 64bit libs for vs2015

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#3910]
there's some libraries that are still missing or seem to have unresolved symbols:

missing:

    - glut

unresolved:

    - poco
    - libpng

**Comment by DomAmato** [comment]
I found glut, nvidia's cg framework has them. https://developer.nvidia.com/cg-toolkit-download
 the only unresolved symbols remaining for me are pixmans in cairo.

libpng needs to be compiled in 64bit which I am working on a patch to go along with the script. Doing it manually is easy but obviously if we can make it automated thats even better.

What problems are you getting with poco? I don't seem to be having any issues related to poco

**Comment by DomAmato** [comment]
I was able to get x64 projects up and running but they need their own 64 bit dlls as well which were easy enough to come by. havent exactly stress tested it but the project generator builds without issue. I also got pixman to stop throwing unresolved symbols by excluding mmx from the 64 bit build so the apothecary formula should now run. The Cairo-VS builds libpng and zlib now as well as pixman and cairo since the one that is a part of libpng only does x86.

I will make a separate PR for the updated vs export and update the PR for the libs

**Comment by liquidzym** [comment]
i got bunch of errors with poco,i guess something to do with openssl libs ?

>PocoNetSSLmdd.lib(SSLManager.obj) : error LNK2001: unresolved external symbol X509_STORE_CTX_get_error
1>PocoNetSSLmdd.lib(SSLManager.obj) : error LNK2001: unresolved external symbol X509_STORE_CTX_get_error_depth
1>PocoNetSSLmdd.lib(SSLManager.obj) : error LNK2001: unresolved external symbol X509_STORE_CTX_get_current_cert
1>PocoNetSSLmdd.lib(SSLManager.obj) : error LNK2001: unresolved external symbol X509_verify_cert_error_string
1>PocoNetSSLmdd.lib(Utility.obj) : error LNK2001: unresolved external symbol X509_verify_cert_error_string
1>PocoNetSSLmdd.lib(Context.obj) : error LNK2001: unresolved external symbol SSL_CTX_set_cipher_list
...................and more

1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2001: unresolved external symbol CRYPTO_num_locks
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2001: unresolved external symbol CRYPTO_set_locking_callback
1>PocoCryptomdd.lib(OpenSSLInitializer.obj) : error LNK2001: unresolved external symbol CRYPTO_set_dynlock_create_callback
.................and more.....

**Comment by liquidzym** [comment]
does openssl build script only build for win32?

**Comment by DomAmato** [comment]
no it should build for both

**Comment by liquidzym** [comment]
ok,i'm also getting the videoInput link error under the X64,did you get any of this? i have to add some DX libs in order to working
#pragma comment(lib, "strmbase.lib")  
#pragma comment(lib, "Strmiids.lib")  
#pragma comment(lib, "dmoguids.lib")

**Comment by DomAmato** [comment]
weird i had no problems with the videoInput libs and did not add any directX libs

**Comment by liquidzym** [comment]
maybe something wrong with my vs2015 IDE? i was installed online. i'm not sure its b'coz my git messup or what,anyway,i did re-complied cairo,no more error.
still got poco left,i still think something wrong with openssl libs
x64\ssleay32MD.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'

**Comment by DomAmato** [comment]
ill try cleaning everything and building to see if I can repeat the issue but it certainly looks like openssl was compiled with 32 bit and not 64 bit.

**Comment by liquidzym** [comment]
i double check with videoinput, i also did manual compiled with vs2015,same result. which version of vs2015 rc are you using? i have to add those dx lib to debug&release props sheets.
updated poco&openssl its here:https://github.com/liquidzym/openFrameworks/tree/vs2015-POCO-OPENSSL

**Comment by DomAmato** [comment]
I cant replicate your issue on any of my machines. I cloned the master and built it on two machines and never ran into the problems you are experiencing though I did run into a few issues related to poco and cairo that I will update in a PR shortly

**Comment by elliotwoods** [comment]
I can replicate videoInput issue here (pulled master 2 days ago):
![image](https://cloud.githubusercontent.com/assets/328294/8369939/1fcc11ae-1bfc-11e5-8572-69437cc047bb.png)

Same unresolved external symbols on Win32 and x64 builds.
This issue only shows when you try to use videoInput. @DomAmato - were you able to open a camera?

On Win32 I get the extra issues with OpenSSL:
![image](https://cloud.githubusercontent.com/assets/328294/8370051/c5ab12cc-1bfd-11e5-9afc-05bed04388ea.png)

Also be good to have better switching between platforms : https://github.com/openframeworks/openFrameworks/issues/4006

@liquidzym - where did you insert those pragmas? any reason to put them in pragmas rather than the project settings?

**Comment by liquidzym** [comment]
@elliotwoods,i was actually added to the .props sheet at the end,within the <AdditionalDependencies>
not too sure is this best option or not

**Comment by elliotwoods** [comment]
side point :
we have 'winmm.lib' in the 'Additonal Dependencies' of 'openFrameworksLib.vcxproj' for:
* Win32 / Debug NO
* Win32 / Release YES
* x64 / Debug YES
* x64 / Release NO

WinMM is legacy audio (wavein / waveout). I checked, we're not using functions from WinMM or including it anywhere. Replacing it with `strmbase.lib;Strmiids.lib;dmoguids.lib` solves the above unresolved symbols. But usually we put all libs into the app's `.props` file.

So best thing is just blanking this one and adding those libs to the `openFrameworksDebug.props` and `openFrameworksRelease.props`?

**Comment by elliotwoods** [comment]
aha. winmm is in the .props also

since we're already using conditional groups inside the .props, is there any opposition to combining `openFrameworksDebug.props` and `openFrameworksRelease.props` completely? (this would remove a lot of redundancy / accidental variations)

**Comment by arturoc** [comment]
the only problem i see is that it would break old projects, is it possible to have an openFrameworksDebug and Release.props that include the new file? the main reason to have this props files was that old projects kept working when we changed the settings

**Comment by elliotwoods** [comment]
i see. yes.
then perhaps have `openFrameworksCommon` which is included by both, and any specialization is done in the individual files?

**Comment by arturoc** [comment]
yes that would be great or even having both debug and release just including the new file that has everything in it just to keep old files compatible so in a couple of releases we can remove the debug and release files

**Comment by liquidzym** [comment]
+1 on this,yes,no need for winmm

**Comment by DomAmato** [comment]
The 32bit OpenSSL issues are because the current libs on the master are compiled for 64 bit. It should be fixed in the PR i made a few days ago https://github.com/openframeworks/openFrameworks/pull/3985

That PR also handles updates to the addons libs. I actually didn't try opening a camera.

 I wonder if this is something we can fix with the videoInput project rather than having to alter build props.

**Comment by DomAmato** [comment]
I figured out an easier way to fix the issue, by adding 
#pragma comment(lib,"Strmiids.lib") 

to @ofTheo 's videoInput files it fixes everything related to the videoInput errors that @liquidzym and @elliotwoods describe above

**Comment by elliotwoods** [comment]
great! 
i'll update to your method when it's in master
let's pull it!

**Comment by bilderbuchi** [comment]
@elliotwoods @DomAmato can we move forward with this issue now? the two PRs I see linked above are merged...

**Comment by DomAmato** [comment]
No ones raised an issue with a library recently so I think we are good.

Dominic Amato
Human Computer Interaction Masters Candidate
Physical Computing Lab (http://goo.gl/dguGzt)
DePaul University

-----Original Message-----

**Comment by bilderbuchi** [comment]
I'll tentatively close this, then.
