### ISSUE TITLE
change with lighting / regression

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#3942]
This is testing on OS X current master. The example project hasn't changed. 
ping @openframeworks/core  @openframeworks/2d-3d 

this is what the model noise example looks like in 0.8.4 

![screen shot 2015-06-16 at 10 14 05 pm](https://cloud.githubusercontent.com/assets/144000/8198489/2a2acb7e-1475-11e5-8881-4c9feb1d35c0.png)

this is what it looks like in master ( 0.9.0 ) 

![screen shot 2015-06-16 at 10 13 07 pm](https://cloud.githubusercontent.com/assets/144000/8198486/258321a2-1475-11e5-93ca-13566fe9eb2a.png)

**Comment by arturoc** [comment]
will check this later but surely is related with a bug we had in OF up until 0.8.4 where lights were being calculated using the full modelview matrix. this caused that when using calls like ofTranslate, rotate, scale but even when applying a node transformation. The lights were also affected by this. This issue was reported by @armadillu but can't find it right now.

Now OF stores the view matrix when a camera is set or a call to setupPerspective and uses that instead of the full viewmodel for the lighting.

This example is probably putting the lights in a position that is not really correct to compensate for that error. For example if the model is scaled by assimp the light might be in the unscaled position.

**Comment by ofTheo** [comment]
That makes sense @arturoc 
I just added a light.setPosition to the example and it looks fairly close to the old version. Closing this issue. 

Thanks!

**Comment by armadillu** [comment]
BTW Issue was reported on the forum http://forum.openframeworks.cc/t/oflight-positioning-weirdness/12806
