### ISSUE TITLE
objects with events gives "Call to implicitly-deleted copy constructor" error (c++11 related)

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#3974]
(I may be doing something wrong so apologies in advance!) 

	class objectWithEvent {
		public: 
		ofEvent<void> triggerEvent;
	};

	//--------------------------------------------------------------
	void ofApp::setup(){

		vector < objectWithEvent > tests;
		
		for (int i = 0; i < 10; i++){
		    objectWithEvent t;
		    tests.push_back(t);
		}
		
	}

gives this error "Call to implicitly-deleted copy constructor of 'objectWithEvent'"

digging deeper there's an explanation

```
/Users/zach/Desktop/openFrameworks/apps/projectGenerator/projectGeneratorSimple/src/ofApp.cpp:123:19: Copy constructor of 'objectWithEvent' is implicitly deleted because field 'triggerEvent' has a deleted copy constructor

/Users/zach/Desktop/openFrameworks/libs/openFrameworks/events/ofEvent.h:172:22: Copy constructor of 'ofEvent<void>' is implicitly deleted because base class 'ofBaseEvent' has a deleted copy constructor

/Users/zach/Desktop/openFrameworks/libs/openFrameworks/events/ofEvent.h:69:16: Copy constructor of 'ofBaseEvent' is implicitly deleted because field 'mtx' has an inaccessible copy constructor
```

so is there a usage pattern or am I doing something wrong?  I was looking at ofxBaseGui / ofxButton but I didn't see any issues there...   don't see this error in 0.8.4 so it seems 0x11 related...

**Comment by arturoc** [comment]
it was just that when i ported the events to not use poco i forgot to add a copy constructor. since the ofEvent class contains a mutex it can't be copied by default it isn't really a c++11 thing. also in c++11 when an object can't be copied (and in general in any case it's usually easier and faster) you can do:

```cpp
    vector <objectWithEvent> tests;
    for (int i = 0; i < 10; i++){
        tests.emplace_back();
    }
```

where you pass the parameters of the constructor to the emplace_back method instead of an instance, that way it creates the object directly in the vector without making any copies.

in any case i've added a copy constructor to ofEvent so events can be copied and push_back should be working

**Comment by ofZach** [comment]
ah makes sense!  thanks for the fix and explanation.  learned something new too !
