### ISSUE TITLE
Project generator issues for projects outside ..\..\.. level, VS2015

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/openFrameworks#4122]
Hi all. I'm having issues getting generated projects to load in VS2015 using both the legacy & simple PGs when creating projects outside the $OF_ROOT\apps\myApps level. The solution opens, but the project (in the sidebar) reads as "Project Name (load failed)" and another line (when clicking the project's disclosure triangle) reads "The project file cannot be loaded."

I dug into the .vcxproj file a little bit but didn't see anything obvious. There's a line which references the oF lib project, but correcting the path (I changed the beginning to ..\..\libs... since I put the app directly into the apps folder) didn't fix it. Curiously, oF will compile, even with an incorrect path to the ofLib.vcxproj file. 
<ProjectReference Include="..\..\..\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj">

Pinging @arturoc and @tgfrerer who seemed to be involved in these related issues/PRs:
https://github.com/openframeworks/openFrameworks/pull/3941
https://github.com/openframeworks/openFrameworks/pull/3929
https://github.com/openframeworks/openFrameworks/issues/3928

**Comment by mattfelsen** [comment]
Looks like the angle brackets got swallowed up...the line is:
\<ProjectReference Include="..\..\..\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj"\>

**Comment by tgfrerer** [comment]
Yes, i can see that windows project files outside of the apps folder will fail to resolve in a couple of places, and i fear we must consider the feature of having visual studio projects outside the app folder broken for now: 

These steps will most likely fail:

* resolving the openframeworks lib location
* copying the .dll files from $OF_ROOT/export/.. to the project directory

I'm trying to find an elegant way to handle this, maybe defining an explicit $OF_ROOT user macro in the `.props` file instead of having a relative path, and including this .props file topmost. It might mean to update a few lines in the project generator as well...

**Comment by ofZach** [comment]
if it's helpful the heart of the "making things work relatively" stuff is here: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp#L36-L52

which is basically finding and replacing ../../../ in a few text files.  It's trickier in VS since there are windows and unix paths.

**Comment by tgfrerer** [comment]
thanks @ofZach =) looking into it!

**Comment by arturoc** [comment]
if it helps, std::filesystem::path or ofFile or ofFilePath now support both / and \ indifferently and will output all \ in vs when calling string()
