### ISSUE TITLE
Project Generator Crashes during runtime VS2015

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4155]
When I build the simple project generator there are no errors and it works unless i include an addon. It works with a debug build but not a release build. The error is an access violation writing location but since I can't get it to happen in the debug I don't know exactly where it stems from

![capture](https://cloud.githubusercontent.com/assets/6936055/8897867/e2eba4a4-33e1-11e5-9ee7-d10ecbf4a3c1.PNG)

It always crashes when adding the src files from the addons

**Comment by DomAmato** [comment]
The error is an access violation writing location but since I can't get it to happen in the debug I don't know exactly where it stems from

**Comment by bilderbuchi** [comment]
I find it suspicious that the folder separators switch between `/` and `\`several times, I'd assume that that could be a problem..

**Comment by ofZach** [comment]
can you put some print outs in this function to see if crashes inside or more specifically where it crashes?

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp#L113-L195

also, have you cleaned and rebuilt this?  sometimes if it crashes in release and not debug (or vice versa) I get suspicious of memory / memory layout and start to hunt down uninitialized variables and / or missalignement voodoo with objects out of sync.  

@bilderbuchi the paths do look like garbage but they get fixed right away in the visualStudioProject addSrc via fixSlashOrder.   Part of the problem is that the recursive parsing of the addons folder must sort of assume a unix path so it's combining fragments of paths weirdly.

**Comment by DomAmato** [comment]
Cleaning and rebuilding didn't fix things. I added some print outs and it crashes inside appendFilter at this line: 

    string uuid = generateUUID(folderName);
folderName is just addons

**Comment by ofZach** [comment]
thanks for investigating, does it seem to crash in the generateUUID function itself?  Can you add some printouts to see there.   The generateUUID is in utils.cpp.   I'd specifically be interested to know if digestString is too short for the substr call, for example.  thanks again!

**Comment by DomAmato** [comment]
ok getting some weird behavior in UUIDgenerator 
when I do

    ofLogNotice("VSPG") << "substringing";
    digestString = digestString.substr(0,24);
    ofLogNotice("VSPG") << "convert to uppercase";
    digestString = StringToUpper(digestString);

it works, if I comment out either of the ofLogNotices, which I added for debugging purposes, it crashes with the access violation error

**Comment by tgfrerer** [comment]
I'm looking into this at the moment. My current working hypothesis is that it has something to do with optimisation. I'm getting the same error as @DomAmato, but it disappears when I disable optimisation for the PGSimple/Release build target.

**Comment by DomAmato** [comment]
I'm glad it wasn't just me experiencing a weird bug +1 for the fix!
