### ISSUE TITLE
freetype versions out of sync w/ Apothecary

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4161]
@danoli3 @DomAmato @arturoc et al.

In trying to solve #4148, I found that the the version of freetype defined in the apothecary script is different than the actual header / libs version in master.

Did this just slip through the cracks or is there a reason we haven't updated it to the latest?

CB

**Comment by DomAmato** [comment]
weird since there are files in there that were updated earlier than the header but are from the 2.5.5 version instead of the 2.5.3.  The 2.5.5 files from ~3 months ago and the 2.5.3 header from ~2 months ago. I assume it must have slipped through the crack unless someone knows something I don't, the VS libs were compiled with 2.5.5

**Comment by arturoc** [comment]
it's strange that none of the platforms have overwritten this header, perhaps check that it's not being gitignored or something

**Comment by bakercp** [comment]
See #4165 and #4164

**Comment by bakercp** [comment]
Just an additional note -- on Raspberry Pi 2, we get the same warnings, which leads me to believe that the version of FreetType shipping with RPi2 is a bit older as well.  This is not a big deal, and only tangentially related to this issue.

**Comment by arturoc** [comment]
yes wheezy is from 2013 and debian doesn't update things much between major versions except for security or other critical fixes
