### ISSUE TITLE
ofMap divide by zero warning causes RPI to slow to an unusable speed under some conditions

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#4217]
In some cases, such as with the 3DPrimitivesExample, if the ofMap params lead to a divide by zero ofLog warning, which, in the case of RPI2 runs in the background and slows the app down so much that you can't interact with the app anymore.

I'd recommend that we document the fact that we explicitly avoid divide by zero errors and remove the logged warning, or make it verbose.

**Comment by ofTheo** [comment]
+1 or switch message to OF_LOG_VERBOSE ? 
Incase people want to track down divide by zero?

I often put a breakpoint on that message for fixing input errors.

**Comment by bakercp** [comment]
I've been looking for precedents and the closest I can find is this:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofShader.cpp#L202-L206

I'll bet (?) this was done for similar reasons ...

**Comment by bakercp** [comment]
ping @arturoc

**Comment by arturoc** [comment]
i don't think setting it as verbose is a good idea. the verbose mode in OF is still super time consuming and if it's not clear why things are slowing down it'll be worse than now.

i've asked several times to remove it since every time i've encountered this error it is solved by the internal logic to return the min value but people use it as a debug point so i guess we have to live with it :)

the standard solution for this kind of stuff is to just use asserts and crash on it, that way the debugger catches them without even having to set breakpoints and asserts are gone in release mode if you define NDEBUG so the program will never crash or spam the console as we do now when running in release

**Comment by kylemcdonald** [comment]
+1 @arturoc

**Comment by ofTheo** [comment]
I'm fine to remove the warning if it's causing slowdown for a platform.  I'd rather that than assert :)
