### ISSUE TITLE
Move issues labeled as ProjectGenerator to the ProjectGenerator Repository

### ISSUE THREAD

**Issue by DomAmato** [openframeworks/openFrameworks#4220]
Currently there are 25 open issues labeled as project generator and they probably belong on the project generator repository can we shift the issues over there?

**Comment by kylemcdonald** [comment]
whether the project generator should exist in it's own repo is an open question as far as i know. @ofzach @oftheo @arturoc have discussed whether submodules are the right way to go or not in this case.

if they plan on moving it into this repo, i suggest leaving the issues here. if they plan on keeping it a submodule, i suggest moving the issues over then closing this one.

**Comment by ofZach** [comment]
I think we can move it over to OF as @ofTheo suggest, at the moment it's a bit odd since there's code in the OF repo (in addons) and in the project generator repo (the visual layer).  I think if we can unify everything having it in one repo is fine.   We're very close to making just one tool (command line w/ visual GUI) and I think that will be the right moment to do the move.

**Comment by kylemcdonald** [comment]
closing this issue, assuming that the PG will be moved to the main OF repo pretty soon and we don't need an issue for that.

**Comment by arturoc** [comment]
i'd vote for keeping it as a separate repo and just add the facilities to add addons from any folder so we can move the common code back to the sub repo. having different repos, makes it more flexible i think even with the occasional problems that git submodules have

**Comment by bilderbuchi** [comment]
as long as we're voting, I'm for keeping it in the main repo - less potential for the issue to fall to neglect, organiziation-wise we have had the issue label  for the PG for a long time, and things like code desynch between the main repo and the PG (due to not having updated the submodule), or the packaging script or nightly builder using the "wrong" PG version are not possible.

**Comment by ofZach** [comment]
one thing that's kind of a pain about having them separate is that when you are working on new features, you wind up having to do two different PRs across two repos.  It feels a little schizophrenic :)

**Comment by kylemcdonald** [comment]
yeah, usually this would be a feature because it would allow work to happen separately from `master` without needing to stay perfectly up to date. but maybe having a `pg` branch with the most up-to-date pg would solve this? then we can merge it to master whenever it's ready.

**Comment by ofTheo** [comment]
I honestly would love to have everything in the main repo. 
Both Nick and I spend a ton of time the other day trying to get the PG submodule to sync / update. 

If its that hard / basically impossible for us, it must be fairly tough for the average user. 

I would love to just have it in the main issue and add a Project Generator label for issues. 
It will make it much easier to get fixes in and to help people contribute.

**Comment by ofZach** [comment]
I think we're close to a point where we can get rid of the legacy and simple PG, once that happens, I'd also vote for moving it over since it should be easy to give developers step by step instructions on how to make examples, etc.   

How we deal with the gui is another story, I'm not sure what the best solution is for that (for now we've made a repo here https://github.com/ofZach/pgElectron for the gui component).  For 0.9 this might be done by hand for the platforms but later we should look at how to automate it.

**Comment by bilderbuchi** [comment]
>  add a Project Generator label for issues. 

this already exists. I labeled this issue as such
