### ISSUE TITLE
Compushaders examples bundled in osx release

### ISSUE THREAD

**Issue by thomasvanta** [openframeworks/openFrameworks#4236]
0.9.0 rc1

**Comment by bilderbuchi** [comment]
Thank you for taking the time to report this bug and helping to make openFrameworks better. Unfortunately, we cannot work on this bug because your description didn't include enough information. You may find it helpful to read "How to report bugs effectively" http://www.chiark.greenend.org.uk/~sgtatham/bugs.html. We'd be grateful if you would then provide a more complete description of the problem.

At a minimum, we need:

    the specific steps or actions you took that caused you to encounter the problem,
    the behavior you expected, and
    the behavior you actually encountered (in as much detail as possible).
    Platform (Mac/Windows/Linux/etc..) and version of Operating System

Thanks!

**Comment by arturoc** [comment]
the problem is that the compute shader examples are in the osx downloads but those examples don't work in osx.

not sure if we should remove them or just add a message in case the application fails to start saying that most probably your os doesn't support the required openGL version yet.  if at some point there's support for opengl 4.3 in osx we would already have them there

**Comment by thomasvanta** [comment]
yep, sorry for the missing explanation.
4.3 OpenGL support is not expected in the next OS X version, El Capitan. So until at least Q4 2016 no support.
removing them is safe in my opinion
