### ISSUE TITLE
ofxOpenCv compilation fails  - RC0.9 

### ISSUE THREAD

**Issue by mrzl** [openframeworks/openFrameworks#4241]
This occured on Win8.1, when the ofxOpenCv addon is added.

opencv_calib3d249.lib(fundam.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(fundam.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(calibration.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(calibration.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(calibinit.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(calibinit.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(opencv_calib3d_pch.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(opencv_calib3d_pch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(modelest.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(modelest.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(checkchessboard.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(checkchessboard.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_calib3d249.lib(circlesgrid.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_calib3d249.lib(circlesgrid.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
2>opencv_core249.lib(dxt.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
2>opencv_core249.lib(dxt.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj

**Comment by ofTheo** [comment]
thanks for the report - do you get this same error when you run the examples/addons/openCvExample?
Or only when adding the addon to a new project?

**Comment by ofTheo** [comment]
ping @DomAmato too.

**Comment by ofTheo** [comment]
also if you build in release instead of debug does the issue go away?

**Comment by DomAmato** [comment]
Look at the project settings in visual studio. The project generator doesn't parse the included libs properly so it includes the debug and release libs. You will see that it includes both the the debug and none in the release so if you manually change the included libs in the linker menu it will compile. Also make sure the right architecture is linked and setup in the additional libraries also in the linker menu

**Comment by ofZach** [comment]
hmm, I don't think we had this problem in the past.   maybe then we should add to this file: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxOpenCv/addon_config.mk

rather then rely on parsing from the FS?  also, do you think it makes sense just to use the release libs for both targets?

**Comment by ofTheo** [comment]
I think VS won't compile in Debug if it doesn't have the Debug libs as it changes the size of objects for debugging.  So in debug you need to be linking against the debug libs ( as far as I remember )

**Comment by ofZach** [comment]
@arturoc @bakercp what if we added to addon_config.mk the ability to specify release and debug libs?
would this have an impact on the makefile system?

it would be easy to add the parsing on the PG side here: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/addons/ofAddon.cpp#L203-L205

at the moment, an addon just has a pile of libs: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/addons/ofAddon.h#L33

but it could had

libs 

and this gets converted to release and debug at some point like here: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/projects/visualStudioProject.cpp#L369-L402

but internally for the addon we could have: 

libs  (common libs added to both debug and release) 
libs_debug (debug libs as specified by addon_config.mk) 
libs_release (release libs as specified by addon_config.mk)

and I think it would be helpful to be more precise (and with addon_config we can be!), then we can drop this adhoc parsing at the project level, which seems maybe buggy?

I'm open to other suggestions and will fire up windows to investigate the current issues.

**Comment by gorkacortazar** [comment]
@ofZach i think it mixes two separate problems, one is the one I reported in #4038. The second one is that now we have separated libraries for i386 and x64 builds, and the PG doesn't recognise the structure and add all the libraries to all architectures.

One thing that that I have been thinking is that maybe is not necessary to build the same solution for both architectures... Just a thought.

**Comment by arturoc** [comment]
having the possibility to specify flags for debug and release in addons_config.mk makes sense but we could also have the possibility of *optionally* having:

```
/lib/vs/Win32/debug 
/lib/vs/Win32/release
/lib/vs/x64/debug
/lib/vs/x64/release
```

which would be pretty straight forward to parse:

```
if(ofFilePath::join(libfolder.path(),"debug").exists()){
    // add files in libfolder/debug to debug libs
}else{
   // add files in libfolder/ to debug and release libs
```

**Comment by DomAmato** [comment]
@gorkacortazar are you suggesting a separate solution for x64 and win32 builds? I would be ok with the PG having an option of selecting one or both architectures but not force them to build different solutions when the ability to switch between architectures is so easy. I could see uses when they may only need one, say a addon that uses a lib thats only 32 bit compatible or something.

as for the separate directory route that was also brought up in the other thread but since my knowledge of the project generator is shallow at best I don't know which particular solution fits best. My intuition is to go the route that requires the least work for people to update their addons to work with OF 0.9.0

**Comment by ofZach** [comment]
as for the separate directory route that was also brought up in the other thread but since my knowledge of the project generator is shallow at best I don't know which particular solution fits best. My intuition is to go the route that requires the least work for people to update their addons to work with OF 0.9.0

it might help to explain a little about the PG -- 

the way it works is we have a concept of an addon as basically a collection of files / libs / headers paths, etc: 

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/addons/ofAddon.h#L28-L44

this gets parsed from the file system first and then from the config file

https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxProjectGenerator/src/addons/ofAddon.cpp#L485

the parsing of the file system is recursive and has a bit of smarts to avoid looking in folders of different targets.   If there were different targets vs32, vs64, then we could make sure we look in the right folder and not use libs from the wrong target. 

at the moment, the addon itself isn't very smart and at the project level (for VS) we figure out if a library is debug or not (using a very cheap trick of looking for libs that have the same name but with a "d" added at the end).   

I hope this background helps, happy to point out more specifics

**Comment by gorkacortazar** [comment]
@domAmato yep basically I think that adds an unnecessary complexity to the
PG. I can't think on any situation that i would like to build both
architectures of the same application, but a think that you decide first.
In osx is very simple, as 32/64 bits libraries are merged in the same file
after compilation, but i couldn't find something similar for VS. In linux,
they have completely separate distributions because you need to select a 32
o 64 bit version when you install the os. An option in between, selecting
which architecture you want the project to build before creating the
solution may make sense.

@ofZach while the automatic approach its necessary, automatically detecting
files for some addons can be difficult. Maybe an standard path in the sorts
of libs/vs/x64 that can be overridden in the addon_config.mk may help with
addons that need for any reason other structure (for example ofxOculusDK2
is one example), having default target paths for i386 and x64 as arturo
suggested?

**Comment by arturoc** [comment]
i don't think having different solutions for each arch makes sense. having all the architectures in the same project is pretty standard practice and visual studio has the necesary tools to support it without problem.

even if it won't be very common with OF, if you want to create an application to redistribute, you probably want to create 32 and 64bits binaries, having to keep uptodate to projects or solutions at once just to do that doesn't make sense

**Comment by arturoc** [comment]
btw, we already have different paths for win32 and x64 what we don't have is different paths for debug and release. in most platforms is not needed, well in any except visualt studio but i think it would be trivial to add it for all libraries including the core ones since we are changing the folder structure for 0.9 anyway. 

parsing the final d, is way trickier and error prone than looking for an extra folder i think

**Comment by tgfrerer** [comment]
Agree with @arturoc. Something we might want to investigate is to use .props file more for visual studio. You can define them per debug / release platform and I've seen very elegant use of them by @elliotwoods.

**Comment by gorkacortazar** [comment]
@arturoc got it, in that case makes complete sense to support both
architectures in the same solution. And the idea to separate in
debug/release subfolders is great.

Agree with @arturoc <https://github.com/arturoc>. Something we might want
to investigate is to use .props file more for visual studio. You can define
them per debug / release platform and I've seen very elegant use of them by
@elliotwoods <https://github.com/elliotwoods>.

—
Reply to this email directly or view it on GitHub
<https://github.com/openframeworks/openFrameworks/issues/4241#issuecomment-131011680>
.

**Comment by DomAmato** [comment]
I can take a look into utilizing the props files since we already use it for the OF lib build (though it doesn't change or get generated quite the same way) however such a feature should certainly be considered for a later release. 

I feel like the separate folders seems to be the easiest solution since we can also change the build scripts to make and separate the libs into those folders. It already does it by architecture so doing it by debug/release is like one maybe 2 more lines in the shell script.
