### ISSUE TITLE
oF 0.9.0RC1 linux release without libs/.project for eclipse

### ISSUE THREAD

**Issue by fx-lange** [openframeworks/openFrameworks#4244]
the linux release (at least the x64) has no libs/.project file for eclipse. addons and libs/openFrameworks are fine.

**Comment by fx-lange** [comment]
just realized that even the master and the android rc1 don't have the project file anymore. is it not needed anymore?

**Comment by arturoc** [comment]
we are not using that project anymore, i need to update the openframeworks project with some changes i've done. since the makefiles output now absolute paths the semantic analisys works pretty much perfectly once you've compiled once. i have an updated .cproject for the core project that i haven't uploaded yet but i'll do before RC2
