### ISSUE TITLE
terminal in bad state when killing ofApp

### ISSUE THREAD

**Issue by avilleret** [openframeworks/openFrameworks#4302]
I'm building an ofApp on Raspberry Pi and as I'm used to do, I do that through an SSH connection.
When I want to stop my running I press `CTRL + c` in my SSH session.
This normally send a SIGART to the app and if it is handled correctly, the app stops after some reset.
But often with OF (0.8.4) the terminal stay in a bad state (see #4293).
Sometimes I can enter `reset` and press enter to reset the terminal, but often the app doesn't return, I don't have access to my terminal anymore, and the display window isn't close.
I have to close my terminal and open a new one.
Then `ps -C myApp` shows something like : 

~~~~
PID   TTY   TIME        CMD
3622 ?        00:00:00  myApp
~~~~

how is it possible to fix that and make the app closing correctly each time ?

btw, I can put a keyboard on the RPi and setup a keyPressed function like : 

~~~~
void ofApp::keyPressed(int key){
  if ( key == 27 ){
    cout << "Exiting" << endl;
    exit();
  }
}
~~~~

But I really would like to be able to correctly close the app from the SSH session.

Thanks

**Comment by bakercp** [comment]
Hey @avilleret I won't have a chance to look at it today, but if you want to start hunting down the problem here are a few references.

First, we capture the previous terminal state here when connecting to the keyboard (so we can turn off echo, etc).

https://github.com/openframeworks/openFrameworks/blob/5b9d0a1d8fef16937c16715c8b32dd2f7e100384/libs/openFrameworks/app/ofAppEGLWindow.cpp#L1401-L1407

Second we attempt to reset the original state when restarting the app:

https://github.com/openframeworks/openFrameworks/blob/5b9d0a1d8fef16937c16715c8b32dd2f7e100384/libs/openFrameworks/app/ofAppEGLWindow.cpp#L1435

If for any reason the app crashes and `ofAppEGLWindow::destroyNativeKeyboard` doesn't get called, then you run into problems.

Anyway, those are some places to start testing!

**Comment by avilleret** [comment]
Thanks @bakercp 
It seems that some work have been done on appRunner.cpp related to signal handler, so I will try with of from git when can managed some time to build it.
I think this shoul be my first step

**Comment by bakercp** [comment]
@avilleret sounds like a good plan!

**Comment by jvcleave** [comment]
In some example testing I did notice I had to often hit `CTRL+c` twice but I haven't had the terminal corruption yet

Another thing to test for is `CTRL+\`

**Comment by arturoc** [comment]
i fixed the signals at some point and now, the first ctrl+c is catch by OF and it tries to finish gracefully, close everything... if it still gets stucked a second ctrl+c will definitely close the app

**Comment by avilleret** [comment]
Thanks @arturoc it seems to be fixed in of_v20150827_linuxarmv7l_release nightly build.
I should have try this one before making so much noise.
Please forgive me.
