### ISSUE TITLE
Bug ofxTCPServer connection

### ISSUE THREAD

**Issue by upflandry** [openframeworks/openFrameworks#4339]
I'm working on Windows 10 and each time I setup a TCP connection

For instance:
TCP.setup(11999);
with the VS 0.9.0 Release Candidate 1, I always have this error
[ fatal ] ofThreadErrorLogger::exception: device or resource busy

I have this error on 2 machines, with the addons ofxTCPserver example or with the project I'm currently developing

**Comment by bilderbuchi** [comment]
ping @arturoc

**Comment by mattfelsen** [comment]
Same here, I'm seeing this on Windows 9.1 on master

**Comment by arturoc** [comment]
can you check if this still happens with latest master?

**Comment by arturoc** [comment]
i'm going to close this since all the tests for creating a connection on windows are passing now also i've tested in my machine with windows 8.1 and it works without problem. you only have to tell the windows firewall to allow the app to open the port when it asks so but from there on it'll work ok.

**Comment by mattfelsen** [comment]
Just got around to testing this and both the network & client tcp examples are working for me on 8.1 – thanks!

**Comment by upflandry** [comment]
Yes, it works on windows 10 also, cheers!
