### ISSUE TITLE
ofSaveImage to the data folder causes unneeded warning

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/openFrameworks#4352]
`[warning] ofDirectory: createDirectory(): directory already exists: "../../../data/"`

```
ofSaveImage(pix, "test.jpg");
```

This is because ofImage::saveImage tries to create the folders needed and when passing an empty file path it will be the data folder which already exists. https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/graphics/ofImage.cpp#L341

My suggestion would be to change the warning to a verbose. 
As if you are saving a series of images to the same directory you'll get this warning every time.

Or another option would be to have ofImage first check if the directory needs creating. 
My preference would be the former as it results in the least change to functionality.

**Comment by arturoc** [comment]
yes in general ofFileSystemUtils is too verbose, i would even just remove it completely. at some point we could even make those functions return some kind of error enum like:

```
enum ofFileSystemError{
    OK,
    DIRECTORY_EXISTS,
    FILE_EXISTS,
    ....
}
```

so if you really need to know if createDirectory failed or didn't failed but the folder was already ther would return something like:

```
switch(ofDirectory::createDirectory("something")){
    case OK:
    ....
    break;
    case DIRECTORY_EXISTS:
    ....
    break;
    default:
    break;
}
```

which would mostly replicate the exceptions thrown by the underlying filesystem library but instead of throwing it would return an error enum

**Comment by ofTheo** [comment]
sounds good! 
I'll remove it.
