### ISSUE TITLE
ofxAssimpModelLoader - ES1 and ES2 discrepancy when using ofMaterial

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4449]
have noticed (but haven't explored fully) that ofMaterials in ES2 don't work the same as for ES1.
i am currently loading a model using ofxAssimpModelLoader which contains materials, ES1 renders the model fine but with ES2 the model is rendered completely black.
i narrowed down this issue to ofMaterial in ES2 by commenting out the use of materials in the ofxAssimpModelLoader draw function, after which the model then renders correctly.

the material values in the collada file all seem to be valid, and the fact that it renders on ES1 and not ES2, points to be an issue with the way that materials have been implemented in ES2.

cc @arturoc - this might also be a Android issue.

**Comment by danoli3** [comment]
Is there possibly an order differential? I'm thinking like Big Endian / Little Endian style

**Comment by ofTheo** [comment]
We might have seen a similar issue with materials and the programmable renderer on desktop. 
Loading FBX models we would get some rendering black.  I think we had to disable materials to get it to work.  pinging @NickHardeman as he might remember what the issue was more clearly. 

also ping @arturoc  and @tgfrerer

**Comment by arturoc** [comment]
yes, i'm seeing the same in android, i'm taking a look now...
