### ISSUE TITLE
osc examples only compile in release mode on OS X

### ISSUE THREAD

**Issue by antimodular** [openframeworks/openFrameworks#4467]
all examples for osc in the example addon folder only compile in release but not debug mode, on OS X 10.10

**Comment by bilderbuchi** [comment]
ping @openframeworks/macos

**Comment by ofTheo** [comment]
@antimodular what are the errors you are getting in debug?
Did you clean before rebuilding?

**Comment by antimodular** [comment]
yes i tried clean in Xcode but still did not work.
it's not a big problem.

<img width="1140" alt="screen shot 2015-10-27 at 11 00 19 am" src="https://cloud.githubusercontent.com/assets/3649364/10765758/f7d30528-7c99-11e5-833e-a7730efe6d5b.png">

**Comment by admsyn** [comment]
Looks like it's not getting any symbols from the OF library itself, which is being built for the wrong architecture. Maybe it's getting confused since you have more than one OF project open. 

Can you try closing all other OF projects and re-opening that one? The "Workspace integrity" error should go away.

**Comment by ofTheo** [comment]
I just tried and it builds fine for me in Debug. 
This issue is definately what @admsyn mentions. 
Closing :)

**Comment by antimodular** [comment]
true. closing all other project did the trick. thanks.

**Comment by arturoc** [comment]
we should solve this anyway, the probelm is that if the OF project is open somewhere else and you try to clean it won't clean the OF project only the application. also it shouldn't be necesary to clean in order to build for another architecture, the OF library should be built as universal or build 2 different names, openFrameworks.a and openFrameworks64.a or something like that

**Comment by ofZach** [comment]
+1 to universal or different names, I've seen this issue a few times so far working with 0.9... (I think I've opened up an issue on it already)

**Comment by ofTheo** [comment]
@ofZach @arturoc I can take a look at that - it should be fairly easy!

**Comment by ofZach** [comment]
here's the issue I opened: https://github.com/openframeworks/openFrameworks/issues/4424
