### ISSUE TITLE
osx project generator not creating runnable app

### ISSUE THREAD

**Issue by phirestalker** [openframeworks/openFrameworks#4599]
I am able to compile the app, however it will not run. According to the turorials on the openframeworks website I should be able to run it and show a blank window without adding any code. All xcode says is build successful and doesn't start anything.

I am running osx 10.11.1 with latest xcode, let me know what you need me to upload

**Comment by ofZach** [comment]
can you check that you have the right target set? (sometimes the target is set to openframeworks and not the app itself):

<img width="231" alt="screen shot 2015-11-18 at 1 19 38 am" src="https://cloud.githubusercontent.com/assets/142897/11234079/897b7be6-8d92-11e5-8fb7-e7637d33c9f0.png">

if the target is set to OF will just compile the OF library (which is a dependency), otherwise, you should be able to compile an app and run it.

**Comment by phirestalker** [comment]
sorry the tuts looked different I thought the middle bar was where i choose the target. It was on the wrong target

**Comment by ofZach** [comment]
no problem!  closing this issue...  (also the OF forum is a good place to ask if you are having any issues getting started with OF)
