### ISSUE TITLE
Removal of Poco in OF 0.9.0 release?

### ISSUE THREAD

**Issue by vinjn** [openframeworks/openFrameworks#4617]
From http://blog.openframeworks.cc/post/133076054194/openframeworks-090-major-changes

```With C++11 to C++14 support for all platforms, the C++ standard library now or in the near future will provide all the core features we used from Poco. Features that are still not part of C++14 are temporarily provided via boost::filesystem. The Poco libraries still come packaged with OF to retain backwards compatibility for anybody who is using the Poco libraries directly.```

Personally I would love to see the removal of the huge Poco lib to make OF more lightweight.

In current code base, Poco is still used in many places, like `ofThread`.
Does it mean Poco hasn't been removed from core library?

**Comment by arturoc** [comment]
as the blog post says poco is still around to make porting old applications easier. also there's still 2 places where we use it. ofThread, which will go away in 0.10, there's already a PR. and ofURLFileLoader which we still need to find a replacement library. the most probable candidates are cpp-netlib http://cpp-netlib.org/ which still has some problems (one of it's dependencies, cpp-uri crashed xocde so we had to remove it before the 0.9.0 release). another posibility is curl which is way more mature but has a c api instead of c++.

in anycase once ofThread is ported to std::thread it would be really easy to compile OF without poco since the http dependency now has a bas class and would be easy to config it in ofConstants so it doesn't use the poco implementation

This is more a question for the forum rather than an issue so i'm going to close it

**Comment by vinjn** [comment]
OK, thanks!
And I will turn to forum for similar future questions.
