### ISSUE TITLE
Feature : ofBuffer::reserve

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#4657]
something like this: 

```c++
//--------------------------------------------------
void ofBuffer::reserve(std::size_t _size) {
	buffer.reserve(_size + 1);
}
```

this means the inner vector allocates the data to use later (without changing the 'public' allocated size)

**Comment by elliotwoods** [comment]
this is useful if you're using `append` in many steps
so that it'll allocate the chunk of memory first rather than re-allocating and copying as required along the way

**Comment by arturoc** [comment]
yes sounds useful, i have a branch somewhere with resize and setall (similar to setmem) i'll add this too and send a PR

**Comment by elliotwoods** [comment]
For a quick note... I found ofBuffer still too slow for my application:

My findings:

|Method|Time|
|---------|------|
|`ofBuffer`|56ms|
|`ofBuffer` with `reserve`|48ms|
|Hand-rolled buffer object|18ms|

I'm using `.append(..)` a lot, which in the case of `ofBuffer` uses `std::insert` which (I presume) always results in 2 copies being made. 

For note, my own `class Buffer` is based around:
```c++
class Buffer {
public:
/* ... */
	void allocate(size_t size) {
		this->deallocate();
		this->buffer = new char[size];
		this->allocation = size;
	}

/* ... */

	void append(const char * data, size_t size) {
		auto newPosition = this->position + size;
		if (newPosition > this->allocation) {
			throw(std::out_of_range("Cannot append outside of allocated region"));
		}
		memcpy(this->buffer + position, data, size);
		this->position = newPosition;
		this->_size += size;
	}

/* ... */

protected:
	char * buffer;
	size_t position;
	size_t _size;
	size_t allocation;
};
```

**Comment by arturoc** [comment]
are you working in release?

**Comment by arturoc** [comment]
been doing some tests and insert seemed to be rally slow, not sure why it probably was doing push_backs for each element instead of a memcpy. i've added a position variable to track the size but the buffer is still backed by a vector to simplify the logic. it is much faster now (seems faster than your implementation in my tests too) and still allows to reallocate on append.

at some point i might move it to hold a raw pointer since i'd like to have a method similar to setFromExternalPixels so you can wrap external memory but still have the same utilities ofBuffer has but i'll leave that for later.

i'll merge this in once 0.9.1 is donw
