### ISSUE TITLE
swapRgb is too smart

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#4683]
I expected the following code to take an image that happened to be BGR and convert it to RGB. And it looks like it did that correctly, except it also switched the pixelFormat which means it gets displayed on the screen as it was originally, making the function kind of useless...

```c++
#include "ofMain.h"

class ofApp : public ofBaseApp {
public:
    ofImage img;
    void setup() {
        img.load("img.jpg");
    }
    void update() {
        if(ofGetFrameNum() % 30 == 0) {
            img.getPixels().swapRgb();
            img.update();
        }
    }
    void draw() {
        img.draw(0, 0);
    }
};
int main() {
    ofSetupOpenGL(512, 512, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

my workaround is to use a function that only swaps the colors and doesn't change the pixel format:

```c++
void swapRgb(ofPixels& pix) {
    for(auto pixel : pix.getPixelsIter()) {
        std::swap(pixel[0], pixel[2]);
    }
}
```

my ideal solution would be to have two separate functions: one for swapping the colors, the other for swapping the pixel format.

**Comment by arturoc** [comment]
i think the function is doing the right thing, the problem is that the image has a different format than expected, not sure if it's a bug in ofImage or just that the image you are loading has the channels swapped. if it's the second you can just set the correct format before calling swapRgb():

```cpp
img.getPixels().setFormat(OF_PIXELS_BGR);
img.getPixels().swapRgb();
img.update();
```

**Comment by arturoc** [comment]
also if you just want to make the image look correct in the texture you can just change the format and update which would be much cheaper than actually swapping the pixels:

```cpp
img.getPixels().setFormat(OF_PIXELS_BGR);
img.update();
```

**Comment by kylemcdonald** [comment]
aha, i was looking for something like `setFormat`, that solution is also totally reasonable. thanks :)

**Comment by pierrep** [comment]
I just ran into this same problem, except that I can't find the setFormat function for ofPixels any more. Has it been removed?

**Comment by arturoc** [comment]
i'm checking and there's never been a setFormat method it looks like :)  can you open a new issue explaining the problem better?

**Comment by pierrep** [comment]
I'm not sure if it warrants a new issue, I had the exact same problem as Kyle - I've been looking at the Gif loading addons that use FreeImage and realised they were broken in various ways. One problem was that the images were loading in as BGR instead of RGB. Adding a swapRgb() call after the FreeImage loading process wasn't enough. I had to force the ofPixelFormat first (I copied this from the ofImage code).

e.g. This doesn't work:

```
  unsigned char* bmpBits = FreeImage_GetBits(bmp);

    if (bmpBits != NULL) {
        pix.setFromAlignedPixels(bmpBits, width, height, pixFormat, pitch);

#ifdef TARGET_LITTLE_ENDIAN
        if (channels >= 3) {
            pix.swapRgb();
        }
#endif
```

But this does:

```
  unsigned char* bmpBits = FreeImage_GetBits(bmp);

    ofPixelFormat pixFormat;
    if (channels == 3)
        pixFormat = OF_PIXELS_BGR;
    if (channels == 4)
        pixFormat = OF_PIXELS_BGRA;

    if (bmpBits != NULL) {
        pix.setFromAlignedPixels(bmpBits, width, height, pixFormat, pitch);

#ifdef TARGET_LITTLE_ENDIAN
        if (channels >= 3) {
            pix.swapRgb();
        }
#endif
```

The point is that the first example _seems_ like it should work, i.e. swap the R and B. However it doesn't because of the reason Kyle gave.

**Comment by arturoc** [comment]
Instead of adding a swapRgb what you should do is load the pixels into the ofPixels as OF_PIXELS_BGR  that should solve it and is faster since it avoids swapping the pixels

**Comment by arturoc** [comment]
to clear it up... swapRgb does the right thing, swaps the channels R and B but also changes the format of the ofPixels to signal that the format is not rgb anymore but bgr (or the opposite).

we could add a new function that swaps the pixels without changing the format in case you really want to show the image with the channels swapped but since that method was initially created for this case, just loading the data using the correct format is a better solution
