### ISSUE TITLE
ofxOpenCv compiling error : " LNK1104	cannot open file ';.obj' "

### ISSUE THREAD

**Issue by karolsenami** [openframeworks/openFrameworks#4724]
Hi, I'm trying to add ofxOpenCv to my project (using the OF Plugin) and I'm getting this error `LNK1104	cannot open file ';.obj' ".`

I'm on `Visual Studio 2015`, and didn't have any problems with addons before. I'm on `openFrameworks 0.9.0`

I've been struggling with it all afternoon and couldn't find a way to avoid it. I tried doing it on my Mac because I wondered if it wasn't adapted to 0.9.0, but it worked perfectly on my Mac.

**Comment by Rhuno** [comment]
I was having the same issue and just got it working. To fix it, you need to adjust the linker dependencies. Right click on your project in the solution explorer and select Properties. Under Linker, click the Input tab. The top option should be Additional Dependencies, select it and click the drop down arrow on the right, select Edit.

The top box probably starts with %3b, delete that. Next, replace all other instances of %3b with a semicolon. I just copied the whole thing into a text editor and did a find/replace to make it simple.

![linker](https://cloud.githubusercontent.com/assets/2680149/12516067/82fde5ca-c0f9-11e5-957b-08c16655216a.JPG)

**Comment by ofZach** [comment]
can you confirm that this issue is specific to using the visual studio plugin?  If you make a new project using the project generator and add opencv, do you have similar issues?   I've opened up an issue here 

https://github.com/openframeworks/visualstudioPlugin/issues/1

since it seems specific to the vs OF plugin....

**Comment by arturoc** [comment]
there was some weird issues with how the visual studio project formats this, i remember having to use some special characters to get it working but it was working for me. i'll take a look

**Comment by Rhuno** [comment]
The only issue I see is the url-encoded semicolons. And correct, this was using the visual studio plugin. Not sure about the project generator, I've only just gotten started with OF.

**Comment by karolsenami** [comment]
Sorry guys I'll have to wait to have my Windows again ! I'll keep you up to date.

**Comment by uirsevla** [comment]
I had the same problem with the latest build from openFrameworks website.
After hours of searching i did  what @Rhuno said and it worked just fine.

**Comment by ZaellixA** [comment]
I had the same problem... been struggling quite some time now to get past it but couldn't.

Your solutions worked perfectly (there were some more errors... like some spaces missing, but I got it solved too). Thanx for the help.

All the best,

Z.

**Comment by jkruseAUT** [comment]
@Rhuno solution worked for me too!

**Comment by randomly123** [comment]
I did the above steps to get rid of this error LNK1104 cannot open file ';.obj' ".
I'm on Visual Studio 2015, and didn't have any problems with addons before. I'm on openFrameworks 0.9.8

Now I get a fresh LINK1104 error.

Which is

'LNK1104 cannot open file C:\OF\addons\ofxOpenCv\src.obj'

And when I look in the above folder, even I cannot find the file src.obj.

How is this file born? How do I get it to be there so that I can run FF on Windows?

**Comment by bigeyesung** [comment]
I got the same problem and it's solved.
Thanks for @Rhuno

**Comment by RogueSheep-nl** [comment]
Problem still exists in 2018 and thankfully the solution still fixes it.
Thanks @Rhuno

**Comment by Bariyard** [comment]
!! work around (of_v0.10.0_vs2017_release)
I use ProjectGenerator to add 'ofxAddons' instead of VS 2017 openframeworks extension
It linked all the addons correctly

Hope this help
