### ISSUE TITLE
ofxGUI support for HDPI screens

### ISSUE THREAD

**Issue by HalfdanJ** [openframeworks/openFrameworks#4727]
On mobile devices that have high pixel density, the ofxGUI is unusable, since the interface elements are super tiny. Would be great if ofxGUI supported some way of scaling the entire interface up by 2X for example.

**Comment by arturoc** [comment]
you can actually set the sizes for everything globally with the functions in https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxGui/src/ofxGui.h

i don't think a scaling factor would do since the default font is the bitmap font which won't scale unless you scale the texture which would look pretty bad

**Comment by roymacdonald** [comment]
I made a PR with this feature, which handles the bitmapfont scaling properly.https://github.com/openframeworks/openFrameworks/pull/6179

**Comment by roymacdonald** [comment]
This got fixed. @HalfdanJ can you close it please?
