### ISSUE TITLE
ofGetWidth() returning incorrect value when High Resolution Capable is enabled in 0.9.1

### ISSUE THREAD

**Issue by braitsch** [openframeworks/openFrameworks#4746]
Seems like something's changed between 0.9.0 & 0.9.1. If I create an empty project in each and enable "high resolution capable" in the plist settings, ofGetWidth() returns different values.

v0.9.1

    ofGetWidth() -> 1024
    ofGetScreenWidth() -> 2880

v0.9.1

    ofGetWidth() -> 2048
    ofGetScreenWidth() -> 2880

One problem this presents is that if I position something based on what ofGetWidth() returns it will potentially be drawn off screen.

Xcode 7.1.1 OSX 10.10.5

**Comment by braitsch** [comment]
Hi Theo,
I just pulled down 0.9.1 and ofGetWidth() is still returning 2x the actual window width when retina is enabled. For example if I run an app fullscreen on my rMBP I get the following:

    ofSetFullscreen(true);
    ofGetWidth() >> 5760
    ofGetScreenWidth() >> 2880

Is this the desired behavior?
If so I think this is kind of confusing as the window isn't actually 5780 pixels wide, it's 2880.

**Comment by ofTheo** [comment]
@braitsch - thats strange on my rMBP gives:

 ofGetWidth() 3840
 ofGetScreenWidth() 3840

My laptop is set to do 1920x1200 so the 3840 is 2x that. 
That would be expected behavior - I don't know why your seeing something different.

**Comment by ofTheo** [comment]
I should note, I am about to start working on a proper retina support for the 0.10.0 release, so things might change a bit.  

The goal being that 1024x768 in retina would give you a window that is the same size as a window that is 1024x768 in a non retina app, but with double the pixels and OF internally handling the pixel to point ratio.

**Comment by arturoc** [comment]
not sure what's the way to work with "retina" but isn't this confusing? if you set the pixel size you probably want the exact size in pixels? there could be other units in which to set the screen size that are resolution independent but setting the size in pixels and getting something else sounds kind of weird. btw i've created a 0.9.2 branch since there was a couple of small bugs that need to be fixed so if you need to fix this please send the PR there instead of master

**Comment by ofTheo** [comment]
@arturoc @braitsch - I've set another issue to discuss the retina stuff. #4789
