### ISSUE TITLE
feature : choosing static/shared linkage of 3rdparty libs

### ISSUE THREAD

**Issue by oxillo** [openframeworks/openFrameworks#4759]
Currently, with MSYS2, you have to copy 50+ dlls in the bin folder to be able to take away your app.
Static linkage of libs into the executable may be a good way to reduce this number. However, I guess some users will prefer to stick with the dlls.

What would be the best option : 
- add an option to make (e.g. make STATIC=True)
- add new tartgets (e.g. make ReleaseStatic, ReleaseShared)

What should be the default : static or shared ?

**Comment by kritzikratzi** [comment]
hey! 

i've been looking into this the past few days. 
here are my findings so far: 

- most dependent libraries have .a files next to the .dll files and they work as expected 
- linking order matters hugely. a wrong static linking order results in a confusing "symbol not found" error. if libA has a dependency on libB then the linking command must be "gcc myFile.o -static libA libB". 
- freeimage must be treated differently, this will require a change in the according apothecary file


so, about freeimage: 

- it comes with its own makefile for mingw (Makefile.mingw), but it doesn't work. 
- the build process requires FREEIMAGE_LIB to be defined for static linking. this must done whenever the FreeImage.h is included, and also during the compilation of freeimage itself 
- mingw has it's own pacman files that patch the build process, see https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-FreeImage
  - instead of using Makefile.mingw they patch and use Makefile.gnu and Makefile.fip 
  - they delete all dependencies (libpng, openjpeg, etc.) included in FreeImage, and replace them with the according packages in mingw
  - a dll build is forced, a .a file is created in the process, but it's not useable

i can pastebin my current thingies if anyone is interested. so far i have a modified version of config.msys2.default.mk that builds a static executable, and a semi working apothecary script (based on the pacman script+patch files). ideally, if i can get this to work fully, those two files could be merged into what OF has so far, to give both options (static and dynamic linking). 

@oxillo are you also still working on this? i'm on irc as often as i can (kritzikratzi)

**Comment by oxillo** [comment]
@kritzikratzi 
I've worked on it and came across the same findings : the MSYS2 freeimage is broken. 
The best option would be to have the MSYS2 package updated. 
However, we cannot rely on it and I was investigating the use of apothecary.
I won't have time to work on it before the weekend; so feel free to submit/share.

**Comment by kritzikratzi** [comment]
hey! 

i think either (fixing the msys2 package or updating the apothecary script) would be viable paths. 
for testing it doesn't make too much of a difference because pacman and apothecary scripts are so similar. searching through google it seems quite a few people would appreciate a working static lib for mingw. 

i'm gonna look into it some more today and tomorrow and then post back here.

**Comment by kritzikratzi** [comment]
i think i managed. could you verify? 

    http://asdfg.me/up/msys-static.zip

1. unzip in some folder where you can make a mess
2. move `config.msys2.default.mk` into libs/openFrameworksCompiled/project/msys2
    this file is still messy, haven't had time to clean up yet. 
3. open a mingw-w32 shell, cd to the unzipped folder
4. run this: 

```
    # the sh script also contains some explanations of what i had to change in freeimage
    source of_msys_freeimage.sh
    download
    prepare
    build
```

If it all worked you can copy the resulting file to `$OF/lib/FreeImage/lib/msys2/i686/libFreeImage.a`

I tested by renaming the msys folder (so dll dependencies break) and running the imageLoaderExample i compiled earlier. works ^^ the resulting binary is 23mb, possibly this can be further reduced with the sections&strip that gcc has. but imho 23mb is already great.

**Comment by oxillo** [comment]
Tested it. The 3dprimitivesExample works perfectly. However some other examples do not compile.The openCv libs are missing. 
I think we should try to mix linking some libs statically (Of core) and the others dynamically (addons).

**Comment by kritzikratzi** [comment]
ooh, my bad. it makes a lot of sense though. they're still marked as "hansi:todo" in the config.mk file :)

**Comment by kritzikratzi** [comment]
@oxillo  i'll have some more time at the end of this week (thursday+friday) to look into this. do you have any new code/insights so i don't do any double work? my next step would be to fix the missing libraries (if the addons are enabled) and do some cleanup to make the static linking a makefile option.

**Comment by oxillo** [comment]
@kritzikratzi I've been investigating if we could have the core libs as static and the addons as dynamic libs. It compiles the OpenCv and Assimp example correctly.
However, it turns out that it doesn't work well as the dynamic libs requires libstdc++6.dll, libdw2_gcc.dll,...

I have a branch [here](https://github.com/oxillo/openFrameworks/tree/static_or_shared) if you want to have a look (It's not clean;-)

**Comment by oxillo** [comment]
Closing this issue as I gave up the idea of having a single exe. The 'copy_dlls' target makes it easy to copy all required dlls next to your binary to take it away...
