### ISSUE TITLE
ofxEditableSvg doesn't check file existence on load

### ISSUE THREAD

**Issue by pdikmann** [openframeworks/openFrameworks#5002]
Hey Folks,

I noticed ofxSvg only checks for the file's existence in a rudimentary way (which leads to a `Poco::XML::SAXParseException`, e.g. a crash). The suspicious line can be found [here](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxSvg/src/ofxSvg.cpp#L11).

I could try fixing this; is the oF repo the right place, or would you rather have this in the [addon's repo](https://github.com/borg/ofxSVG)?

Cheers!

**Comment by hoopless-frood** [comment]
For those Googling "Poco::XML::SAXParseException" who may be new to xCode or ofxSVG, I got this error simply because my .svg files weren't in the correct directory. All such resources should be placed in bin/data within the root folder of your app (debug.app is in the bin so makes sense, right). It doesn't matter whether you import any of them into xCode.

**Comment by bakercp** [comment]
This is an error with an external addon.  You should leave an issue in the addon's repo.  Closing this issue.
