### ISSUE TITLE
Move constructors: noexcept missing -> issue with STL container

### ISSUE THREAD

**Issue by Spacechild1** [openframeworks/openFrameworks#5008]
Hi,

I've just came across the issue that the c++ STL standard containers require the move constructors/assignments in member objects to be 'noexcept' to allow move operations. The compiler might be clever in some cases but this is not guaranteed. 
I checked the oF sources and saw that none of the move constructors and assignements for containers (like ofPixels or ofImage) are noexcept. I made a little test program to show that in a vector of ofPixels, the pixel data is copied for reallocations instead of being moved.

What do you think about adding noexcept? Are there any drawbacks?

See copy_example.cpp for the behaviour of oF containers inside a vector and compare it with move_example.cpp, where I made a class Foo with a noexcept move constructor. (Try to delete 'noexcept' and see how vector will do copies instead.)

Links: 
http://www.codingstandard.com/rule/12-5-4-declare-noexcept-the-move-constructor-and-move-assignment-operator/
http://stackoverflow.com/questions/28627348/noexcept-and-copy-move-contructors

[copy_vs_move.zip](https://github.com/openframeworks/openFrameworks/files/181628/copy_vs_move.zip)

**Comment by arturoc** [comment]
no, just didn't knew about this, we don't throw exceptions anyway so marking the move constructors as no except would be great if that enables classes to be moved into containers. do you want to send a PR?

i think this is something that could go into 0.9.4 since there's been several fixes for move constructors in the patch versions of 0.9.x so if you do send a PR please do it against the 0.9.4 branch and i'll merge it later into master

**Comment by Spacechild1** [comment]
Sure, i'll make a pull request in the next couple of days!

**Comment by Spacechild1** [comment]
A general question: what's the timeline for the OF 0.9.4 release? I keep finding more possible issues and like to propose fixes. Knowing how much time i have, i can concentrate on the more important stuff for the next release.

**Comment by arturoc** [comment]
there's no fixed timeline, if there are critical issues that need to be fixed we'll include them in 0.9.4

if there's some things that need to be fixed with relative urgency but can wait a little we can start a 0.9.5 right away since there's some issues in 0.9.4 that need to be fixed right away, like osx 32bits is not working

in any case open the issues for anything you find and we'll assign them to the correct milestone
