### ISSUE TITLE
OfMesh::load fails to read a ply containing 8bit colour values

### ISSUE THREAD

**Issue by IglooVision** [openframeworks/openFrameworks#5185]
I've just encountered an issue with ofMesh::load. Was trying to load a ply file written using ofMesh::save. Every vertex colour was white (ie [255 255 255]). The vertex colours and UV coordinates in the loaded mesh were wrong.

 The issue seems to be within ofMesh.cpp, in particular the lines: 

> if(colorCompsFound>0){
>
>				if (floatColor){
>					...
>				}
>                               else{
>					ofColor c;
>					sline >> c.r;
>					sline >> c.g;
>					sline >> c.b;
>					if(colorCompsFound>3) sline >> c.a;
>					data.getColors()[currentVertex] = c;
>				}
>			} 

Rather than loading the entirety of sline up to the space, it seems as if c.r etc just get written with the ascii representation of the each character in the first colour column of the ply file. 

A really hacky fix is just to replace the content of the else statement with something like:

> else{
>		ofColor c;
>   	        int holder;
>		sline >>holder;
>		c.r = holder;
>		sline >> holder;
>		c.b = holder;

and so on. 

I'm running openFrameworks 0.9.3 on windows,
Thanks

**Comment by arturoc** [comment]
that looks like a good solution, i think that's how we do it in other places actually. can you send a pull request? thanks!

**Comment by tgfrerer** [comment]
I've just looked into this - and it seems that this has already been fixed a while ago - specifically in this PR <https://github.com/openframeworks/openFrameworks/pull/4944> - also, the latest github version of oF does not have an `ofMesh.cpp` file anymore - because mesh methods have been inlined and moved to `ofMesh.inl`. 

Could it be @IglooVision, that you were using a older version of oF than the current github master? Please let me know if the issue is fixed or still appears if you pull from master...

**Comment by IglooVision** [comment]
Just pulled from the oF master and the issue is fixed in the current version. I was using a version downloaded from the website previously. Sorry!
