### ISSUE TITLE
poco does not compile / apothecary not found

### ISSUE THREAD

**Issue by nanu-c** [openframeworks/openFrameworks#5210]
```
It seems you are running gcc 5 or later, due to incomatible ABI with previous versions
we need to recompile poco. This will take a while
Press any key to continue... ./install_dependencies.sh: line 210: cd: /home/nanu-c/Projekte/openFrameworks/scripts/linux/ubuntu/../../apothecary: No such file or directory
./install_dependencies.sh: line 211: ./apothecary: No such file or directory
chown: cannot access 'build/poco': No such file or directory
chown: cannot access '../../libs/poco': No such file or directory
```

In the branch 0.9.4 it's still working...

**Comment by tgfrerer** [comment]
This could be because when using openFrameworks from `git/master`, apothecary has been (re)moved into its own repository, and the linux/ubuntu script might still expect it at the old location within the openFrameworks directory.

As a quick fix, you could clone apothecary from https://github.com/openframeworks/apothecary and run the poco compilation script manually: as in:
    
	cd $YOUR_DEV_DIR$
	git clone https://github.com/openframeworks/apothecary apothecary
	cd apothecary
	./apothecary update poco

Then, you will most likely have to copy/replace the build results into the `openframeworks/libs/poco` directory. The build results will be in the root directory of the apothecary repository.

**Comment by arturoc** [comment]
or just clone the apothecary repo in the place where it used to be, scripts/apothecary and rerun the install_dependencies script again which should do the right thing.

you can also find the latest libraries, including gcc5 compatible ones here: http://ci.openframeworks.cc/libs/ just download the tarball and uncompress it in you libs folder

**Comment by nanu-c** [comment]
okey
then it should be included in  openFrameworks/.gitmodules not?

**Comment by nanu-c** [comment]
Thats working now and thanks for the ci.openframeworks

**Comment by arturoc** [comment]
yes it should probably be in submodules but since the final location is also going to change we haven't added it yet. if you want to send a PR with the current correct location, we can merge that by now and change it to the definitive location later

**Comment by nanu-c** [comment]
Putting it in the right path is not so easy because when i pull it the executable is in ./scripts/apothecary/apothecary/apothecary
That's one apothecary to much and i have to change it in every script to get them work. So where could be the final destination?... Or just a note in readme.md until there is a final decision?

**Comment by arturoc** [comment]
perhaps just change the script to use the new path too

**Comment by Paul92** [comment]
The stable branch is fine though
