### ISSUE TITLE
feature->ofParameter save/load

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#5357]
Hi, saving and loading ofParameters without having to use ofxGui is super handy.
Actually is quite easy to achieve and it looks like it wont be breaking anything.
We just need to move the save/load related methods from ofxBaseGui into ofAbstractParameter. :)
Look at this commit.
https://github.com/roymacdonald/openFrameworks/commit/5d9e21f9981d29212eb5fc372ce5876b46bd0a01

Should I PR?

Cheers!

**Comment by arturoc** [comment]
mmh, the idea is that instead of having parameter load / save itself the ofSerialize/Deserialize functions take care of that and also allow for more flexibility cause you can use whatever serializer you want.

```
ofJson json;
ofSerialize(json, parameters);
ofSaveJson(json, "settings.json");
```

or

```
ofXml xml;
ofSerialize(xml, parameters);
xml.save("settings.xml");
```

does the same and it's not much more verbose. not completely opposed to having this as save/load methods in ofParameter if others think it's useful but would like to keep ofParameter/Group as simple as possible given that it's already really complex

**Comment by roymacdonald** [comment]
right, but it is still easier to have one line rather than 3. ;)
I just though that it could be handy and it only meant moving code from one place to another.
With the code I committed, which was taken from ofxBaseGui, the saveToFile/loadFromFile will figure out which serializer to use based on the file extension, so it is still flexible to use whichever serializer.
Maybe a cleaner and still handy thing would be to have a helper function? like `ofSaveParameter(string path, ofAbstractParameter& param)`
which would figure out which serializer to use just like ofxBaseGui does.
What do you think? 
I can code it right now and PR.

best!
