### ISSUE TITLE
Child node traversal in ofNode?

### ISSUE THREAD

**Issue by AustinSlominski** [openframeworks/openFrameworks#5428]
Currently there are no methods available to access child nodes while using ofNode. I've played around with accessing the set using the following snippets, but I'm running into issues actually utilizing it this way. Why hasn't a child getter been implemented yet? Is there a preferred method of doing this that I've missed?

In ofNode:
```
//----------------------------------------
std::set<ofNode*> ofNode::getChildren() const {
	return children;
}
```
In ofApp
```
std::set<ofNode*> t_children = branches[0]->getChildren();
for (set<ofNode*>::iterator i = t_children.begin(); i != t_children.end(); i++) {
    auto element = *i;
}
```

**Comment by arturoc** [comment]
ofNode is not meant to be a class for storing or navigating a hierarchy of objects just to store the transformations of an object and create a hierarchy of *transformations* so you can recover the full model matrix of an object that is somehow related to a parent object and "moves" with it in order to implement that functionality the only relevant information is the parent of each object not it's children.

we only keep the children in the parent to be able to destroy things in the correct order but are not publicly accessible because that collection has been recently added and could even go away if we find a better way of managing memory.

i think what you want is some kind of tree data structure but ofNode is not meant to be that:

https://en.wikipedia.org/wiki/Tree_%28data_structure%29
http://tree.phi-sci.com/documentation.html
https://www.codeproject.com/articles/1734/tree-data-class-for-c
