### ISSUE TITLE
ofLight crashes on destruction w/ programmable renderer.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#5522]
While I realize programmable renderer doesn't support old-fashioned lights / materials, `ofLight` is currently crashing on destruction when using the programmable renderer.

On `master` branch, OSX, xcode, etc.

Steps to reproduce:

```c++
#include "ofMain.h"
#include "ofApp.h"

int main( ){
    ofGLWindowSettings settings;
    settings.setGLVersion(3,2);
    ofCreateWindow(settings);
    return ofRunApp(std::make_shared<ofApp>());
}
```
```c++
#pragma once

#include "ofMain.h"

class ofApp : public ofBaseApp{

public:
    void setup(){
        ofSetLogLevel(OF_LOG_VERBOSE);
        light.setPosition(0, 0, 500);
    }
    void update() { }
    void draw() {
        light.enable();
        light.disable();
    }

    ofLight light;

};
```

![ofapprunner_cpp_and_main_cpp](https://cloud.githubusercontent.com/assets/300484/24784736/33b720a4-1b1a-11e7-88c4-f157e09a79d0.png)

**Comment by tgfrerer** [comment]
I've tracked this down to `ofLight` calling the renderer when `ofLight` gets destroyed. 

The bad access is due to calls from [ofLight#L80-84](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/gl/ofLight.cpp#L80-L84)

On application teardown, it can't be guaranteed that a renderer is still alive, and if the renderer has been destroyed before an `ofLight` this would lead to `BAD_ACCESS`, as a destroyed renderer can't be de-referenced.

It seems these renderer calls might be better placed inside the renderer itself, rather than in the destructor of ofLight, as they change state in the renderer (which should own the lights), and don't touch de-allocation/destruction per se. Perhaps we shouldn't need these calls in the first place, as ofLight doesn't seem to be an object which is allocated/deallocated, rather than enabled/disabled.

I'd suggest we remove global calls to the renderer from `ofLight`'s destructor.
