### ISSUE TITLE
Cannot build 0.9.8 on Raspbian stretch - (fix for master branch)

### ISSUE THREAD

**Issue by PanderMusubi** [openframeworks/openFrameworks#5741]
Running `./install_dependencies.sh` for openFrameworks 0.9.8 on Rasbian stretch (August 2017) on Raspberry Pi 2 results in:

    ...
    ...
    ...
    It seems you are running gcc 5 or later, due to incomatible ABI with previous versions
    we need to recompile poco. This will take a while
    Press any key to continue... 
     ----- poco -----
     
      Downloading "poco"
     
     ... skipping, src dir already exists
     
      Preparing "poco"
     
      Skipping "openssl": downloadFormula not needed for type "linuxarmv7l"
      Skipping "openssl": prepareFormula not needed for type "linuxarmv7l"
      Skipping "openssl": buildFormula not needed for type "linuxarmv7l"
      Skipping "openssl": copyFormula not needed for type "linuxarmv7l"
     
      Building "poco"
    
    Configured for Linux
    make -C /home/pi/openFrameworks/scripts/apothecary/build/poco/Foundation
    ...
    ...
    ...
    ranlib /home/pi/openFrameworks/scripts/apothecary/build/poco/lib/Linux/armv7l/libPocoMongoDBd.a
    ** Building library (release) /home/pi/openFrameworks/scripts/apothecary/build/poco/lib/Linux/armv7l    /libPocoMongoDB.a
    ar -cr /home/pi/openFrameworks/scripts/apothecary/build/poco/lib/Linux/armv7l/libPocoMongoDB.a /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Array.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Binary.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Connection.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Cursor.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/DeleteRequest.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Database.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Document.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Element.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/GetMoreRequest.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/InsertRequest.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/JavaScriptCode.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/KillCursorsRequest.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/Message.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/MessageHeader.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/ObjectId.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/QueryRequest.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/RegularExpression.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/ReplicaSet.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/RequestMessage.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/ResponseMessage.o /home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB/obj/Linux/armv7l/release_static/UpdateRequest.o
    ranlib /home/pi/openFrameworks/scripts/apothecary/build/poco/lib/Linux/armv7l/libPocoMongoDB.a
    make[1]: Leaving directory '/home/pi/openFrameworks/scripts/apothecary/build/poco/MongoDB'
    
     ^ Received error ^

Extra info on what is installed for `gcc` by default:

    $ dpkg -l|grep gcc|awk '{print $2}'
    gcc
    gcc-4.6-base:armhf
    gcc-4.7-base:armhf
    gcc-4.8-base:armhf
    gcc-4.9-base:armhf
    gcc-5-base:armhf
    gcc-6
    gcc-6-base:armhf
    libgcc-6-dev:armhf
    libgcc1:armhf

What is the workaround for this? Or can this get fixed in a new download for openFrameworks?

See also (but didn't help me fix it):
* https://forum.openframeworks.cc/t/compiling-of-in-raspbian-stretch/27562
* https://forum.openframeworks.cc/t/solved-problems-because-of-gcc-6-poco/26479/2
* https://forum.openframeworks.cc/t/received-error-when-install-dependencies/25226

**Comment by arturoc** [comment]
openframeworks 0.9.8 is not compatible anymore with latest debian version can you try if the nightly builds work for you?

**Comment by PanderMusubi** [comment]
Yes, I will try. Do you have a url so I use exactly the one you expect me to use?

**Comment by jvcleave** [comment]
this one should be fine
http://ci.openframeworks.cc/versions/nightly/of_v20170714_linuxarmv6l_nightly.tar.gz

**Comment by PanderMusubi** [comment]
Yes, that one works. Hope there will be a new official release with that fix as I have seen many people struggle with this.

**Comment by PanderMusubi** [comment]
This error shows up with this nightly on Raspbian stretch:

    ~/of_v20170714_linuxarmv6l_release/apps/myApps/emptyExample $ make RunRelease
    HOST_OS=Linux
    checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libcurl glfw3 rtaudio gtk+-3.0 
    with PKG_CONFIG_LIBDIR=
    [notice ] ofAppEGLWindow: setupRPiNativeWindow(): screenRect: 800x600
    [notice ] ofAppEGLWindow: setupRPiNativeWindow(): windowRect: 800x600
    [notice ] ofAppEGLWindow: createSurface(): setting up EGL Display
    [notice ] ofAppEGLWindow: createSurface(): EGL Display correctly set 0x85d480
    libEGL warning: DRI3: xcb_connect failed
    libEGL warning: DRI2: xcb_connect failed
    libEGL warning: DRI2: xcb_connect failed
    [ error ] ofAppEGLWindow: createSurface(): eglInitialize returned EGL_FALSE
    [notice ] ofAppEGLWindow: setupPeripherals(): peripheral setup complete
    [notice ] ofAppEGLWindow: setupNativeUDev(): created udev object
    [notice ] ofAppEGLWindow: setupMouse(): mouse_fd=5 devicePath=/dev/input/event0
    [notice ] ofAppEGLWindow: setupMouse(): mouse device name = Logitech HID compliant keyboard
    [notice ] ofAppEGLWindow: setupKeyboard(): keyboard_fd=6 devicePath=/dev/input/by-path/platform-3f980000.usb-usb-0:1.4:1.0-event-kbd
    [notice ] ofAppEGLWindow: setupKeyboard(): keyboard device name = Logitech HID compliant keyboard
    [notice ] ofAppEGLWindow: setupPeripherals(): native event setup complete
    [notice ] ofAppEGLWindow: display(): eglSwapBuffers failed: 
    [notice ] ofAppEGLWindow: display(): eglSwapBuffers failed: 
    [notice ] ofAppEGLWindow: display(): eglSwapBuffers failed: 
    [notice ] ofAppEGLWindow: display(): eglSwapBuffers failed: 
    [notice ] ofAppEGLWindow: display(): eglSwapBuffers failed: 
    ...

**Comment by PanderMusubi** [comment]
these are created automatically

    /dev/input# tree
    .
    ├── by-id
    │   ├── usb-Logitech_HID_compliant_keyboard-event-if01 -> ../event1
    │   └── usb-Logitech_HID_compliant_keyboard-event-kbd -> ../event0
    ├── by-path
    │   ├── platform-3f980000.usb-usb-0:1.4:1.0-event-kbd -> ../event0
    │   └── platform-3f980000.usb-usb-0:1.4:1.1-event -> ../event1
    ├── event0
    ├── event1
    └── mice

**Comment by PanderMusubi** [comment]
That nightly gave exactly the same errors :-(

**Comment by hlolli** [comment]
Also had this error on lates linux releast on Fedora 26, end of the poco recompilation
```
ranlib /home/hlolli/openFrameworks/scripts/apothecary/build/poco/lib/Linux/x86_64/libPocoNet.a
make[1]: Leaving directory '/home/hlolli/openFrameworks/scripts/apothecary/build/poco/Net'

 ^ Received error ^
```

**Comment by julien** [comment]
Using the nightly for gcc 6, it compiles on debian 9.2.1

**Comment by PanderMusubi** [comment]
Does a build of that version with latest Raspbian runs the demo app properly on a Raspberry Pi 2 or 3?

**Comment by jonassorgenfrei** [comment]
Has anyone solved the Problem yet? im getting exact the same error when trying to run.

**Comment by bakercp** [comment]
Yes.  I'll post the fix on the forum and here when I get home.

Basically change this:

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L123-L125

to this (remove `GLESv1_CM` since it just pointed to `GLESv2` anyway)

```
PLATFORM_LIBRARIES += brcmGLESv2
PLATFORM_LIBRARIES += brcmEGL
```

Then in raspi-config > advanced > choose the legacy GL driver.

**Comment by bakercp** [comment]
I'll submit a PR soon.

**Comment by bakercp** [comment]
Here is a further discussion for compiling oF master in raspbian stretch.

https://forum.openframeworks.cc/t/compiling-of-in-raspbian-stretch/27562/12

**Comment by arturoc** [comment]
This is fixed now

**Comment by neilmendoza** [comment]
PG doesn't build on master branch or nightly because of a Poco linking error (errors below). If I'm on the master branch and I try to use apothecary to fix it, I get "./apothecary: line 1238: TOOLCHAIN_PREFIX: unbound variable". Next up compile Poco from source I guess.

**Apothecary error**
./apothecary -tlinuxarmv6l update poco
OF: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../
APOTHECARY: /home/pi/openFrameworks/scripts/apothecary/apothecary
FORMULAS: /home/pi/openFrameworks/scripts/apothecary/apothecary/formulas
BUILD: /home/pi/openFrameworks/scripts/apothecary/apothecary/build
LIBS_DIR: /home/pi/openFrameworks/scripts/apothecary/apothecary/../
ADDONS: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../addons
REL_ADDONS_DIR: /home/pi/openFrameworks/scripts/apothecary/apothecary/../../../addons
./apothecary: line 1238: TOOLCHAIN_PREFIX: unbound variable

**PG compile error**
obj/linuxarmv6l/Release/src/main.o: In function `main':
main.cpp:(.text.startup+0xe64): undefined reference to `Poco::Path::current[abi:cxx11]()'
main.cpp:(.text.startup+0x1018): undefined reference to `Poco::Path::current[abi:cxx11]()'
main.cpp:(.text.startup+0x1034): undefined reference to `Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x105c): undefined reference to `Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x1078): undefined reference to `Poco::Path::toString[abi:cxx11]() const'
main.cpp:(.text.startup+0x10bc): undefined reference to `Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x10e0): undefined reference to `Poco::Path::toString[abi:cxx11]() const'
main.cpp:(.text.startup+0x18e8): undefined reference to `Poco::Path::Path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text.startup+0x1908): undefined reference to `Poco::Path::toString[abi:cxx11]() const'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/utils/Utils.o: In function `getOFRelPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Utils.cpp:(.text+0x1268): undefined reference to `Poco::Path::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Utils.cpp:(.text+0x1288): undefined reference to `Poco::Path::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Utils.cpp:(.text+0x12c8): undefined reference to `Poco::Path::toString[abi:cxx11]() const'
Utils.cpp:(.text+0x12d4): undefined reference to `Poco::Path::toString[abi:cxx11]() const'
Utils.cpp:(.text+0x143c): undefined reference to `Poco::Path::directory[abi:cxx11](int) const'
Utils.cpp:(.text+0x16e4): undefined reference to `Poco::Path::directory[abi:cxx11](int) const'
Utils.cpp:(.text+0x16f4): undefined reference to `Poco::Path::directory[abi:cxx11](int) const'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/utils/Utils.o: In function `generateUUID(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
Utils.cpp:(.text+0x73ac): undefined reference to `Poco::DigestEngine::digestToHex[abi:cxx11](std::vector<unsigned char, std::allocator<unsigned char> > const&)'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o: In function `ofAddon::exclude(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
ofAddon.cpp:(.text+0xa90): undefined reference to `Poco::RegularExpression::RegularExpression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
ofAddon.cpp:(.text+0xbbc): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0xca4): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0xd90): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0xe7c): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0x120c): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o:ofAddon.cpp:(.text+0x13d0): more undefined references to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const' follow
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o: In function `ofAddon::exclude(std::vector<LibraryBinary, std::allocator<LibraryBinary> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
ofAddon.cpp:(.text+0x1a3c): undefined reference to `Poco::RegularExpression::RegularExpression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
ofAddon.cpp:(.text+0x1b68): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0x1c50): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0x1d3c): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0x1e28): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
ofAddon.cpp:(.text+0x21dc): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o:ofAddon.cpp:(.text+0x24bc): more undefined references to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) const' follow
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o: In function `ofAddon::addReplaceStringVector(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
ofAddon.cpp:(.text+0x3144): undefined reference to `Poco::RegularExpression::RegularExpression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
ofAddon.cpp:(.text+0x3218): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, Poco::RegularExpression::Match&, int) const'
/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine/obj/linuxarmv6l/Release/addons/ofxProjectGenerator/src/addons/ofAddon.o: In function `ofAddon::addReplaceStringVector(std::vector<LibraryBinary, std::allocator<LibraryBinary> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
ofAddon.cpp:(.text+0x3c7c): undefined reference to `Poco::RegularExpression::RegularExpression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool)'
ofAddon.cpp:(.text+0x3d54): undefined reference to `Poco::RegularExpression::match(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, Poco::RegularExpression::Match&, int) const'
collect2: error: ld returned 1 exit status
/home/pi/of_v20180402_linuxarmv6l_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:403: recipe for target 'bin/projectGenerator' failed
make[1]: *** [bin/projectGenerator] Error 1
make[1]: Leaving directory '/home/pi/of_v20180402_linuxarmv6l_release/apps/projectGenerator/commandLine'
/home/pi/of_v20180402_linuxarmv6l_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2

**Comment by PanderMusubi** [comment]
Please, open this issue again.

**Comment by arturoc** [comment]
i believe this should be fixed now, OF won't be compatible with jessie after today.

let me know if it's still a problem
