### ISSUE TITLE
Issue in cloning 

### ISSUE THREAD

**Issue by UsamaIslam** [openframeworks/openFrameworks#5810]
Unable to download or clone 
![screenshot_1](https://user-images.githubusercontent.com/24495238/32992028-831f1c1e-cd67-11e7-8dc6-782aee8b7212.png)

**Comment by Paul92** [comment]
This is not a problem related to the ```openFrameworks``` repository, but rather with your internet connection/git config.

My suggestions are:
- Check for a stable connection for a long time. OF is quite a large repo, and it takes a while to download. If your internet connection is not stable during this time, you might get that error.
- Make sure you have git configured properly. See https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup, especially the ```Identity``` section
- Try cloning the official repo rather than your fork

**Comment by armadillu** [comment]
see https://github.com/openframeworks/openFrameworks/issues/5562
