### ISSUE TITLE
templated code needs to be more readable

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#582]
ofImage_<T> should be ofBaseImage<Type>, likewise with ofPixels_<T>

in general, X_<T> style classes should be BaseX<Type>

templated functions that are just sitting around should also have descriptive template names.

it's important for this to happen before 007, otherwise code will be written against ofImage\_&lt;T&gt; etc.

**Comment by arturoc** [comment]
This hasn't been a big issue since we implemented it, the base cases are easy to use through the typedefs and i haven't seen anyone having any problem with it in the 4 years we've been using the pattern. The _ at the end is also way easier to parse than any special naming convention for things like documentation so it allows to make the docs cleaner. i'm going to close it then but feel free to comment if someone still thinks it should be done in a different way
