### ISSUE TITLE
ofxFaceRecognizer example project compiling problem (from ofxOpenCV2461)

### ISSUE THREAD

**Issue by alana92** [openframeworks/openFrameworks#5850]
I'm running the example project (from the ofxFaceRecognizer addon folder) in the of_v0.9.8_osx_release (downloaded from the of website) in xcode (v. 9.1) with opencv (v. 3.4.0 ) installed on macOS High Sierra and getting the following compiling errors:

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvImage.h:82:29: Virtual function 'getPixels' has a different return type ('unsigned char *') than the function it overrides (which has return type 'ofPixels_<unsigned char> &')`

From code:

` virtual unsigned char*  getPixels();`

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvContourFinder.h:58:29: Field type 'ofxCvGrayscaleImage' is an abstract class`

From code:
```
 protected:

    int  _width;
    int  _height;
    ofxCvGrayscaleImage     inputCopy;
    CvMemStorage*           contour_storage;
    CvMemStorage*           storage;
    CvMoments*              myMoments;
    vector<CvSeq*>          cvSeqBlobs;  //these will become blobs
    
    ofPoint  anchor;
    bool  bAnchorIsPct;      

    virtual void reset();
```

Error:

`/Applications/of_v0.9.8_osx_release/addons/ofxOpenCV2461/src/ofxCvHaarFinder.h:51:22: Field type 'ofxCvGrayscaleImage' is an abstract class`

From code:

```
protected:
	CvHaarClassifierCascade* cascade;
	string haarFile;
	ofxCvGrayscaleImage img;
	float scaleHaar;
	unsigned neighbors;
```

Issue also logged on the ofxopencv2461 github repository, see: https://github.com/pkmital/ofxOpenCV2461/issues/1

Issue also logged on the ofxFaceRecognizer github repository, see: 
https://github.com/antimodular/ofxFaceRecognizer/issues/2

Please advise

**Comment by arturoc** [comment]
Hi, this doesn't seem an openframeworks issue but something wrong with the specific addons that you mention. probably that they are not maintained and don't work with latest versions of openFrameworks. i would try using the ofxOpenCv addon included in openframeworks itself rather than the version you are trying to use.

In any case since this is not an issue i'm going to close this. If you don't get an answer from the addon authors try posting your problem in the OF forum instead
