### ISSUE TITLE
ofDirectory diff results on diff mac osx versions

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#5852]
I don't know if this is a bug or a feature but because apple introduced apfs 

https://en.wikipedia.org/wiki/Apple_File_System

ofDirectory listDir gives different results in terms of order across different osx versions.  This has led to some confusion with students where image sequences play out of order on newest OSX, etc. 

obviously ofDirectory::sort fixes things so we get the same results but wonder if we maybe shouldn't just sort on listDir to make things more normalized?  

somewhat related (re: sorting)   https://github.com/openframeworks/openFrameworks/issues/2578

**Comment by arturoc** [comment]
This has always worked like this in linux, that's why we introduced the sort method. I'm almost sure it's even working with natural sorting instead of alphabetic already too.

I think we never did it by default cause it might be redundant in some platforms and perhaps be a performance problem in some cases if you try to read an extra large directory. I guess it would be a very rare case though.

All the examples regarding reading files for image sequences.... include a call to sort after listDir because of this.

**Comment by ofZach** [comment]
ok !  I will just add sort to my examples, I had been neglecting to include it since things just work on osx but they don't anymore...
