### ISSUE TITLE
.gitignore for examples is missing PG-generated (linux) makefiles

### ISSUE THREAD

**Issue by drewLough** [openframeworks/openFrameworks#6021]
Currently, 170+ untracked files show up in git status when projectGenerator builds the examples. 
they are of kind `addons.make`, `Makefile`, and `config.make`. The latter two are tied to a !-flagged entry in examples/ .gitignore, and the addons.make files are what PG creates for Linux (I assume).
### in examples/.gitignore starting at line 43:
```
# operating system
#########################

# Linux
/*/*/Makefile
/*/*/config.make
# Leave Android files in until project generation works
!/android/*/Makefile
!/android/*/config.make
```
 looks to be missing
`/*/*/addons.make  `

are the android makefiles still supposed to be !-flagged? 
This is on Fedora 28. ` master` branch.

**Comment by 2bbb** [comment]
i'm encountering same problem on Xcode with updating examples with PG.
every example (doesn't need addons) will given empty `addons.make` and android-examples will given new `Makefile` and `config.make`.

on master branch too.

**Comment by arturoc** [comment]
android examples shouldn't have a makefile or config.make anynore. some times when deleting stuff from git it remains in the directories. try deleting the examples/android folder and checking it out again.

as for the addons.make files we need to not ignore those since the project generator needs them to generate the projects when creating the downloadable.

what we could do is commit the empty addons.make files for projects that don't have addons so they don't show up as new files in the git status
