### ISSUE TITLE
Low framerate

### ISSUE THREAD

**Issue by Sert42** [openframeworks/openFrameworks#6049]
My project sufferes from a low framerate issue, but I couldn't find the problem. So I used the emptyExample project and found out when I again draw the framerate I get ~30 fps. How can an empty project be so slow? I have tried both Debug and Release.
Memory usage: 136mb, CPU usage: 4.2%, GPU usage: ~22%

**Comment by hamoid** [comment]
Hi! What OS? Anything special about the hardware? Other programs run at higher frame rate?

**Comment by Sert42** [comment]
Hey, the specs are:
Windows 10
Intel Core i7 2.60Ghz
8GB RAM
64-bit
This work laptop has only the Intel(R) HD Graphics 520 GPU, my personal laptop has GeForce GT 650M. I have only Visual Studio 17 running.

**Comment by farkasgzoltan** [comment]
ofSetFrameRate(60);
ofSetVerticalSync(true);
or
ofSetVerticalSync(false);

There are other things to be faster...
these are specific because of...
GLUT, GLFW gl2, GLFW gl3 or ofAppNoWindow its own render engine etc....

Ubuntu 64bit
Intel(R) Core(TM)2 Duo CPU     P9700  @ 2.80GHz 2GB  Nvidia nvs160m 256mb
1280x720
maximum fps we could reach complete gui demo
GLUT opengl2                                       220FPS
GLFW opengl2	                              58FPS
GLFW opengl3	                              35FPS    
opengl3 ofGLProgrammableRenderer  37FPS
opengl2                                                 39FPS
my renderer glfw opengl2                     85FPS

GLUT It was no small surprise :)

good looks ofAppGLFWWindow and its own glfw window with a difference of 17fps
mine is far less knowledgeable than ofAppGLFWWindow

opengl3 smaller fps. I think it's old video card hardware.
