### ISSUE TITLE
Wrong spacing of ofTrueTypeFont

### ISSUE THREAD

**Issue by hiroMTB** [openframeworks/openFrameworks#6066]
ofTrueTypeFont seems like handling letterSpacing in wrong way.
This is problematic when we set big letterSpacing value like more than 2.0.
Here is comparison between oF(top half) and Adobe Illustrator(bottom half).
Please click an image below and check the difference.

![2018-07-03 at 9 09 34 pm](https://user-images.githubusercontent.com/193280/42239944-e99228ce-7f05-11e8-87a3-296541ffda38.png)

Here is test code of oF.
```
#include "ofApp.h"

void ofApp::setup(){
    ofBackground(255);
    ofTrueTypeFont::setGlobalDpi(72);
    font.load("frabk.ttf", 20, true, true);;
    font.setLetterSpacing(4);
}

void ofApp::draw(){
    ofSetColor(0);
    font.drawString("HELLO I AM a BIG LETTERSPACING STRING!!", 20, 250);
    font.drawString("Hello I am a big letterspacing string!!", 20, 330);
}
```

**Comment by chriship** [comment]
Reading here: https://www.freetype.org/freetype2/docs/tutorial/step2.html 

It seems fine with monospaced fonts. I presume it's because they all have the same 'advance' value. Oddly, I don't see any mention of 'bearingX' being used in ofTrueTypeFont.cpp.

It looks to me like Illustrator is using the same 'bearingX' and/or 'advance' value for each character but when I analyse various fonts they have different values for these.

**Comment by hiroMTB** [comment]
Nice idea providing compatibility!

**Comment by hiroMTB** [comment]
thanks!
