### ISSUE TITLE
High Resolution Capable not working correctly

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#6068]
First of all, when I set `High Resolution Capable` to `YES` in `openFrameworks-Info.plist` file, the window shows up in half size than the size it was when `High Resolution Capable` was set to `NO` and this is the problem I can live with.

However, when I set the window width to be larger than my Mac Book Pro's non-retina screen resolution(1440x900), suddenly the width of the window gets as big as the screen. (the window width becomes 2 times bigger when I change width to 1441 from 1440)

I assume there's a code that compares the window dimensions with the screen dimensions so the window won't get bigger than the screen size. But I think one made a mistake by using the non-retina resolution instead of retina.

The problem only happens with OF 0.10.0 and it works fine with OF 0.9.8.
Can any Mac users confirm this issue? How can we fix this?

**Comment by luisArandas** [comment]
Any updates on this?
Best, Luis

**Comment by kylemcdonald** [comment]
it looks like this might be related to a previous issue https://github.com/openframeworks/openFrameworks/issues/6032

i think it's also related to this bug that happens when the high resolution switch is turned on:

```cpp
#include "ofMain.h"
class ofApp : public ofBaseApp{
public:
    void setup() {
        ofBackground(0);
    }
    void update() {
    }
    void draw() {
        ofSetColor(255);
        ofDrawRectangle(0,0,100,100);
    }
};

int main() {
    ofSetupOpenGL(1920, 1080, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

expected behavior: draw rectangle at top left corner. actual behavior:

<img width="1280" alt="Screen Shot 2019-09-07 at 11 25 51 AM" src="https://user-images.githubusercontent.com/157106/64468856-7a483c80-d164-11e9-9b14-b51ea65bc762.png">

**Comment by jivido** [comment]
Hi,
I can't replicate the 1440-1441 bug (of_v0.11.0). 
But I can confirm the bug that @kylemcdonald mentions, on of_v0.11.0 on OSX (that's why I'm here).
However, it's gone on the nightly build, so I guess this issue can be closed (reason of this comment)?
Probably this PR is the fix: of_v20201026_osx_release
