### ISSUE TITLE
Possible memory leak in ofxGui

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6145]
I just noticed that in ofxGuiGroup all the `add(ofParameter<T> & parameter)` functions call new as you can see [here](https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxGui/src/ofxGuiGroup.cpp#L178-L229), thus creating the gui object needed. but these newly created objects never get deleted even after the `ofGuiGroup` is destroyed. In a lot of cases this might not be a problem as a lot of times the the `ofxGuiGroup` or `ofxPanel` object exists for the whole runtime of the app, but in scenarios where the gui is created and destroyed dynamically this is a problem.

The following code is a proof of this.
````cpp
#include "ofMain.h"
#include "ofxGui.h"

class ofApp : public ofBaseApp
{
public:
	//----------------------------------------------------------------
	void setup(){		
		gui = new ofxPanel();
		gui->setup();
		gui->add(param.set("param", 0, 0, 255));
		sliderPtr = &(gui->getFloatSlider("param"));
		
	};
	//----------------------------------------------------------------
	void draw(){
		
		ofBackground(param, 0, 0);
		
		if (displayGui){
			if(gui){
				gui->draw();
			}else if (sliderPtr){
				sliderPtr->draw();
			}
		}
		
		stringstream ss;
		
		if(sliderPtr){
			ss << "sliderPtr  " << sliderPtr << endl;	
		}else{
			ss << "sliderPtr  is null" << endl;
		}
		if(gui){
			ss << "gui  " << gui << endl;	
		}else{
			ss << "gui is null" << endl;
		}
		ofDrawBitmapStringHighlight(ss.str(), 20, ofGetHeight() - 50);
		
	};
	//----------------------------------------------------------------
	void keyPressed(int key)
	{
		if(key == ' '){
			displayGui = !displayGui;
		}else if(key == 'd'){
			delete gui;
			gui = nullptr;
		}
	}
	//----------------------------------------------------------------
	ofxPanel* gui= nullptr;
	ofParameter<float> param;
	ofxFloatSlider* sliderPtr = nullptr;
	bool displayGui = true;
};

int main( )
{
	ofSetupOpenGL(400,200,OF_WINDOW);
	ofRunApp(new ofApp());
}

````

Maybe moving all the pointers used into smart pointer can be a good idea. What do you think @arturoc  @bakercp @ofZach ?

**Comment by arturoc** [comment]
yeah that should be a unique pointer

**Comment by roymacdonald** [comment]
@arturoc sure. but there are some functions that return raw pointers to the gui elements, thus shouldn't these be stored as `shared_ptr `instead of `unique_ptr`, and return the `shared_ptr`? Wouldn't it be a bad practice to return the raw pointer from the  shared or unique pointer? Also `ofxBaseGui` stores a pointer to its parent, which should be a `weak_ptr`, so as such it also makes sense to use a `shared_ptr`. What do you think?

**Comment by igiso** [comment]
nice find roy, I remember noticing leaking as well


Regarding 
unique_ptr and shared_ptr

if you are going to return a raw pointer it doesn't matter since both can return it:
https://en.cppreference.com/w/cpp/memory/unique_ptr/get 

so it's better if you use unique

here is the thing,

shared_ptr does ref counting, 
a gui is something that might use a lot of items
so it might have a slight or significant overhead

also if you return a shared_ptr instead of a raw you will increase the refcount
https://en.cppreference.com/w/cpp/memory/shared_ptr/use_count

so what it would happen in our case if we returned a shared_ptr instead of a weak_ptr or a raw

it would still leak, since auto sliderPtr would be in scope till the end of the program.
and you would also create a scenario where the user could do something stupid and create double allocations double release .. etc


it's one of those situations where the lesser evil must prevail

unique_ptr is "better" if you are going to return naked pointers 
it will do the release when call clear()

returning only shared pointers or weakptr would make the user code radically different, more verbose and less user friendly and still leak in some cases


The easiest solution will be to make a tiny change for now

void ofxGuiGroup::clear(){
    for (int i=0; i<collection.size(); i++) {
        delete collection[i];
    }
	collection.clear();
	parameters.clear();
	b.height = header + spacing + spacingNextElement;
	sizeChangedCB();
}

and 

ofxPanel::~ofxPanel(){
    ofxGuiGroup::clear();
}

and:

 if(key == 'd'){
            sliderPtr= nullptr;
            displayGui=false;

in order to avoid calling a released pointer in draw

**Comment by roymacdonald** [comment]
Hi @igiso 
Thanks for your insight. Really helpful. 
I understand the problem with having the ref counting of the shared_ptr and its possible overhead. Although I think that the problem is actually another.
Currently you can make an instance of an ofxFloatSlider (or any other of the ofxGui widgets) and add it to an ofxPanel (or ofxGuiGroup), which will store the widget pointer. So far so go, no need to dealocate pointers.
Then, when you use ofParameters and add these to an ofxPanel, it will create a new ofxGui widget, according to the filetype of it of course, and store its pointer. This new widget is created using the new keyword and stored in the same place as all the other pointers. Here then is the problem. If it delete is called on all these pointers you would delete pointers that are not supposed to. So I think that what would be the right way for approaching this would be to have in ofxGuiGroup two vectors holding the pointers, one of unique_ptr, which are the ones created when using ofParameters and another that that stores the raw pointers, storing the pointers of the ofxGui widgets created elsewhere. I think that this would not add much code and it would not make a any difference to the API. What do you think. I think I have this implementation already made. I'll try to find it and push.

**Comment by igiso** [comment]
yeah, you are correct

**Comment by dimitre** [comment]
@roymacdonald is this one closed by your PR?

**Comment by roymacdonald** [comment]
@dimitre yes it is. closing this issue
