### ISSUE TITLE
Xcode 10 - won't build OF iOS examples for simulators

### ISSUE THREAD

**Issue by ronherrema** [openframeworks/openFrameworks#6192]
I can build and run the iOS examples (and my own projects) on devices, but not on simulators. I am working on High Sierra (10.13.6), Xcode 10.0, and OF 0.10.1. The error message I get is ‘linker command failed with exit code 1’. When I check the Build Report I find this message:

> /Users/rherrema/Documents/Frameworks/of_v0.10.1_ios_release/libs/openFrameworksCompiled/lib/ios/libofxiOS_iphoneos_Debug.a, file was built for archive which is not the architecture being linked (x86_64): /Users/rherrema/Documents/Frameworks/of_v0.10.1_ios_release/libs/openFrameworksCompiled/lib/ios/libofxiOS_iphoneos_Debug.a
:-1: symbol(s) not found for architecture x86_64

**Comment by antoineschmitt** [comment]
Same problem here. Did you find a fix ? Thanks !

**Comment by ofTheo** [comment]
I think this is an issue with the build settings of the iOS+OFLib.xcodeproj
The product name is set like this: 


<img width="671" alt="image" src="https://user-images.githubusercontent.com/144000/63623344-3541d900-c5ae-11e9-9606-03ef0575ab3a.png">

But the platform name is not getting updated in the linker stage of the Build Phases for the example / app xcodeproj that includes the iOS+OFLib.xcodeproj.
 
So when you run an app in the simulator its trying to link to libofxiOS_iphoneos_Debug.a instead of libofxiOS_iphonesimulator_Debug.a 

![image](https://user-images.githubusercontent.com/144000/63624621-e433e400-c5b1-11e9-9068-63f662071925.png)

**SOLUTION:** 

( going to dig in more to this - but this seems to work well ) 
1) Add this to CoreOF.xcconfig

`LIB_OF = "$(OF_PATH)/libs/openFrameworksCompiled/lib/ios/libofxiOS_${PLATFORM_NAME}_${CONFIGURATION}.a"`

2) In CoreOF.xcconfig change the CORE_OF_LIBS line to add $(LIB_OF) to the end like:

`OF_CORE_LIBS = $(MISC_FLAGS) $(LIB_BOOST) $(LIB_FREEIMAGE) $(LIB_FREETYPE) $(LIB_OPENSSL) $(LIB_TESS) $(LIB_CURL) $(LIB_URIPARSER) $(LIB_PUGIXML) $(LIB_OF)
`

3) Remove libofxiOS_iphoneos_Debug.a from the linking phase of Build Phases so you just have these libraries linked. 

<img width="875" alt="image" src="https://user-images.githubusercontent.com/144000/63624562-a636c000-c5b1-11e9-9a60-302c7e3d1691.png">

This should now link Simulator and Debug for all platforms.
