### ISSUE TITLE
updating nlohmann::json to 3.5

### ISSUE THREAD

**Issue by brinoausrino** [openframeworks/openFrameworks#6258]
I'm working on a wrapper for a json-schema validator to use as an of-addon -> https://github.com/pboettch/json-schema-validator.
The validator needs the current nlohmann::json release therefore I updated it in my of repository. Should I make a fork, pull request with the updated version?

**Comment by arturoc** [comment]
yes please, be aware that this should go in the apothecary repo not here. you will need to modify the corresponding script there to pull the correct version.

it should be pretty straight forward since this library doesn't require compilation as far as i remember

I'm going to clsoe this but feel free to create a similar issue in the apothecary repo or directly a PR
