### ISSUE TITLE
ofPath::tessellator initialization order fiasco

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/openFrameworks#6294]
Hi, I've seen several times apps crashing randomly (ie. you run it once and it works, then run it again without even recompiling and it will crash, then run again and it works fine), where always the crash points to `ofPath::tessellator`. I think that the problem is due to the initialization order fiasco, which is properly addressed on lots of other parts of the OF core but not in this case.
The one issue that raises my doubt here, rather than just simply implementing the fix and making a PR, is that these `static` variable is also, sometimes, a `thread_local` variable. 
As far as I can tell the implementation for the the `thread_local` and the regular `static` variables is almost the same, but I might be wrong. Can you guys enlighten me please? @arturoc @bakercp 

 I think that we should implement a getter function for the tessellator like this.

```
static ofTessellator & getTessellator(){
#if defined(TARGET_EMSCRIPTEN)
	static std::unique_ptr<ofTessellator> i =  make_unique<ofTessellator>();
	return *i;
#elif HAS_TLS
	static thread_local std::unique_ptr<ofTessellator> i =  make_unique<ofTessellator>();
	return *i;
#else
	return tessellator; // non static instance defined in ofPath.h
#endif
}
```
Would this be correct? Please let me know what you think. cheers

**Comment by arturoc** [comment]
I doubt this is related to static initialization order since the tesselator is never used until draw or getTesselation are called explictly, never on any constructor so unless you are calling yourself those on any constructor called from a static initialization it shouldn't be a problem.

Also the initialization order is not random and definetly wont't change between runs without recompiling and in most cases even after recompiling.

The tesselator sometimes crashes due to malformed triangles (three points on the same line for example) so i think that might be the problem. If you are running the tesselator on a randomly initialized shape it would make the crashes random. I haven't checked in a while if there's a new version of the tess2 library but if there is we might want to update it. Other than that or trying to detect malformed triangles (which might make tesselation much slower) I'm not sure there's any other solution

**Comment by roymacdonald** [comment]
I see. Thanks for answering.
This happens when using ofxGui actually. So the geometry is not random. I think it happens when instantiating an ofxFloatSlider, for example, as it usually points to the to it.
<img width="1400" alt="Screen Shot 2019-05-21 at 09 53 47" src="https://user-images.githubusercontent.com/974878/58101948-7b9e2b00-7bae-11e9-9256-4bc3393ec0cf.png">

In this case the ofxFloatSlider instances are being created "on demand" and it is within the draw function that these are created if needed. Any ideas? I will try to isolate the issue and come back.
all the best

**Comment by arturoc** [comment]
This might happen from trying to render a really small rectangle in a slider which value is really small. If that's the case we could easily solve it by not drawing anything in sliders if the value is equivalent to less than one pixel which should be pretty cheap to calculate

**Comment by roymacdonald** [comment]
It might be, but then why the erratic behavior? If the case has to do with the sliders then these are initialized with the same values all the time.

**Comment by tgfrerer** [comment]
If a float parameter for example is not initialised with a value, only declared, it won't get zero-initialised, but will get whatever value the memory assigned to it held at the time ("garbage data"). 

This happens for example when a parameter is declared in the header file without initialisation, then drawn before a value was assigned to it.

While it's possible but not very likely that such garbage data value will be 0, more often than not it will, interpreted as a float, give you a negative number or even `NaN`, which leads to the surreal situation where the tessellator will get asked to tessellate a negative rectangle, or one with a width of `NaN`, at which point it will throw a tantrum.

**Comment by arturoc** [comment]
going to close this since it's not really describing the correct problem but feel free to reopen - keep commenting here if the problem persists after tim's fix
