### ISSUE TITLE
Mojave 10.14.6 update

### ISSUE THREAD

**Issue by autr2** [openframeworks/openFrameworks#6377]
This update seems to break OF - getting these errors with master, patched and stable branches:

<img width="485" alt="Screenshot 2019-10-01 at 17 02 12" src="https://user-images.githubusercontent.com/1035590/65974422-3b5c8c80-e46d-11e9-83d3-a03d71199086.png">

(Also using XCode 11)

**Comment by ofTheo** [comment]
Hmm - I am on 10.14.6 - can you try with the Nightly build at the bottom of this page?
https://openframeworks.cc/download/ 

Also 
- Which Xcode are you running?
- What is your macOS deployment target in your Xcode build settings?

**Comment by autr** [comment]
Xcode 11
Default 10.9, and tried through til 10.15

I think it’s Xcode 11 issues - I’d previously added the 10.7 SDK inside Xcode.app, but it wasn’t showing up in the Base SDK options. Since removing it, I get a different error: `ofConstants.h:84:14: 'TargetConditionals.h' file not found`

Nightly build works, but if I roll back the master branch to the nightly commit b34f9a936badb4b9667daaa90d16e719fab8eb03, the error persists

**Comment by ofTheo** [comment]
Going to close as I think this is working for most users.
