### ISSUE TITLE
ofPolyline smoothed seems broken in nightly 

### ISSUE THREAD

**Issue by ofZach** [openframeworks/openFrameworks#6414]
was just working with a student and we noticed ofPolyline::getSmoothed() seems broken on nightly. 

example code: 

```
ofPolyline line;
for (int i = 0; i < 100; i++){
        float angle = ofMap(i, 0, 100, 0, PI);
        line.addVertex(400 + 200 * cos(angle),
                       400 + 200 * sin(angle));
    }
line = line.getSmoothed( (int)ofMap(mouseX, 0, ofGetWidth(), 0, 11));
line.draw();
```

in 0.10.1 it works as expected (half-circle shrinks slightly as you move the mouse), in nightly when you move the mouse over it does something strange.  

investigating...

**Comment by ofTheo** [comment]
wow - I think this is another case of a bug with glm now not initializing variables by default. 
hard to catch because of the templating. 

https://github.com/openframeworks/openFrameworks/blame/master/libs/openFrameworks/graphics/ofPolyline.inl#L490 

```
			T cur;
``` 

is not initialized so has garbage values.   
Try changing it to:

```
			T cur(0);
``` 

See: https://github.com/openframeworks/openFrameworks/issues/6397#issuecomment-544202311 

I am more and more tempted to do our next release with:
`#define GLM_FORCE_CTOR_INIT 1` 

Or document really well the switch and how the #define can be used if needed.

**Comment by ofZach** [comment]
yeah I was just about to say, I tracked it down to T cur being different on the two releases :) 

T cur(0) definitely fixes.  I wonder if there are other subtle issues w/ initializing we should be looking for.
