### ISSUE TITLE
High Resolution Capable / Retina issue in the windows setup with GLFW

### ISSUE THREAD

**Issue by P0ulp** [openframeworks/openFrameworks#6487]
When I use this code with High Resolution Capable set to Yes, I get different result depending on the resolution I set in `ofSetupOpenGL();`.

```
#include "ofApp.h"
#include "ofAppGLFWWindow.h"

//--------------------------------------------------------------
void ofApp::setup(){	

    int scale = ((ofAppGLFWWindow *)(ofGetWindowPtr()))->getPixelScreenCoordScale();
    cout << " scale is " << scale << endl;
}

```
In my case, my screen physical resolution is 3840x2160. In my graphics configuration (macOs) my scaled resolution is 2560x1440. If in `ofSetupOpenGL();` the width is equal or below 2560 (opening a window being half of my width screen) the scale value (`pixelScreenCoordScale`) is 2, but if I want to open a window bigger than half of my width screen and I set in ofSetupOpenGL(); a width greater than 2560 the scale value is 1.

Internally, the scale value is a 0 < float < 2, so when the value is wrong the function using this value return wrong value (for example `ofGetWidth()`).

I've search a bit, and it seems that the issue is in the `ofAppGLFWWindow` class. Indeed, the value (`pixelScreenCoordScale`) calculated in the `Setup()` function is wrong, contrary to those calculated in `resize_cb()`. So If a callback is triggered on `resize_cb()`, for example with `ofSetWindowShape()` the values are right.

@roymacdonald

**Comment by roymacdonald** [comment]
Hi, On my computer, I see this happening from resolutions with a width > 1920 on macos 10.14.6. 
@P0ulp in your code you are storing the pixelScreenCoordScale in an `int` that's why you get 1, while actually it is something more like 1.9.
There are some math being done when the window is first opened that according to the window mode it will set its internal parameters, which happen to be very similar to those done by `resize_cb()`. I'll try to reduce this code redundancy and see how it goes, although I have the feeling that this is  GLFW problem rather than an OF one. I'll test with glfw alone to see if it happens as well.

**Comment by P0ulp** [comment]
Hi ! Indeed I store this in a int, because the getPixelScreenCoordScale() function return a int in ofAppGLFWWindow.cpp. But I have indeed the same feeling that the issue comes from GLFW ...

**Comment by ofTheo** [comment]
I think this is due to an interesting interaction between GLFW and the scaled screen size in macOS. 
If you don't use the default screen size setting in macOS, then you are not really using pixel doubling / retina. 

Going to dig in too, but I think the behavior / bug makes sense. Just need to figure out a good way to deal with it.

**Comment by roymacdonald** [comment]
Hi @ofTheo I was taking a look at this and there are some math done [here](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L153-L397) make assumptions that are not correct. The weird part is that it gets fixed when the window is resized. I'll continue looking at what it might be.

**Comment by ofTheo** [comment]
I wonder if moving these lines: 
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L329-L332

after this would fix it in setup:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L329-L332

**Comment by roymacdonald** [comment]
@ofTheo you pasted the same URL twice. 

Although I think there is a bit of redundancy of code which is leading us to have this problem.

**Comment by ofTheo** [comment]
oops! edited - thanks. 
yeah for sure it could be cleaner to have the calculation in one place. my guess is though that the because the window shape is set after the density calculation in setup it is getting calculated incorrectly.

**Comment by ofTheo** [comment]
actually @roymacdonald @P0ulp 
this seems to fix it for me change 
`pixelScreenCoordScale = (float)framebufferW / (float)windowW;`
to
`pixelScreenCoordScale = (float)framebufferW / (float)tmpWindowW;`

On line:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L329

Could you confirm that works on your end?

**Comment by roymacdonald** [comment]
@theo How are you testing? I think that I need a larger retina scree that the one I have right now.

**Comment by ofTheo** [comment]
@roymacdonald I just tested on my laptop.
Set the screen resolution to Default and in the plist add: High Resolution Capable : Yes 

Then  did `ofSetupOpenGL(1920*2, 1200*2, OF_WINDOW);`

I get pixelScreenCoordScale listed as 1 in ofApp::Setup but 2 in resize callback. 

With the fix above I get 2 in both.

**Comment by roymacdonald** [comment]
@ofTheo thanks. that works.
Actually the problem was that if you'd set the initial screen size to something like `ofSetupOpenGL(1888, 1200, OF_WINDOW);` you would get something like the following pic, with this draw code
```
void ofApp::draw(){
	ofBackgroundGradient(ofColor::white, ofColor::gray);
	ofDrawCircle(ofGetMouseX(), ofGetMouseY(), 30);
}
```
and would only render properly after resizing the window. With this tiny fix you made this got solved. 👏 👏 👏 
please merge it.
<img width="1238" alt="Screen Shot 2020-02-16 at 10 03 07" src="https://user-images.githubusercontent.com/974878/74607140-1d05cf00-50a4-11ea-969e-a212e0facd18.png">

all the best
