### ISSUE TITLE
ofParameter events not firing with newListener

### ISSUE THREAD

**Issue by neilmendoza** [openframeworks/openFrameworks#6489]
If I do...

```
ofParameter<glm::vec3> vTest;
ofParameter<float> fTest;

...

vTest.newListener([this](glm::vec3& f){cout << "test";});
fTest.newListener([this](float& f){cout << "test";});
```

...the events don't fire. This works though...

`vTest.addListener(this, &ofApp::test);`

**Comment by arturoc** [comment]
newListener returns a listener that has to be stored otherwise the listener is destroyed right away and the event is not listened to anymore:

usually in your .h file add an ofEventListener or ofEventListeners if you want to add more than one and then:

```cpp
listener = vTest.newListener([this](glm::vec3& f){cout << "test";});
```

when you class is destroyed ithe listeners will autoremove the event

**Comment by neilmendoza** [comment]
Ah sorry, my bad...
