### ISSUE TITLE
Windows msys2 64bits failing to link on CI tests

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6605]
Last PRs seem to fail to link with several undefined references. eg: https://ci.appveyor.com/project/arturoc/openframeworks/builds/34415684/job/mnc18wc0xjrf1ocs

**Comment by tgfrerer** [comment]
Could this have something to do with ccache i wonder? 

The builds that failed initially failed because they timed out, and now, the msys builds which fail do so after a relatively short time of about 20 minutes.

perhaps we could try [cleaning up the cache](https://www.appveyor.com/docs/build-cache/#cleaning-up-cache) manually?

**Comment by tgfrerer** [comment]
Update: it doesn't seem to be build cache. Disabling it didn't make an observable difference. 

### Some observations:
* x86 msys compiles fine, errors out when attempting to run networkTcp_debug.exe: `error while loading shared libraries: ?: cannot open shared object file: No such file or directory` no name for the missing shared library given. 
*x64 msys compiles openframeworks library fine, but errors out when compiling allAddonsExample (which is compiled before running any tests): here, a ton of ugly linker errors show up.
* when restarting msys2 build jobs which were completing successfully in the past, these now fail, too

Because of this last point, I wonder if it it could be something to do with the appveyor msys2 build environment having changed...

**Comment by oxillo** [comment]
Same problem locally on my machine ( and also in GuiExample ). So it is not a CI bug. 

Compiling in Release mode works fine. 

So I think, it's more a compilation/link optimization (G++ version is 10.2.0)

**Comment by oxillo** [comment]
I've pinpoint the faulty lines :
ofxSlider.cpp:
```cpp
template class ofxSlider<typename std::conditional<std::is_same<uint32_t, size_t>::value || std::is_same<uint64_t, size_t>::value, bool, size_t>::type>;
```
ofxInputField.cpp:
```cpp
template class ofxInputField<typename std::conditional<std::is_same<uint32_t, size_t>::value || std::is_same<uint64_t, size_t>::value, bool, size_t>::type>;
```
Suppressing these 2 lines solve the problem.
I do not really understand the purpose of these lines. Not sure they are useful...

**Comment by oxillo** [comment]
There is also a problem with SVGTiny with duplicate symbols. Fixed with above PR.
