### ISSUE TITLE
More than one nightly build is being kept

### ISSUE THREAD

**Issue by arturoc** [openframeworks/openFrameworks#6662]
It seems from the webpage, that old nightly builds are not being deleted or at least there's one that hasn't.

![image](https://user-images.githubusercontent.com/48240/105330841-0b417b80-5bd3-11eb-9b09-8adb7148dee5.png)

**Comment by ofTheo** [comment]
This should be fixed now ( after the next nightly build runs ).  

This issue has been there for a while, but removing the gcc4 / gcc5 links revealed it as before we wouldn't see the next release below. I removed the old releases which because of a different naming convention were not being deleted by the script.
