### ISSUE TITLE
ofSetFullscreen - issues after entering and exit fullscreen

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#6719]
After enter fullscreen and exit, sometimes aspect ratio is changed and window will only work correctly on fullscreen.
I've noticed this on Big Sur, apple m1, not sure if it is affect other builds too.
this only happens when my main window is created with dimensions exceeding or equaling screen size.
for example in this computer if my window width is 1439 it doesn't happen, if it is 1440 it start to happen.
vertical window size seems to influence but not sure how.
mouse coordinates are still good after the issue.

```c++
void ofApp::draw(){
    ofSetColor(255,0,70);
    ofDrawCircle(300, 300, 300);
}

bool fs = false;
void ofApp::keyPressed(int key){
    if (key == 'f') {
        fs ^=1;
        ofSetFullscreen(fs);
    }
}
```
Before Fullscreen
<img width="1552" alt="Screen Shot 2021-03-25 at 12 04 48" src="https://user-images.githubusercontent.com/58289/112495085-55291800-8d62-11eb-881b-cb43f4139621.png">

After Fullscreen
<img width="1552" alt="Screen Shot 2021-03-25 at 12 04 52" src="https://user-images.githubusercontent.com/58289/112495113-5bb78f80-8d62-11eb-93d7-d9b5c0306791.png">

**Comment by ofTheo** [comment]
Huh. Weird. I just tried on an intel MBP and don't see the issue. Is this with 0.11.1 / 0.11.2 ?

Is your window setup for Default for Resolution in the Display settings of System Preferences?
Or one of the other modes? 

<img width="655" alt="image" src="https://user-images.githubusercontent.com/144000/112504339-eb504480-8d48-11eb-826d-18ea06aca146.png">

**Comment by dimitre** [comment]
not sure if it helps, this display gives this warning when switching fullscreen and back
```
CVCGDisplayLink::setCurrentDisplay didn't find a valid display - falling back to 60Hz
[ error ] ofAppGLFWWindow: 65544: Cocoa: Failed to find service port for display
```

**Comment by ofTheo** [comment]
Hmm. I see that error coming up for other apps that use GLFW with M1 machines. 

Out of curiosity does it go away if you do this in `ofAppGLFWWindow::update()` ?

	if( targetWindowMode == OF_WINDOW){
			 int winW, winH;
			glfwGetWindowSize(windowP, &winW, &winH);
			resize_cb(windowP, currentW, currentH);
	}

**Comment by dimitre** [comment]
I can confirm the issue is still happening after inserting this code in update, I've inserted at the end of update. after RPI code

**Comment by dimitre** [comment]
maybe it is related to this one https://github.com/glfw/glfw/issues/1060

**Comment by petewerner** [comment]
I had a look at this today

I tried glfw-master from today and did not fix it however it did silence a bunch of chatty messages that show up on arm builds

- The issue seems to happen if width >= screen width, having height >= screen height does not seem to trigger it.
- If the window is created with mode = OF_FULLSCREEN, the issue does not seem to occur.
- I can successfully reproduce it on intel macs with 0.11.2 so its not exclusively an m1 issue.
 

main.cpp
```
    glm::vec2 dims(1920);
    ofGLWindowSettings settings;
    settings.setSize(dims.x, dims.y);
    settings.windowMode = OF_WINDOW;
    ofCreateWindow(settings);
    ofRunApp(new ofApp());
```

ofApp.cpp

```
void ofApp::draw(){
    ofDrawRectangle(0, 0, 300, 300);
}
void ofApp::keyPressed(int key){
    if (key == 'f')
        ofToggleFullscreen();
}
```

Happy to take suggestions about where the issue might be, the FULLSCREEN vs WINDOW thing seems to be important. I am not that familiar with that part of the code base so nothing immediately jumped out at me.

**Comment by dimitre** [comment]
it bugs me why the aspect ratio is wrong. it is like width is correct and height not.
maybe we can try to fill an issue on GLFW, they seem still far from solving this kind of issues on macOs
https://github.com/glfw/glfw/issues/1857
https://github.com/glfw/glfw/issues/1800
https://github.com/hajimehoshi/ebiten/pull/1811

**Comment by ofTheo** [comment]
Thanks @petewerner 

I think it might be worth looking at the frame buffer size before after toggling fullscreen - maybe putting a print out in these two functions? 

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L1581-L1611

That might help isolate where the issue is? 
It also might be that one of the callbacks is not happening or getting updated so the framebuffer is getting stretched or squished?
