### ISSUE TITLE
Most examples for iOS are outdated or broken

### ISSUE THREAD

**Issue by atiliomf** [openframeworks/openFrameworks#6723]
Hello everybody. I have just finished testing all of the examples for iOS in the latest release. My setup: OF 0.11.2, Xcode 12.4, macOS 10.15.7, iPhone SE 1st generation with iOS 14.4.1. These are my findings:

About half of the examples did not compile at all, but many had easy fixes:

Add a camera usage description key to ofxiOS-Info.plist:

	videoGrabberExample
	ImagePickerExample
	opencvFaceExample

Add a microphone usage description key to ofxiOS-Info.plist:

	audioInputExample

Remove `ofxAccelerometer.setup();` in ofApp.mm:

	CoreLocationExample
	eventsExample
	iosExternalDisplayExample
	KeyboardExample
	MapKitExample
	PrimitivesExample
	iosCustomSizeExample

Replace `ofTTFCharacter` with `ofPath` in ofApp.h:

	fontShapesExample

Remove the sections `attitude- quaternion` and `quaternion rotations` in ofApp.mm:

	iosCoreMotionExample

These examples compile but crash when the "back" button of the native GUI is pressed (this does not happen under 0.9.0):

	iosNativeExample
	iosCustomSizeExample

In these examples (which work properly under 0.9.0) the left and right orientations are switched or the image is upside down (seems related to issue #6076):

	iosOrientationExample
	videoGrabberExample
	opencvFaceExample

In this example, multitouch was not enabled. Add `settings.enableMultiTouch = true;` to ofApp.h:

	iosCoreMotionLegacyExample

I could not get these examples to compile at all: 

	GLKitNativeARCExample
	iPhoneGuiExample
	ofxGuiExample
	assimpExample (works under 0.9.0)
	vboExample (works under 0.9.0)

Also, there are many warnings within Xcode (the empty example produced 136 using the settings as-is) and there is deprecated code (such as `ofRotate `and `ofSoundStreamSetup`) in many examples.

It would be a good idea to revise and update all of the examples at some point. I hope my "summary" will be of some help in that sense.

**Comment by ofTheo** [comment]
Hi!

Thanks for this. 
I can help with the plist stuff for the iOS template. 

Would you be able to do a Pull Request for any of the ofApp.cpp/.h changes needed for the examples?

Thanks!
Theo

**Comment by danoli3** [comment]
Thanks mate! Checklist for sure

**Comment by artificiel** [comment]
### FIXED ###

CAMERA PERMISSION solved by default camera usage description key in recent template
`videoGrabberExample ` `ImagePickerExample` `opencvFaceExample` 

ACCELEROMETER-RELATED solved by #7371
`CoreLocationExample` `eventsExample` `iosExternalDisplayExample` `KeyboardExample` `MapKitExample` `PrimitivesExample` `iosCustomSizeExample` `iosCoreMotionExample` 

MISC #7373
`fontShapesExample` solved by Replace ofTTFCharacter with ofPath in ofApp.h
`iosCoreMotionLegacyExample` fixed by settings.enableMultiTouch = true
`iPhoneGuiExample` fixed by XIB tweaks
`vboExample` glm adjusments
`iosStoryboardExample` storyboard and ARC
`audioInputExample` solved by microphone usage description key in recent template but still a cohabitation problem between ofSoundStream and ofSoundPlayer #7291 -- commenting out the sound player stuff makes the example work and display the input signal which is the objective of the demo so considered solved and see what happens with #7293

EXTERNAL ISSUE
`assimpExample` fixed by #7372 ofxAssimpModelLoader addon_config library tweak

### THE BIG ORIENTATION MESS ### 

`iosOrientationExample` `videoGrabberExample` `opencvFaceExample` compile and run correctly except the left and right orientations are switched or the image is upside down. seems related to issue #6076 and all the other orientation issues. As far as this issue goes the example work, and the real problem will be solved elsewhere.

### STILL PROBLEMS iOS-related ###

1) `iosNativeExample` `iosCustomSizeExample` `GLKitNativeARCExample` `iosStoryboardExample` compile but crash when the "back" button of the native GUI is pressed (this does not happen under 0.9.0) (feels like something is not retained) — not clear if it's because of a pattern of how these examples are written, or an underlying cause — should be addressed 

2) `ofxGuiExample` something ofParameter template fishy with ofxSlider<unsigned int> ending in a link "missing symbol" error — should be addressed
when #7373 #7372 and #7371 get merged this issue should be closed and 2 fresh ones opened specifically for the 2 problems above.

and also yeah eventually a thorough review of all...

**Comment by ofTheo** [comment]
Amazing! Thanks @artificiel 

I wonder if the Native UI issues are tied to them being created before we moved to ARC?

**Comment by artificiel** [comment]
Yes it’s a 0x0 error so probably, but the viewcontroller pattern at play is pretty alien to me it would be better looked at by someone familiar. Same with the ofxSlider, the problem being a template-induced linking error it’s harder to debug — probably will be easier to figure out for someone acquainted with the internals of ofxGui.

**Comment by artificiel** [comment]
@dimitre @ofTheo #7458 and #7457 transpose what is left of this issue, which can be closed
