### ISSUE TITLE
ofDirectShowPlayer hits "failed to find the video renderer"

### ISSUE THREAD

**Issue by nama-gatsuo** [openframeworks/openFrameworks#6765]
When I tried to play `videoPlayerExample` in v0.11.2 with VisualStudio, just got: 

```
failed to find the video renderer
```
and wouldn't update video frame. Here is the line.https://github.com/openframeworks/openFrameworks/blob/7c46c8a9415703c1cf7ce1bb66c91cc97851fa19/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L619

my env:

* Windows 10 Home 21H2 19044.1202
* VisualStudio2019 Community (v142)
* K-Lite Codec Pack 16.4.0

Before half a year I could open any video files on same machine, but I keep almost all system (like Win OS/framework, NVidia firmware, K-Lite codec etc.) up-to-date to their latest, and now I've got the error above. Looking up to docs DirectShow from Microsoft, I found some features are going to be deprecated such as [SampleGrabber](https://docs.microsoft.com/en-us/windows/win32/directshow/using-the-sample-grabber). Yet I couldn't make sure what the exact problem is and how to hot-fix it.

An alternative that works for me is just to use this: [DomAmato/ofxWMFVideoPlayer](https://github.com/DomAmato/ofxWMFVideoPlayer). This plugin can be built with v0.11.2 without errors and can open/play videos.  Downgrading software/apis like VisualStudio might work too, but it's not the one for me.

This issue should be relatable with #5156 .

**Comment by hanasaan** [comment]
I encountered exact same problem with playing video files using `ofVideoPlayer` on Windows 10, which was totally fine 3 months ago.
I keep NVIDIA drivers and Windows 10 up to date, so I suspect these software update has affected `ofDirectShowPlayer` behavior. 

For my environment, I found quick fix of this issue by renaming `"Video Renderer"` to `"Video Mixing Renderer 9"` in this line.
https://github.com/openframeworks/openFrameworks/blob/7c46c8a9415703c1cf7ce1bb66c91cc97851fa19/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L617


I checked DirectShow graph by graphedit and I found in my environment video render block has the name "Video Mixing Renderer 9".
<img width="561" alt="graphedit" src="https://user-images.githubusercontent.com/7454329/133561385-3cc793bf-0f84-4e34-b9fb-3017d243a3e4.PNG">

In my environment, all video has a same render block name.

This name might be changed by environment. So more sophisticated workaround is needed to be integrated into master branch.

**Comment by ofTheo** [comment]
Hi! 

I just ran into this issue on a new system. 
This is what fixed it for me:

In Codec Tweak Tool which is installed with K-Lite. 

Select Preferred Decoders in the bottom left. 
Then set the for every option `LAV Video`. 

![image](https://user-images.githubusercontent.com/144000/133653803-b68dda08-7534-46bb-b185-b66406b11e55.png)

Then hit Apply and Close. 

Let me know if that works for you both and I will add it to the instructions. 

Note: we are working on a new video player for 0.12.0

**Comment by hanasaan** [comment]
@ofTheo 
Thanks for providing a new solution.
But unfortunately it didn't work for me.
With this new setting, I still needed to rename `"Video Renderer"` to `"Video Mixing Renderer 9"` in `ofDirectShowPlayer.cpp`.

**Comment by ofTheo** [comment]
Thanks @hanasaan - I tried again on a clean install and found the one thing needed in the Codec Tweak Tool. 
I think I had done this at the same time as the other changes I suggested. I will add this to the setup instructions, or maybe we can find a way to detect in the video player and do either your approach or the old approach based on the filter graph?

Go to: `General -> Fixes ` and check `Re-register base Directshow Filters`

![image](https://user-images.githubusercontent.com/144000/133816916-6e70f16e-98c5-451e-94f9-ace3cae6bb18.png)

**Comment by hanasaan** [comment]
@ofTheo Yes, it works. thanks!

**Comment by prudd42** [comment]
@ofTheo I was having the same issue with "failed to find the video renderer". 

Env
Windows 10 Home 
20H2
K-Lite Codec 16.4.7 (Full)
openFrameworks v0.10.1

In my case I do my development on a different machine and deploy applications to multiple other machines. Most have worked in the past however one wasn't working. 

I looked at the GraphEdit on the machine that wasn't working and saw that it was using "Video Mixing Renderer 9" just like @hanasaan. When I opened the Codec Tweak Tool the "Re-register base Directshow Filters" was already checked. Because I deploy to multiple machines I am hesitant to change the "Video Renderer" string. 

Instead I hit the "Re-register DirectShow filters from K-Lite Codec Pack" option in General>Fixes. This then reset all of the "Preferred decoders" to "Microsoft" so I went through and set them all back to "USE MERIT". 

![Capture](https://user-images.githubusercontent.com/50640001/135110500-17d59ec0-999e-4219-a81b-1c8d567026c7.PNG)

![PreferedDecoders](https://user-images.githubusercontent.com/50640001/135111102-b11b9f3f-0f20-419d-8073-56ec670cb102.PNG)

Between these two steps the GraphEdit was now displaying "Video Renderer" in the final block, however the middle block was some Microsoft thing (Didn't take a screencap at this stage). This fixed the issue for me and the videos are now playing. After I rebooted the middle block changed to "LAV Video Decoder" and the videos still play.

![GraphEdit](https://user-images.githubusercontent.com/50640001/135111575-1643ea1c-da6a-46cf-a0cc-a5a0e5aa7f33.PNG)

I do not want to make any additional changes on this laptop because it is needed in production shortly and I don't want to break it.

 Hopefully this helps.

**Comment by ofTheo** [comment]
Thanks for this @prudd42 !

I think a true fix for this issue would be to put a similar section after this:

https://github.com/openframeworks/openFrameworks/blob/8569142e8850862da3701d8723da92fdfebc25bb/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L617-L622

trying "Video Renderer 9" or probably better matching any filter with "Video Renderer" in the name.

Going to try a couple of approaches and see what works.

**Comment by clsid2** [comment]
You may also want to include "Enhanced Video Renderer", which is another standard renderer from Windows. It is not used by default in a simple graph, but could be used if a user increased its filter merit. Same applies to third party video renderers.

A good fallback detection method:
Enumerate filters and find first filter that has zero output pins, and at least one input pin where the mediatype has a majortype equal to MEDIATYPE_Video.

**Comment by ofTheo** [comment]
@clsid2 wow - thanks for this info! 

If you felt like doing a PR for the enumeration ( and it wasn't a big pain ), I like the idea of something a bit more future proof like you describe. 

Ultimately I want to move over to an IMFMediaEngine based approach so we don't need to install codecs at all.

**Comment by clsid2** [comment]
I don't use OF myself, so can't help you with a PR. But you can find an example in the code base of MPC-HC:
https://github.com/clsid2/mpc-hc/blob/develop/src/DSUtil/DSUtil.cpp#L103

Media Foundation does offer a bit more codecs out-of-the-box in Windows, but be aware that it is far from complete in terms of coverage for common formats. For example decoders for HEVC and VP9 video still need to be installed manually through the Windows Store or [Appx](http://codecguide.com/media_foundation_codecs.htm).

**Comment by axjxwright** [comment]
> @clsid2 wow - thanks for this info!
> 
> If you felt like doing a PR for the enumeration ( and it wasn't a big pain ), I like the idea of something a bit more future proof like you describe.
> 
> Ultimately I want to move over to an IMFMediaEngine based approach so we don't need to install codecs at all.

Just FYI, I've already done this for cinder, with both a CPU and hardware accelerated render path that you can check out [here](https://github.com/axjxwright/AX-MediaPlayer), I suspect a port to OF would be trivial, assuming it does everything you needed.
