### ISSUE TITLE
ofxAssimpModelLoader - Error calculating normalized scale of scene

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7376]
With the current master branch I get an error `[warning] ofxAssimpModelLoader: Error calculating normalized scale of scene` with the `3DModelLoaderExample`, `advanced3dExample` and `modelNoiseExample`. In the first two examples I can not see any models, in the third one it is very, very small.

And for Linux it seems that the `assimp` lib is not installed.

**Comment by dimitre** [comment]
I'm working on this right now, already know how to fix it.
it was introduced on this PR https://github.com/openframeworks/openFrameworks/pull/7366
and I'm trying to clean up tangled dependencies

I already know it can be fixed by adding 
#include "ofConstants.h"
to the file ofxAssimpMeshHelper, but I'll try to be more precise and identify what include it is missing exactly.

it is kind of an obscure error because it compiles OK but calculates things differently...

**Comment by ofTheo** [comment]
Ahh yes, I think it’s because we define this line in ofConstants.h : https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L16

So we have to be careful to not include glm directly but do so via ofConstants.h 

We could potentially move it out to another file or find another way to make sure the define is set, but without it glm types have undefined values and that caused a lot of errors in the past. 

We should actually probably fix the undefined variables this exposes in the addon. The define was really meant for users projects with OF core intending to work the same without it.

**Comment by dimitre** [comment]
Thank you @ofTheo I'll make it work without including ofConstants. 
just linking here the related thread https://github.com/openframeworks/openFrameworks/issues/6530

**Comment by Jonathhhan** [comment]
@ofTheo @dimitre thank you both :)
