### ISSUE TITLE
Github actions, suggestion of moving tests from msys2 to vs2019

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#7398]
I've noticed not all the actions platforms run tests at the end, so I suspect one will run tests on each platform (macos, linux, windows)
so as vs2019 action is much faster to build, we can move testing to this action, so the whole batch of tests run faster.
Nowadays the test that takes longer is msys2, about 26, 27 min.

**Comment by oxillo** [comment]
@dimitre Maybe there is something I do not catch...
If MSYS2 tests are moved into VS2019 action, a full OF recompilation will be required with MSYS2 toolchain. I suspect it will be worse.

Additional remark: the VS action doesn't run tests !  It only builds the empty and alladdons examples.

**Comment by ofTheo** [comment]
Tangental to this @oxillo 

Wondering if we could simplify the mysy2 approach for OF. 
Is there a flavor / version that we could make the supported one and drop the rest? 

Having one msys2 platform to support and then making the setup guide ( and all the build stuff ) based on that would make maintenance a lot easier. Doesn't have to be right away, but just a thought. 

Thanks!!
Theo

**Comment by dimitre** [comment]
tangential to this too, @oxillo we are using caching in macOS build, so we save the compiled files from one session to another

here in the actions it is named "Cache compile"
https://github.com/openframeworks/openFrameworks/blob/master/.github/workflows/build-macos.yml

so only the changes are recompiled.

**Comment by oxillo** [comment]
@ofTheo : MSYS2 recommends UCRT64 environment. Personnaly, I still need MINGW64 because I'm using some old libs that need to be compatible msvcrt. We may keep the building of all flavors in CI and only release UCRT64 and MINGW64.

@dimitre : a while ago, I've tried to use ccache on AppVeyor but there was no big improvements. I've read things saying that 'make' in MSYS2 is slow because it is going through all POSIX compatibility layer. 'mingw32-make' is native and should be faster. I'll try to see if it speeds up the compilation.

**Comment by dimitre** [comment]
@oxillo I've finally speed up msys2 compilation with ccache (cached in github actions)
some make changes enabling multicore
and installing and caching msys packages using pacboy and cache

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7850/
