### ISSUE TITLE
Xcode sidebar OF reference/group is relative to ../../.. wherever the project is PG-created/updated

### ISSUE THREAD

**Issue by artificiel** [openframeworks/openFrameworks#7464]
the incorporation of the OF tree in the sidebar of the Xcode project is broken when the project is not exactly `../../..` to OF; it is displayed in red and looks like an error.

it's been "revealed" by the attention to 24746f0 but was like that before. i put my projects not at `../../..` and now realize i have been now for a while spontaneously deleting the red OF stuff and thought it was a (harmless) confusion/mismatch somewhere.

but i now realize there is a true desire to have the stuff appear at the left, even if it's not needed in the project (it's not in the target as it's compiled in the `Compile OF` phase).

for this "documentation browsing feature" to work properly it must take into account `OF_PATH` in `.xcconfig` (don't know if that's doable) or be processed in the PG like the addon paths. 

(note that if PG/Xcode work is considered i strongly recommend taking the occasion to make the paths of addon relative to the `$OF_PATH` instead of the project, as discussed in #7351 (addons are relative to OF and not your project), and it will make the Xcode project portable or re-orientabe to another OF tree with the sole editing of `OF_PATH` (the countless xcode flags will simply follow $OF_PATH , which is better than re-initializing your project to rewrite the `../../../../../../../../..` things).

![image](https://user-images.githubusercontent.com/2172370/229410650-261d14ff-a64f-407e-9e86-bc42235e60d6.png)

![image](https://user-images.githubusercontent.com/2172370/229410665-72132f59-770f-4f10-a400-47c620c0e50f.png)

**Comment by dimitre** [comment]
Great find. it seems the fix is not so complex.
I've been working on PG in the latest months and I'm a bit disappointed of how it works. It was super useful until now but maybe we can do something better from scratch. if not in openFrameworks project, maybe as a side project / fork.

The things I don't agree is the way addons.make is treated (overwritten every time now) so it doesn't fit like a recipe. because if you don't have the addon cloned already it will remove from the list.

And this recipe, or another format of recipe could accept specific git addresses, with tags or checkouts as a parameter, like platformio does, or cargo. 

And I've been experimenting a lot with Chalet build system with Ninja backend. And making all core addons work with little effort. I think it has great potential.

I know the rest are pretty non standard and it is hard to be absorbed in OF perspective of breaking as little as possible but here it goes:
We could use GLOB format instead of Make format in inclusions / exclusions, so it is more universal of a syntax. Much more compact code also.

Maybe the recipe can make use of a more universal language than Makefiles, like maybe YML or JSON

Just some random thoughts on today's Project Generator

**Comment by artificiel** [comment]
hehe I did not mean for my "OF_PATH"-relative addon suggestion to trigger a discussion on the whole PG/toolchain re-design (even though there is plenty of room for thought!) just to mention that adjacent to the required changes to make the OF reference work would be that low-hanging fruit of correcting the addon references to be relative to OF_PATH instead of the project.

that being said in terms of fixing this specific issue, of course I'll reiterate the fastest fix is simply not to include the OF directory in the sidebar as it's technically superfluous, augments cognitive load with information to subtract (if one wishes to understand/grasp the compilation process), and it may confuse beginners into thinking it's actually part of the target (and miss the actual OF-compile phase, which is obfuscated by the presence of this impersonation).

it's not false that it's a shortcut to the OF source-as-reference (and modifications), but if you want that in a project it's a mere drag&drop away.

**Comment by ofTheo** [comment]
@dimitre yeah - I share those frustrations. 

If there was a node / npm solution that would at least remove the cross complexity of having two different languages needed to build the PG.  But who knows what other bugs might get introduced.  CMake would be an obvious solution but that would also be a big overhaul. 

> The things I don't agree is the way addons.make is treated 


I think there could probably be a way to not have addons.make get cleared when addons aren't found and only pass the addons to the command line PG if they exist ( of have PG ignore non existent addons ).

**Comment by artificiel** [comment]
I think it's a case where the GUI is better designed than the plain command line (it reports non-existing addons and warns about overwriting the project settings). if I understand @dimitre's point vs the direct command line usage, the command line will take an addons.make with non-existent addons, ignore them, and restitute an addons.make without them? if that is the case, that is a bug (masked by the PG-GUI behaviour, which normal people use) and an issue should be created for it: PG commandline should not process a project unless all addons.make addons are found (unless --force or something).

**Comment by dimitre** [comment]
there is some discussion here about this https://github.com/openframeworks/projectGenerator/issues/258
