### ISSUE TITLE
ofxTCPServer not releasing offline clients

### ISSUE THREAD

**Issue by leonyuhanov** [openframeworks/openFrameworks#7610]
Have an instance of ofxTCPServer running on an Raspberry Pi 4. If a tcp client goes offline(for whatever reason) the tcp server still lists them as a connected client. Running 

```
TCP.isClientConnected(i)
```
Where i is the clients last known clientID still reports a connected client even though its offline. 
getNumClients() also reports that there is a connected client even though its not online!

How do we handle this? If TCP.isClientConnected(i) always returns true for an offline device, I can not use disconnectClient to purge it form the server

**Comment by ofTheo** [comment]
looking at the implementation you might need to send a message / ping to the client to check if its still connected. 
if you do that it will update the connected clients list and those functions will work as expected.

**Comment by leonyuhanov** [comment]
@ofTheo I suspected as much, but this is pretty time intensive. Often takes about 5 seconds for the server to offload the client once a bunch of sends fail. 
I have moved back to using UDP for my project, but this is maybe something to add

**Comment by artificiel** [comment]
to build on what @ofTheo says, the TCP protocol is not responsible to detect unexpected disconnections; it is the application's problem. so I guess the question is: should ofxTCPManager include an "active monitoring" feature that implements a hidden ping and actively disconnect poorly performing hosts? 

part of the resiliency of TCP is surviving network brownouts while guaranteeing ordered delivery. so think that your packet might be emitted over your wifi, onto the internet around the word, back down into a cheap router, NAT'ed into another bad wifi connection, and ack'ed (same way back) by an struggling ESP32 in a lightbulb. what is the appropriate latency window? [2 hours, says linux](https://man7.org/linux/man-pages/man7/tcp.7.html) — so your use case is very different than what the design of TCP is about.

note that there is the possibility of enabling a `TCP keep-alive` on a socket, but [the parameters are OS-wide](https://stackoverflow.com/questions/1480236/does-a-tcp-socket-connection-have-a-keep-alive). if you want a quick headache, go in your pi terminal and type 

`cat /proc/sys/net/ipv4/tcp_` followed by `<tab>`

you'll see all the parameters you can tweak at the OS level...

because all needs are subtly different, I would not rely on a generic compromise but implement the specific logic I need in my own application layer and tie it specifically to my operational parameters. so for example: if you don't get an active answer (not just a TCP ACK) to a ping message within e.g. 100ms, you close the connection yourself. of course the lower the latency you're aiming for, the more traffic you'll generate.

**Comment by leonyuhanov** [comment]
@artificiel fair points, understood
