### ISSUE TITLE
Lots of build errors when building for Any Mac Xcode

### ISSUE THREAD

**Issue by sebleedelisle** [openframeworks/openFrameworks#7698]
Seems to be new for 0.12.0 - I'm pretty sure I'm on a recent release build, but will try now with the nightly. 

**[EDIT - the issue doesn't occur on the release for 0.12.0, it's only on the nightlies]**

Way to replicate : 

Create new empty project in PG

Open it in Xcode

Change the build target from "My Mac" to "Any Mac (Apple Silicon, Intel)

Compile. 

I get a massive list of undefined errors, seem related to SSL or encryption?  

![Screenshot 2023-10-05 at 12 15 04](https://github.com/openframeworks/openFrameworks/assets/110866/c7103c4b-0305-4eb1-8496-62a5c708461b)

Let me know if there's anything else I can do to help!

**Comment by sebleedelisle** [comment]
I can confirm that this also happens on the latest nightly.

**Comment by dimitre** [comment]
Maybe it is related to download_libs.sh, I'll test running the script again

**Comment by sebleedelisle** [comment]
Ah thanks @dimitre, I'm on Xcode 13.4.1, MacOS 12.4 - do you think it's worth upgrading? 

I'll try from GitHub later this afternoon.

**Comment by sebleedelisle** [comment]
OK same deal having tested the latest from GitHub

**Comment by ofZach** [comment]
does it help if you adjust anything about the deployment target ?  (I haven't had ssh errors, but I have seen this pop up recently with some linking related issues) 

<img width="821" alt="Screenshot 2023-10-05 at 8 29 14 AM" src="https://github.com/openframeworks/openFrameworks/assets/142897/543522a9-fd06-4275-94a9-4ffd2f812c4e">

**Comment by dimitre** [comment]
I confirm here the same issues downloading the libs from latest. updating XCode won't help
And I think this is the same issue : https://github.com/openframeworks/openFrameworks/issues/7656

**Comment by sebleedelisle** [comment]
@ofZach I've tried changing this option to several different OS versions and still get the issue. Is this the setting you mean? Thanks!

![Screenshot 2023-10-05 at 13 38 55](https://github.com/openframeworks/openFrameworks/assets/110866/eb9c85a3-15fb-4724-a92b-de973650a6fb)

**Comment by sebleedelisle** [comment]
Ah I just double checked and it does actually work on the release for 0.12.0, but it doesn't work on the nightlies / GitHub.

**Comment by ofTheo** [comment]
Ahhh yes. This is because GitHub Actions dropped Xcode 11 shortly after OF 0.12 was released which allowed us to build curl with the missing symbols. Message ID: ***@***.***>
There’s a thread about it here #7656. And a solution: https://github.com/openframeworks/openFrameworks/issues/7656#issuecomment-1728204296only changes needed for a vanilla install are:change this line to:HEADER_CURL = ""and change this line to:LIB_CURL = "-lcurl"Those are found in  CoreOF.xcconfig https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig#L40

**Comment by ofTheo** [comment]
Ahhh yes. This is because GitHub Actions dropped Xcode 11 shortly after OF 0.12 was released which allowed us to build curl with the missing symbols.

There’s a thread about it here #7656. 

And a solution: https://github.com/openframeworks/openFrameworks/issues/7656#issuecomment-1728204296

only changes needed for a vanilla install are:
[change this line](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig#L24) to:
HEADER_CURL = ""

and [change this line](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig#L40) to:
LIB_CURL = "-lcurl"

Those are found in [CoreOF.xcconfig](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/osx/CoreOF.xcconfig)

**Comment by sebleedelisle** [comment]
That worked! Thank you so much @ofTheo ❤️
