### ISSUE TITLE
emscripten / linux(make) build conflicts and renaming suggestion (compiled Emscripten files)

### ISSUE THREAD

**Issue by Jonathhhan** [openframeworks/openFrameworks#7749]
If I build an Emscripten example and try after that to build this example with make for Linux I get this error:
`/usr/bin/ld.gold: fatal error: bin/threadedImageLoaderExample: open: Is a directory`
If I compile the Linux example first I get:
`mkdir: cannot create directory ‘bin/threadedImageLoaderExample’: File exists`

My renaming suggestion is to name only the html file `index` and the other files `threadedImageLoaderExample` (or whatever the patch is called).

**Comment by artificiel** [comment]
I'm not 100% sure but as I understand your renaming suggestion you would rollback the change that was made to encapsulate the emscripten output inside a directory (instead of directly at the `bin` top-level)? the idea for that change was to make it simpler to move and access a project on servers (simpler path due to implicit index.html and a single object to copy with no renaming required).

so as you now reveal, if we are building multiple architectures in a given project, there is a naming conflict between linux binary executable and the emscripten dir.

perhaps write the emscripten stuff in`bin/dist/${PROJECT_NAME}`? so  the `${PROJECT_NAME}` subdirectory can still be uploaded as-is, and `dist` does not conflict with the binary exec? 

or `bin/web/${PROJECT_NAME}`? `bin/em/${PROJECT_NAME}`?

**Comment by artificiel** [comment]
ah! OK then it's a matter of deciding what happens in the URL when the directory is uploaded without renaming. your proposal would make URLs like: `https://some.com/path/exampleName_emscripten` which seems a bit cumbersome. 

pushing the emscripten build down one level in `bin/em` or `bin/dist` allows one to have `https://some.com/path/exampleName`. (I'm thinking specifically of automatically-uploaded builds (for instance, replicating the OF examples in integrality on the web), where having a processing phase to regexp `_emscripten` out of the dir name might be fragile)

**Comment by Jonathhhan** [comment]
> your proposal would make URLs like: https://some.com/path/exampleName_emscripten which seems a bit cumbersome.

That's true. Did not thought about that (was always uploading the single files).

**Comment by ofTheo** [comment]
maybe: 
`bin/upload/exampleName/` could be the way to go?

**Comment by artificiel** [comment]
reading over the above I favour `bin/em/exampleName` because it's locally relevant (i.e. even if you're not concerned about uploads, it's still your em "build".)

**Comment by Jonathhhan** [comment]
I also favour `bin/em/exampleName` (or something like that), because it is not necessarily an upload?

**Comment by ofTheo** [comment]
sounds good to me :) 
👍
