### ISSUE TITLE
[ios] libraries - pugixml missing?

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#8194]
/Volumes/tool/ofw/libs/pugixml/lib/macos/pugixml.xcframework:1:1 While building for iOS, no library for this platform was found in '/Volumes/tool/ofw/libs/pugixml/lib/macos/pugixml.xcframework'.

**Comment by ofTheo** [comment]
I think iOS is working now right @artificiel ? 
Can we close this?

**Comment by artificiel** [comment]
it's hard to say as there is no clear information on the context of where the reported error occurred. 

FWIW `xmlSettingsExample` compiles and runs fine with `of_v20241109_ios_release`. 

i do notice in the reported error path above the presence of `/macos/` maybe the encountered error is related to path libs "exploration"? again lacking context to ensure.

**Comment by ofTheo** [comment]
@artificiel @dimitre 
Sounds like we need to be using the same PG in the CI that's been shipped ( 0.83.0 ). 
We should check the actions and see what PG version is being used . 

Was this in the nightly release @artificiel or the latest release?

**Comment by ofTheo** [comment]
Hmm the nightly is using 0.86.0 see: 

```
projectGenerator exists...
PG building example projects
  [notice ] { "openFrameworks projectGenerator": "0.86.0" }
  [notice ] ofPath set and valid using ["/home/runner/work/openFrameworks/openFrameworks/out/openFrameworks_pkg_creation"]
  
  [notice ] -----------------------------------------------
  [notice ] updating an existing project
  [notice ] target platform is: ios
  [notice ] recursiveUpdate "/home/runner/work/openFrameworks/openFrameworks/out/openFrameworks_pkg_creation/examples"

```

Is this a regression with 0.83.0 to 0.86.0 ?

**Comment by artificiel** [comment]
above testing was done in the context of #8192 with `of_v20241109_ios_release` which includes 0.83.0. 

just re-checked with `of_v20241121_ios_release` which now includes 0.86.0, and it's the same: the delivered example projects do not include subfolders, but running 0.86.0 over them fixes it. so either a regression in PG (since at least a little while) or something related to command-line invocation or some other env condition of CI.

NB: "get info" on the PG app reports v 0.67.0:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/293174d1-bfff-4680-bf84-770c4dbeedbf">

**Comment by dimitre** [comment]
Yeah once Dan added this info to "reflect" PG command line. but it got outdated soon. 
I think they are two very different pieces of software, they should have independent versions.

**Comment by dimitre** [comment]
I'm closing this one as I've downloaded the latest libs and worked OK
